// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 1763929c89cf4969 "Patrick McKowen", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * image?: {src: string, srcSet?: string, alt?: string} // Image
 * title?: string // Title
 * titleHover?: string // Title Hover
}} Props

 */
import { routes } from "./chunks/chunk-IRNZKG45.js";

// virtual:about-photo
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/ncrFhbDcJMs60WFLOQ1W/irj4fuJyQTy4U2nmduLO/rQpGcm7zK.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	Image,
	RichText,
	useConstant,
	useIsOnFramerCanvas,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";

// /:https://framerusercontent.com/modules/NB2uUjp5kqIPx74erx62/Z1l7wDXF5vxM60fkeNbu/OVJg2gdOu.js
import { fontStore } from "unframer";
fontStore.loadFonts([
	"CUSTOM;Geist Mono Variable Regular",
	"Inter-Bold",
	"Inter-BoldItalic",
	"Inter-Italic",
]);
var fonts = [
	{
		family: "Geist Mono Variable Regular",
		source: "custom",
		url: "https://framerusercontent.com/assets/awrUu69VgkDKQl3yHJCBKi9Zam8.woff2",
	},
];
var css = [
	'.framer-Z1867 .framer-styles-preset-sw3ylo:not(.rich-text-wrapper), .framer-Z1867 .framer-styles-preset-sw3ylo.rich-text-wrapper p { --framer-font-family: "Geist Mono Variable Regular", "Geist Mono Variable Regular Placeholder", monospace; --framer-font-family-bold: "Inter-Bold", "Inter", "Inter Placeholder", sans-serif; --framer-font-family-bold-italic: "Inter-BoldItalic", "Inter", "Inter Placeholder", sans-serif; --framer-font-family-italic: "Inter-Italic", "Inter", "Inter Placeholder", sans-serif; --framer-font-size: 12px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-style-bold-italic: italic; --framer-font-style-italic: italic; --framer-font-weight: 400; --framer-font-weight-bold: 700; --framer-font-weight-bold-italic: 700; --framer-font-weight-italic: 400; --framer-letter-spacing: 0em; --framer-line-height: 1.5em; --framer-paragraph-spacing: 12px; --framer-text-alignment: start; --framer-text-color: var(--token-949a3add-eac1-4ce7-abe1-88da755f4b37, rgba(0, 0, 0, 0.45)); --framer-text-decoration: none; --framer-text-transform: none; }',
];
var className = "framer-Z1867";

// /:https://framerusercontent.com/modules/ncrFhbDcJMs60WFLOQ1W/irj4fuJyQTy4U2nmduLO/rQpGcm7zK.js
var enabledGestures = {
	HedKtaBZ6: {
		hover: true,
	},
};
var cycleOrder = ["HedKtaBZ6"];
var serializationHash = "framer-WYpof";
var variantClassNames = {
	HedKtaBZ6: "framer-v-hszrs1",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants === null || variants === void 0
		? void 0
		: variants.forEach(
				(variant) =>
					variant && Object.assign(nextOverrides, overrides[variant]),
			);
	return nextOverrides;
}
var transitions = {
	default: {
		damping: 60,
		delay: 0,
		mass: 1,
		stiffness: 500,
		type: "spring",
	},
};
var toResponsiveImage = (value) => {
	if (
		typeof value === "object" &&
		value !== null &&
		typeof value.src === "string"
	) {
		return value;
	}
	return typeof value === "string"
		? {
				src: value,
			}
		: void 0;
};
var transformTemplate1 = (_, t) => `translateY(-50%) ${t}`;
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition =
		value !== null && value !== void 0 ? value : config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var getProps = ({ height, id, image, title, titleHover, width, ...props }) => {
	var _ref, _ref1, _ref2;
	return {
		...props,
		dXgaQ6pAA:
			(_ref = title !== null && title !== void 0 ? title : props.dXgaQ6pAA) !==
				null && _ref !== void 0
				? _ref
				: "My favorite person",
		R6MVe3Sgp:
			(_ref1 =
				titleHover !== null && titleHover !== void 0
					? titleHover
					: props.R6MVe3Sgp) !== null && _ref1 !== void 0
				? _ref1
				: "My wife Alena",
		TGRhczkgt:
			(_ref2 = image !== null && image !== void 0 ? image : props.TGRhczkgt) !==
				null && _ref2 !== void 0
				? _ref2
				: {
						src: "https://framerusercontent.com/images/5mU0S2dPBpsu0x2KV0HszWUn5Wc.png",
					},
	};
};
var createLayoutDependency = (props, variants) =>
	variants.join("-") + props.layoutDependency;
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const { activeLocale, setLocale } = useLocaleInfo();
	const {
		style,
		className: className2,
		layoutId,
		variant,
		TGRhczkgt,
		dXgaQ6pAA,
		R6MVe3Sgp,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		gestureVariant,
		setGestureState,
		setVariant,
		transition,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "HedKtaBZ6",
		enabledGestures,
		transitions,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const isOnCanvas = useIsOnFramerCanvas();
	const initialVariant = useConstant(() => variant);
	const ref1 = React.useRef(null);
	const defaultLayoutId = React.useId();
	const sharedStyleClassNames = [className];
	return (
		<LayoutGroup
			id={layoutId !== null && layoutId !== void 0 ? layoutId : defaultLayoutId}
		>
			<Transition value={transition}>
				<motion.div
					{...restProps}
					animate={variants}
					className={cx(
						serializationHash,
						...sharedStyleClassNames,
						"framer-hszrs1",
						className2,
						classNames,
					)}
					data-framer-name={"Variant 1"}
					initial={isOnCanvas ? variant : initialVariant}
					layoutDependency={layoutDependency}
					layoutId={"HedKtaBZ6"}
					onHoverEnd={() =>
						setGestureState({
							isHovered: false,
						})
					}
					onHoverStart={() =>
						setGestureState({
							isHovered: true,
						})
					}
					onTap={() =>
						setGestureState({
							isPressed: false,
						})
					}
					onTapCancel={() =>
						setGestureState({
							isPressed: false,
						})
					}
					onTapStart={() =>
						setGestureState({
							isPressed: true,
						})
					}
					ref={ref !== null && ref !== void 0 ? ref : ref1}
					style={{
						...style,
					}}
					{...addPropertyOverrides(
						{
							"HedKtaBZ6-hover": {
								"data-framer-name": void 0,
							},
						},
						baseVariant,
						gestureVariant,
					)}
				>
					<Image
						background={{
							alt: "",
							fit: "fill",
							intrinsicHeight: 224,
							intrinsicWidth: 224,
							pixelHeight: 448,
							pixelWidth: 448,
							sizes: "min(224px, 100vw)",
							...toResponsiveImage(TGRhczkgt),
						}}
						className={"framer-e4ller"}
						data-framer-name={"image"}
						layoutDependency={layoutDependency}
						layoutId={"NWWkhCWUE"}
					/>
					<motion.div
						className={"framer-s00owf"}
						data-framer-name={"About Photo Caption"}
						layoutDependency={layoutDependency}
						layoutId={"NggYGrkF_"}
					>
						<RichText
							__fromCanvasComponent={true}
							className={"framer-1g3kowv"}
							fonts={["CUSTOM;Geist Mono Variable Regular"]}
							layoutDependency={layoutDependency}
							layoutId={"FIW7Ik75N"}
							style={{
								"--extracted-r6o4lv":
									"var(--token-896a38fe-d0ec-4731-b86b-9b448c2d2dcc, rgba(255, 255, 255, 0.45))",
								"--framer-link-text-color": "rgb(0, 153, 255)",
								"--framer-link-text-decoration": "underline",
							}}
							text={R6MVe3Sgp}
							verticalAlignment={"top"}
							withExternalLayout={true}
						>
							<React.Fragment>
								<motion.p
									style={{
										"--font-selector":
											"Q1VTVE9NO0dlaXN0IE1vbm8gVmFyaWFibGUgUmVndWxhcg==",
										"--framer-font-family":
											'"Geist Mono Variable Regular", "Geist Mono Variable Regular Placeholder", monospace',
										"--framer-font-size": "12px",
										"--framer-line-height": "1em",
										"--framer-text-color":
											"var(--extracted-r6o4lv, var(--token-896a38fe-d0ec-4731-b86b-9b448c2d2dcc, rgba(255, 255, 255, 0.45)))",
									}}
								>
									{"My wife Alena"}
								</motion.p>
							</React.Fragment>
						</RichText>
						<RichText
							__fromCanvasComponent={true}
							className={"framer-ct34a1"}
							layoutDependency={layoutDependency}
							layoutId={"MZPJKHt9j"}
							style={{
								"--extracted-r6o4lv":
									"var(--token-896a38fe-d0ec-4731-b86b-9b448c2d2dcc, rgba(255, 255, 255, 0.45))",
								"--framer-link-text-color": "rgb(0, 153, 255)",
								"--framer-link-text-decoration": "underline",
							}}
							text={dXgaQ6pAA}
							transformTemplate={transformTemplate1}
							verticalAlignment={"top"}
							withExternalLayout={true}
							{...addPropertyOverrides(
								{
									"HedKtaBZ6-hover": {
										transformTemplate: void 0,
									},
								},
								baseVariant,
								gestureVariant,
							)}
						>
							<React.Fragment>
								<motion.p
									className={"framer-styles-preset-sw3ylo"}
									data-styles-preset={"OVJg2gdOu"}
									style={{
										"--framer-text-color":
											"var(--extracted-r6o4lv, var(--token-896a38fe-d0ec-4731-b86b-9b448c2d2dcc, rgba(255, 255, 255, 0.45)))",
									}}
								>
									{"My favorite person"}
								</motion.p>
							</React.Fragment>
						</RichText>
					</motion.div>
				</motion.div>
			</Transition>
		</LayoutGroup>
	);
});
var css2 = [
	'.framer-WYpof[data-border="true"]::after, .framer-WYpof [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; pointer-events: none; }',
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-WYpof.framer-vf1q04, .framer-WYpof .framer-vf1q04 { display: block; }",
	".framer-WYpof.framer-hszrs1 { align-content: flex-start; align-items: flex-start; cursor: pointer; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 8px; height: min-content; justify-content: flex-start; overflow: hidden; padding: 0px 0px 0px 0px; position: relative; width: 224px; }",
	".framer-WYpof .framer-e4ller { aspect-ratio: 1 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 200px); overflow: visible; position: relative; width: 100%; }",
	".framer-WYpof .framer-s00owf { flex: none; height: 15px; overflow: hidden; position: relative; width: 100%; }",
	".framer-WYpof .framer-1g3kowv { bottom: -20px; flex: none; height: auto; left: 0px; position: absolute; white-space: pre; width: auto; }",
	".framer-WYpof .framer-ct34a1 { flex: none; height: auto; left: 0px; position: absolute; top: 47%; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
	"@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-WYpof.framer-hszrs1 { gap: 0px; } .framer-WYpof.framer-hszrs1 > * { margin: 0px; margin-bottom: calc(8px / 2); margin-top: calc(8px / 2); } .framer-WYpof.framer-hszrs1 > :first-child { margin-top: 0px; } .framer-WYpof.framer-hszrs1 > :last-child { margin-bottom: 0px; } }",
	".framer-WYpof.framer-v-hszrs1.hover .framer-1g3kowv { bottom: unset; top: 0px; }",
	".framer-WYpof.framer-v-hszrs1.hover .framer-ct34a1 { top: -20px; }",
	...css,
];
var FramerrQpGcm7zK = withCSS(Component, css2, "framer-WYpof");
var stdin_default = FramerrQpGcm7zK;
FramerrQpGcm7zK.displayName = "About Photo";
FramerrQpGcm7zK.defaultProps = {
	height: 247,
	width: 224,
};
addPropertyControls(FramerrQpGcm7zK, {
	TGRhczkgt: {
		__defaultAssetReference:
			"data:framer/asset-reference,5mU0S2dPBpsu0x2KV0HszWUn5Wc.png?originalFilename=image.png&preferredSize=auto",
		title: "Image",
		type: ControlType.ResponsiveImage,
	},
	dXgaQ6pAA: {
		defaultValue: "My favorite person",
		displayTextArea: false,
		title: "Title",
		type: ControlType.String,
	},
	R6MVe3Sgp: {
		defaultValue: "My wife Alena",
		displayTextArea: false,
		title: "Title Hover",
		type: ControlType.String,
	},
});
addFonts(FramerrQpGcm7zK, [
	{
		family: "Geist Mono Variable Regular",
		source: "custom",
		url: "https://framerusercontent.com/assets/awrUu69VgkDKQl3yHJCBKi9Zam8.woff2",
	},
	...fonts,
]);

// virtual:about-photo
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"1763929c89cf4969ad190da187fc25ea516fa82b7cf163cf1161896117bee1d5"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders AboutPhotoFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"1763929c89cf4969ad190da187fc25ea516fa82b7cf163cf1161896117bee1d5"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var about_photo_default = ComponentWithRoot;
export { about_photo_default as default };
