// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 1763929c89cf4969 "Patrick McKowen", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Light' | 'Dark' // Variant
 * title?: string // Title
 * link?: string // Link
 * newTab?: boolean // New Tab
 * hasIcon?: boolean // Has Icon
}} Props

 */
import { routes } from "./chunks/chunk-IRNZKG45.js";

// virtual:button
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/7XzKPlfsEG3dFA5y05Lj/GjGqraCXEC2tIgdmb5Bc/lUTKU3TmQ.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	Link,
	RichText,
	SVG,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var enabledGestures = {
	TtNfABr5k: {
		hover: true,
		pressed: true,
	},
	vqnKsoj9D: {
		hover: true,
		pressed: true,
	},
};
var cycleOrder = ["TtNfABr5k", "vqnKsoj9D"];
var serializationHash = "framer-UfqWI";
var variantClassNames = {
	TtNfABr5k: "framer-v-1rgwqee",
	vqnKsoj9D: "framer-v-gnhfg3",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	damping: 40,
	delay: 0,
	mass: 1,
	stiffness: 800,
	type: "spring",
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
	Dark: "vqnKsoj9D",
	Light: "TtNfABr5k",
};
var getProps = ({
	hasIcon,
	height,
	id,
	link,
	newTab,
	title,
	width,
	...props
}) => {
	return {
		...props,
		fZNKmQbgw: link ?? props.fZNKmQbgw,
		M6dyw0jBD: newTab ?? props.M6dyw0jBD,
		NOJL9PoSg: title ?? props.NOJL9PoSg ?? "Case Study",
		SS1nsta_X: hasIcon ?? props.SS1nsta_X ?? true,
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "TtNfABr5k",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className,
		layoutId,
		variant,
		NOJL9PoSg: NOJL9PoSg2,
		fZNKmQbgw: fZNKmQbgw2,
		M6dyw0jBD: M6dyw0jBD2,
		SS1nsta_X: SS1nsta_X2,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "TtNfABr5k",
		enabledGestures,
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<Link
						href={fZNKmQbgw2}
						motionChild={true}
						nodeId={"TtNfABr5k"}
						scopeId={"lUTKU3TmQ"}
						{...addPropertyOverrides(
							{
								vqnKsoj9D: {
									openInNewTab: M6dyw0jBD2,
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion.a
							{...restProps}
							{...gestureHandlers}
							className={`${cx(scopingClassNames, "framer-1rgwqee", className, classNames)} framer-1uxlv83`}
							data-framer-name={"Light"}
							layoutDependency={layoutDependency}
							layoutId={"TtNfABr5k"}
							ref={refBinding}
							style={{
								"--border-bottom-width": "0px",
								"--border-color": "rgba(0, 0, 0, 0)",
								"--border-left-width": "0px",
								"--border-right-width": "0px",
								"--border-style": "solid",
								"--border-top-width": "0px",
								backdropFilter: "blur(5px)",
								backgroundColor: "rgba(255, 255, 255, 0.8)",
								borderBottomLeftRadius: 100,
								borderBottomRightRadius: 100,
								borderTopLeftRadius: 100,
								borderTopRightRadius: 100,
								boxShadow:
									"0px 1px 1px 0px rgba(0, 0, 0, 0.03), 0px 1px 1px 0px rgba(0, 0, 0, 0.02), 0px 2px 1px 0px rgba(0, 0, 0, 0.01), 0px 4px 1px 0px rgba(0, 0, 0, 0)",
								WebkitBackdropFilter: "blur(5px)",
								...style,
							}}
							variants={{
								"TtNfABr5k-hover": {
									"--border-bottom-width": "0px",
									"--border-left-width": "0px",
									"--border-right-width": "0px",
									"--border-top-width": "0px",
									backgroundColor: "rgba(255, 255, 255, 0.9)",
								},
								"TtNfABr5k-pressed": {
									"--border-bottom-width": "0px",
									"--border-left-width": "0px",
									"--border-right-width": "0px",
									"--border-top-width": "0px",
									backgroundColor: "rgba(250, 250, 250, 0.9)",
								},
								"vqnKsoj9D-hover": {
									backgroundColor: "rgb(51, 51, 51)",
								},
								"vqnKsoj9D-pressed": {
									backgroundColor: "rgb(51, 51, 51)",
								},
								vqnKsoj9D: {
									"--border-bottom-width": "1px",
									"--border-color": "rgba(255, 255, 255, 0.04)",
									"--border-left-width": "1px",
									"--border-right-width": "1px",
									"--border-style": "solid",
									"--border-top-width": "1px",
									backgroundColor: "rgb(38, 38, 38)",
									boxShadow:
										"0px 1px 2px -1px rgba(0, 0, 0, 0.05), 0px 2px 4px -2px rgba(0, 0, 0, 0.05), 0px 3px 6px -3px rgba(0, 0, 0, 0.05), 0px 4px 8px -4px rgba(0, 0, 0, 0.05)",
								},
							}}
							{...addPropertyOverrides(
								{
									"TtNfABr5k-hover": {
										"data-framer-name": void 0,
									},
									"TtNfABr5k-pressed": {
										"data-framer-name": void 0,
									},
									"vqnKsoj9D-hover": {
										"data-framer-name": void 0,
									},
									"vqnKsoj9D-pressed": {
										"data-framer-name": void 0,
									},
									vqnKsoj9D: {
										"data-border": true,
										"data-framer-name": "Dark",
									},
								},
								baseVariant,
								gestureVariant,
							)}
						>
							<RichText
								__fromCanvasComponent={true}
								className={"framer-11ohume"}
								data-framer-name={"Case Study"}
								fonts={["CUSTOM;Geist Regular"]}
								layoutDependency={layoutDependency}
								layoutId={"txBOAxLCd"}
								style={{
									"--extracted-r6o4lv":
										"var(--token-089597d0-362c-414f-b3b0-277cb81925bd, rgb(0, 0, 0))",
									"--framer-paragraph-spacing": "0px",
								}}
								text={NOJL9PoSg2}
								variants={{
									vqnKsoj9D: {
										"--extracted-r6o4lv":
											"var(--token-464632b9-70af-47b9-93b4-8eb38f80e40f, rgb(255, 255, 255))",
									},
								}}
								verticalAlignment={"top"}
								withExternalLayout={true}
								{...addPropertyOverrides(
									{
										vqnKsoj9D: {
											children: (
												<React.Fragment>
													<motion.p
														style={{
															"--font-selector": "Q1VTVE9NO0dlaXN0IFJlZ3VsYXI=",
															"--framer-font-family":
																'"Geist Regular", "Geist Regular Placeholder", sans-serif',
															"--framer-font-size": "18px",
															"--framer-line-height": "1.6em",
															"--framer-text-alignment": "left",
															"--framer-text-color":
																"var(--extracted-r6o4lv, var(--token-464632b9-70af-47b9-93b4-8eb38f80e40f, rgb(255, 255, 255)))",
														}}
													>
														{"Case Study"}
													</motion.p>
												</React.Fragment>
											),
										},
									},
									baseVariant,
									gestureVariant,
								)}
							>
								<React.Fragment>
									<motion.p
										style={{
											"--font-selector": "Q1VTVE9NO0dlaXN0IFJlZ3VsYXI=",
											"--framer-font-family":
												'"Geist Regular", "Geist Regular Placeholder", sans-serif',
											"--framer-font-size": "18px",
											"--framer-line-height": "1.6em",
											"--framer-text-color":
												"var(--extracted-r6o4lv, var(--token-089597d0-362c-414f-b3b0-277cb81925bd, rgb(0, 0, 0)))",
										}}
									>
										{"Case Study"}
									</motion.p>
								</React.Fragment>
							</RichText>
							{SS1nsta_X2 !== false && (
								<motion.div
									className={"framer-haem03"}
									data-framer-name={"Icon"}
									layoutDependency={layoutDependency}
									layoutId={"ZZJq2zlZb"}
								>
									<SVG
										className={"framer-1awk7c0"}
										data-framer-name={"graphic"}
										layout={"position"}
										layoutDependency={layoutDependency}
										layoutId={"lJFX4cgBq"}
										opacity={1}
										svg={
											'<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 14 14"><path d="M 13.223 9.88 C 13.223 10.12 13.141 10.32 12.977 10.477 C 12.833 10.629 12.633 10.716 12.423 10.715 C 12.209 10.716 12.004 10.627 11.86 10.469 C 11.714 10.321 11.633 10.122 11.632 9.915 L 11.632 6.663 L 11.79 2.559 L 10.34 4.202 L 1.612 12.921 C 1.468 13.073 1.268 13.159 1.059 13.158 C 0.916 13.159 0.775 13.12 0.654 13.044 C 0.532 12.969 0.43 12.867 0.355 12.745 C 0.281 12.623 0.242 12.484 0.241 12.341 C 0.241 12.136 0.323 11.951 0.487 11.787 L 9.197 3.06 L 10.832 1.627 L 6.543 1.767 L 3.484 1.767 C 3.277 1.766 3.079 1.684 2.931 1.539 C 2.781 1.395 2.695 1.196 2.693 0.987 C 2.691 0.779 2.774 0.579 2.922 0.432 C 3.076 0.267 3.294 0.177 3.52 0.186 L 12.361 0.186 C 12.625 0.186 12.833 0.265 12.985 0.423 C 13.141 0.589 13.223 0.811 13.214 1.038 Z" fill="var(--token-0b05e8d8-074c-4ec2-beac-cfabe9f31de9, rgba(0, 0, 0, 0.85))"></path></svg>'
										}
										svgContentId={9267023082}
										withExternalLayout={true}
										{...addPropertyOverrides(
											{
												vqnKsoj9D: {
													svg: '<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 14 14"><path d="M 13.223 9.88 C 13.223 10.12 13.141 10.32 12.977 10.477 C 12.833 10.629 12.633 10.716 12.423 10.715 C 12.209 10.716 12.004 10.627 11.86 10.469 C 11.714 10.321 11.633 10.122 11.632 9.915 L 11.632 6.663 L 11.79 2.559 L 10.34 4.202 L 1.612 12.921 C 1.468 13.073 1.268 13.159 1.059 13.158 C 0.916 13.159 0.775 13.12 0.654 13.044 C 0.532 12.969 0.43 12.867 0.355 12.745 C 0.281 12.623 0.242 12.484 0.241 12.341 C 0.241 12.136 0.323 11.951 0.487 11.787 L 9.197 3.06 L 10.832 1.627 L 6.543 1.767 L 3.484 1.767 C 3.277 1.766 3.079 1.684 2.931 1.539 C 2.781 1.395 2.695 1.196 2.693 0.987 C 2.691 0.779 2.774 0.579 2.922 0.432 C 3.076 0.267 3.294 0.177 3.52 0.186 L 12.361 0.186 C 12.625 0.186 12.833 0.265 12.985 0.423 C 13.141 0.589 13.223 0.811 13.214 1.038 Z" fill="var(--token-5c05223f-e6db-4f60-881e-1cad8809818b, rgb(255, 255, 255)) /* {&quot;name&quot;:&quot;White Text Primary&quot;} */"></path></svg>',
													svgContentId: 11544345874,
												},
											},
											baseVariant,
											gestureVariant,
										)}
									/>
								</motion.div>
							)}
						</motion.a>
					</Link>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-UfqWI.framer-1uxlv83, .framer-UfqWI .framer-1uxlv83 { display: block; }",
	".framer-UfqWI.framer-1rgwqee { align-content: center; align-items: center; cursor: pointer; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 8px; height: min-content; justify-content: center; overflow: visible; padding: 8px 20px 8px 20px; position: relative; text-decoration: none; width: min-content; }",
	".framer-UfqWI .framer-11ohume { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
	".framer-UfqWI .framer-haem03 { flex: none; height: 14px; overflow: visible; position: relative; width: 14px; }",
	".framer-UfqWI .framer-1awk7c0 { flex: none; height: 14px; left: calc(50.00000000000002% - 14px / 2); position: absolute; top: calc(50.00000000000002% - 14px / 2); width: 14px; }",
	".framer-UfqWI.framer-v-gnhfg3.framer-1rgwqee { overflow: hidden; will-change: var(--framer-will-change-override, transform); }",
	'.framer-UfqWI[data-border="true"]::after, .framer-UfqWI [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; corner-shape: inherit; pointer-events: none; }',
];
var FramerlUTKU3TmQ = withCSS(Component, css, "framer-UfqWI");
var stdin_default = FramerlUTKU3TmQ;
FramerlUTKU3TmQ.displayName = "Button";
FramerlUTKU3TmQ.defaultProps = {
	height: 45,
	width: 157,
};
addPropertyControls(FramerlUTKU3TmQ, {
	variant: {
		options: ["TtNfABr5k", "vqnKsoj9D"],
		optionTitles: ["Light", "Dark"],
		title: "Variant",
		type: ControlType.Enum,
	},
	NOJL9PoSg: {
		defaultValue: "Case Study",
		displayTextArea: false,
		title: "Title",
		type: ControlType.String,
	},
	fZNKmQbgw: {
		title: "Link",
		type: ControlType.Link,
	},
	M6dyw0jBD: {
		defaultValue: false,
		title: "New Tab",
		type: ControlType.Boolean,
	},
	SS1nsta_X: {
		defaultValue: true,
		title: "Has Icon",
		type: ControlType.Boolean,
	},
});
addFonts(
	FramerlUTKU3TmQ,
	[
		{
			explicitInter: true,
			fonts: [
				{
					cssFamilyName: "Geist Regular",
					source: "custom",
					style: "normal",
					uiFamilyName: "Geist",
					url: "https://framerusercontent.com/assets/fmgcvoo7Pvi75XN7wkBOp5g4i4s.woff2",
					weight: "400",
				},
			],
		},
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:button
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "TtNfABr5k",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"1763929c89cf4969ad190da187fc25ea516fa82b7cf163cf1161896117bee1d5"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders ButtonFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"1763929c89cf4969ad190da187fc25ea516fa82b7cf163cf1161896117bee1d5"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var button_default = ComponentWithRoot;
export { button_default as default };
