// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 1763929c89cf4969 "Patrick McKowen", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * title?: string // Title
 * description?: string // Description
}} Props

 */
import { className, css, fonts } from "./chunks/chunk-T6M5HMBG.js";
import { routes } from "./chunks/chunk-IRNZKG45.js";

// virtual:card
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/JKeWNG2ux78iMVWq3Lch/zMqnc9CrGDdWKNqu3MzJ/oXB2ggp1H.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	RichText,
	useConstant,
	useIsOnFramerCanvas,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";

// /:https://framerusercontent.com/modules/nl4d0I3VUBi6k7jJsKqV/HkPUWIRnxsYuKDoz57Ql/Le_xC7TsI.js
import { fontStore } from "unframer";
fontStore.loadFonts(["CUSTOM;Geist Regular", "CUSTOM;Geist Medium"]);
var fonts2 = [
	{
		explicitInter: true,
		fonts: [
			{
				family: "Geist Regular",
				source: "custom",
				url: "https://framerusercontent.com/assets/fmgcvoo7Pvi75XN7wkBOp5g4i4s.woff2",
			},
			{
				family: "Geist Medium",
				source: "custom",
				url: "https://framerusercontent.com/assets/dNqH0c4qjo3RGmYZnJknwKtT0.woff2",
			},
		],
	},
];
var css2 = [
	'.framer-nn2TP .framer-styles-preset-1ok24qa:not(.rich-text-wrapper), .framer-nn2TP .framer-styles-preset-1ok24qa.rich-text-wrapper p { --framer-font-family: "Geist Regular", "Geist Regular Placeholder", sans-serif; --framer-font-family-bold: "Geist Medium", "Geist Medium Placeholder", sans-serif; --framer-font-size: 16px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-weight: 400; --framer-font-weight-bold: 400; --framer-letter-spacing: 0em; --framer-line-height: 1.5em; --framer-paragraph-spacing: 16px; --framer-text-alignment: start; --framer-text-color: var(--token-949a3add-eac1-4ce7-abe1-88da755f4b37, rgba(0, 0, 0, 0.45)); --framer-text-decoration: none; --framer-text-transform: none; }',
	'@media (max-width: 1199px) and (min-width: 501px) { .framer-nn2TP .framer-styles-preset-1ok24qa:not(.rich-text-wrapper), .framer-nn2TP .framer-styles-preset-1ok24qa.rich-text-wrapper p { --framer-font-family: "Geist Regular", "Geist Regular Placeholder", sans-serif; --framer-font-family-bold: "Geist Medium", "Geist Medium Placeholder", sans-serif; --framer-font-size: 14px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-weight: 400; --framer-font-weight-bold: 400; --framer-letter-spacing: 0em; --framer-line-height: 1.5em; --framer-paragraph-spacing: 14px; --framer-text-alignment: start; --framer-text-color: var(--token-949a3add-eac1-4ce7-abe1-88da755f4b37, rgba(0, 0, 0, 0.45)); --framer-text-decoration: none; --framer-text-transform: none; } }',
	'@media (max-width: 500px) and (min-width: 0px) { .framer-nn2TP .framer-styles-preset-1ok24qa:not(.rich-text-wrapper), .framer-nn2TP .framer-styles-preset-1ok24qa.rich-text-wrapper p { --framer-font-family: "Geist Regular", "Geist Regular Placeholder", sans-serif; --framer-font-family-bold: "Geist Medium", "Geist Medium Placeholder", sans-serif; --framer-font-size: 10px; --framer-font-style: normal; --framer-font-style-bold: normal; --framer-font-weight: 400; --framer-font-weight-bold: 400; --framer-letter-spacing: 0em; --framer-line-height: 1.5em; --framer-paragraph-spacing: 16px; --framer-text-alignment: start; --framer-text-color: var(--token-949a3add-eac1-4ce7-abe1-88da755f4b37, rgba(0, 0, 0, 0.45)); --framer-text-decoration: none; --framer-text-transform: none; } }',
];
var className2 = "framer-nn2TP";

// /:https://framerusercontent.com/modules/JKeWNG2ux78iMVWq3Lch/zMqnc9CrGDdWKNqu3MzJ/oXB2ggp1H.js
var cycleOrder = ["U22LKdOYE"];
var serializationHash = "framer-05RVk";
var variantClassNames = {
	U22LKdOYE: "framer-v-mbvyor",
};
var transitions = {
	default: {
		damping: 60,
		delay: 0,
		mass: 1,
		stiffness: 500,
		type: "spring",
	},
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition =
		value !== null && value !== void 0 ? value : config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var getProps = ({ description, height, id, title, width, ...props }) => {
	var _ref, _ref1;
	return {
		...props,
		bvABklfQi:
			(_ref = title !== null && title !== void 0 ? title : props.bvABklfQi) !==
				null && _ref !== void 0
				? _ref
				: "Title",
		t_JPInD9n:
			(_ref1 =
				description !== null && description !== void 0
					? description
					: props.t_JPInD9n) !== null && _ref1 !== void 0
				? _ref1
				: "Description",
	};
};
var createLayoutDependency = (props, variants) =>
	variants.join("-") + props.layoutDependency;
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const { activeLocale, setLocale } = useLocaleInfo();
	const {
		style,
		className: className3,
		layoutId,
		variant,
		bvABklfQi,
		t_JPInD9n,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		gestureVariant,
		setGestureState,
		setVariant,
		transition,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "U22LKdOYE",
		transitions,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const isOnCanvas = useIsOnFramerCanvas();
	const initialVariant = useConstant(() => variant);
	const ref1 = React.useRef(null);
	const defaultLayoutId = React.useId();
	const sharedStyleClassNames = [className, className2];
	return (
		<LayoutGroup
			id={layoutId !== null && layoutId !== void 0 ? layoutId : defaultLayoutId}
		>
			<Transition value={transition}>
				<motion.div
					{...restProps}
					animate={variants}
					className={cx(
						serializationHash,
						...sharedStyleClassNames,
						"framer-mbvyor",
						className3,
						classNames,
					)}
					data-border={true}
					data-framer-name={"Variant 1"}
					initial={isOnCanvas ? variant : initialVariant}
					layoutDependency={layoutDependency}
					layoutId={"U22LKdOYE"}
					onHoverEnd={() =>
						setGestureState({
							isHovered: false,
						})
					}
					onHoverStart={() =>
						setGestureState({
							isHovered: true,
						})
					}
					onTap={() =>
						setGestureState({
							isPressed: false,
						})
					}
					onTapCancel={() =>
						setGestureState({
							isPressed: false,
						})
					}
					onTapStart={() =>
						setGestureState({
							isPressed: true,
						})
					}
					ref={ref !== null && ref !== void 0 ? ref : ref1}
					style={{
						"--border-bottom-width": "1.5px",
						"--border-color":
							'var(--token-88ded627-a466-4702-99e3-84aa865c34c4, rgb(235, 235, 235)) /* {"name":"Light Fig BG"} */',
						"--border-left-width": "1.5px",
						"--border-right-width": "1.5px",
						"--border-style": "solid",
						"--border-top-width": "1.5px",
						borderBottomLeftRadius: 8,
						borderBottomRightRadius: 8,
						borderTopLeftRadius: 8,
						borderTopRightRadius: 8,
						...style,
					}}
				>
					<RichText
						__fromCanvasComponent={true}
						className={"framer-6ot67p"}
						layoutDependency={layoutDependency}
						layoutId={"RKwZZnfix"}
						style={{
							"--extracted-r6o4lv":
								"var(--token-38e34800-80da-44a7-911f-74b9aae91a0c, rgba(0, 0, 0, 0.9))",
							"--framer-link-text-color": "rgb(0, 153, 255)",
							"--framer-link-text-decoration": "underline",
						}}
						text={bvABklfQi}
						verticalAlignment={"top"}
						withExternalLayout={true}
					>
						<React.Fragment>
							<motion.p
								className={"framer-styles-preset-1f40k0m"}
								data-styles-preset={"YYoNxvhFL"}
								style={{
									"--framer-text-color":
										"var(--extracted-r6o4lv, var(--token-38e34800-80da-44a7-911f-74b9aae91a0c, rgba(0, 0, 0, 0.9)))",
								}}
							>
								<motion.strong>{"Title"}</motion.strong>
							</motion.p>
						</React.Fragment>
					</RichText>
					<RichText
						__fromCanvasComponent={true}
						className={"framer-1h35uap"}
						layoutDependency={layoutDependency}
						layoutId={"E2f5caqEx"}
						style={{
							"--extracted-r6o4lv":
								"var(--token-949a3add-eac1-4ce7-abe1-88da755f4b37, rgba(0, 0, 0, 0.5))",
							"--framer-link-text-color": "rgb(0, 153, 255)",
							"--framer-link-text-decoration": "underline",
						}}
						text={t_JPInD9n}
						verticalAlignment={"top"}
						withExternalLayout={true}
					>
						<React.Fragment>
							<motion.p
								className={"framer-styles-preset-1ok24qa"}
								data-styles-preset={"Le_xC7TsI"}
								style={{
									"--framer-text-color":
										"var(--extracted-r6o4lv, var(--token-949a3add-eac1-4ce7-abe1-88da755f4b37, rgba(0, 0, 0, 0.5)))",
								}}
							>
								{"Description"}
							</motion.p>
						</React.Fragment>
					</RichText>
				</motion.div>
			</Transition>
		</LayoutGroup>
	);
});
var css3 = [
	'.framer-05RVk[data-border="true"]::after, .framer-05RVk [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; pointer-events: none; }',
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-05RVk.framer-kfw21v, .framer-05RVk .framer-kfw21v { display: block; }",
	".framer-05RVk.framer-mbvyor { align-content: center; align-items: center; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 8px; height: min-content; justify-content: flex-start; overflow: hidden; padding: 16px 16px 16px 16px; position: relative; width: 1200px; will-change: var(--framer-will-change-override, transform); }",
	".framer-05RVk .framer-6ot67p, .framer-05RVk .framer-1h35uap { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
	"@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-05RVk.framer-mbvyor { gap: 0px; } .framer-05RVk.framer-mbvyor > * { margin: 0px; margin-bottom: calc(8px / 2); margin-top: calc(8px / 2); } .framer-05RVk.framer-mbvyor > :first-child { margin-top: 0px; } .framer-05RVk.framer-mbvyor > :last-child { margin-bottom: 0px; } }",
	...css,
	...css2,
];
var FrameroXB2ggp1H = withCSS(Component, css3, "framer-05RVk");
var stdin_default = FrameroXB2ggp1H;
FrameroXB2ggp1H.displayName = "Card";
FrameroXB2ggp1H.defaultProps = {
	height: 91,
	width: 1200,
};
addPropertyControls(FrameroXB2ggp1H, {
	bvABklfQi: {
		defaultValue: "Title",
		displayTextArea: false,
		title: "Title",
		type: ControlType.String,
	},
	t_JPInD9n: {
		defaultValue: "Description",
		displayTextArea: true,
		title: "Description",
		type: ControlType.String,
	},
});
addFonts(FrameroXB2ggp1H, [...fonts, ...fonts2]);

// virtual:card
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"1763929c89cf4969ad190da187fc25ea516fa82b7cf163cf1161896117bee1d5"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders CardFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"1763929c89cf4969ad190da187fc25ea516fa82b7cf163cf1161896117bee1d5"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var card_default = ComponentWithRoot;
export { card_default as default };
