// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 1763929c89cf4969 "Patrick McKowen", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Default' | 'Mobile' | 'Large' | 'Large Hover' // Variant
 * title?: string // Title
 * description?: string // Description
 * image?: {src: string, srcSet?: string, alt?: string} // Image
 * link?: string // Link
}} Props

 */
import { className, css, fonts } from "./chunks/chunk-RRAHJCFQ.js";
import { withSlideUpOnHover } from "./chunks/chunk-VSMRQKYW.js";
import { routes } from "./chunks/chunk-IRNZKG45.js";

// virtual:case-study-card
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/8d6wN2SDsrjWMeAzWavE/Q7pisZD9fXOwQnl35Fdz/DdmKe7fcT.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	Image,
	Link,
	RichText,
	SVG,
	useActiveVariantCallback,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
var MotionAWithSlideUpOnHover = withSlideUpOnHover(motion.a);
var enabledGestures = {
	dxepszk8h: {
		hover: true,
	},
};
var cycleOrder = ["dxepszk8h", "sgAdZPNpi", "va3ugk0SI", "qmxCHXkK7"];
var serializationHash = "framer-TWpLq";
var variantClassNames = {
	dxepszk8h: "framer-v-1cb0hdp",
	qmxCHXkK7: "framer-v-1dbxl4u",
	sgAdZPNpi: "framer-v-19c7tc4",
	va3ugk0SI: "framer-v-160rici",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants === null || variants === void 0
		? void 0
		: variants.forEach(
				(variant) =>
					variant && Object.assign(nextOverrides, overrides[variant]),
			);
	return nextOverrides;
}
var transition1 = {
	damping: 60,
	delay: 0,
	mass: 1,
	stiffness: 500,
	type: "spring",
};
var transformTemplate1 = (_, t) => `translateY(-50%) ${t}`;
var toResponsiveImage = (value) => {
	if (
		typeof value === "object" &&
		value !== null &&
		typeof value.src === "string"
	) {
		return value;
	}
	return typeof value === "string"
		? {
				src: value,
			}
		: void 0;
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition =
		value !== null && value !== void 0 ? value : config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion(React.Fragment);
var humanReadableVariantMap = {
	"Large Hover": "qmxCHXkK7",
	Default: "dxepszk8h",
	Large: "va3ugk0SI",
	Mobile: "sgAdZPNpi",
};
var getProps = ({
	description,
	height,
	id,
	image,
	link,
	title,
	width,
	...props
}) => {
	var _ref, _ref1, _ref2, _humanReadableVariantMap_props_variant, _ref3;
	return {
		...props,
		FlgPlKh9o: link !== null && link !== void 0 ? link : props.FlgPlKh9o,
		Hqz1nZvRF:
			(_ref = title !== null && title !== void 0 ? title : props.Hqz1nZvRF) !==
				null && _ref !== void 0
				? _ref
				: "Cameo Licensing",
		PFUUW7APZ:
			(_ref1 = image !== null && image !== void 0 ? image : props.PFUUW7APZ) !==
				null && _ref1 !== void 0
				? _ref1
				: {
						src: "https://framerusercontent.com/images/QdBK4VJp9eM2GBYRPT7BOWM0ZQ.png?scale-down-to=1024",
						srcSet:
							"https://framerusercontent.com/images/QdBK4VJp9eM2GBYRPT7BOWM0ZQ.png?scale-down-to=512 512w,https://framerusercontent.com/images/QdBK4VJp9eM2GBYRPT7BOWM0ZQ.png?scale-down-to=1024 1024w,https://framerusercontent.com/images/QdBK4VJp9eM2GBYRPT7BOWM0ZQ.png?scale-down-to=2048 2048w,https://framerusercontent.com/images/QdBK4VJp9eM2GBYRPT7BOWM0ZQ.png 2880w",
					},
		PnznjCIhq:
			(_ref2 =
				description !== null && description !== void 0
					? description
					: props.PnznjCIhq) !== null && _ref2 !== void 0
				? _ref2
				: "The first steps of a new product.",
		variant:
			(_ref3 =
				(_humanReadableVariantMap_props_variant =
					humanReadableVariantMap[props.variant]) !== null &&
				_humanReadableVariantMap_props_variant !== void 0
					? _humanReadableVariantMap_props_variant
					: props.variant) !== null && _ref3 !== void 0
				? _ref3
				: "dxepszk8h",
	};
};
var createLayoutDependency = (props, variants) =>
	variants.join("-") + props.layoutDependency;
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const { activeLocale, setLocale } = useLocaleInfo();
	const {
		style,
		className: className2,
		layoutId,
		variant,
		Hqz1nZvRF,
		PnznjCIhq,
		PFUUW7APZ,
		FlgPlKh9o,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		gestureVariant,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "dxepszk8h",
		enabledGestures,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const { activeVariantCallback, delay } =
		useActiveVariantCallback(baseVariant);
	const onMouseLeavelm9gxe = activeVariantCallback(async (...args) => {
		setVariant("dxepszk8h");
	});
	const onMouseEnter1qfyv2v = activeVariantCallback(async (...args) => {
		setVariant("qmxCHXkK7");
	});
	const onMouseLeavegbyzgv = activeVariantCallback(async (...args) => {
		setVariant("va3ugk0SI");
	});
	const ref1 = React.useRef(null);
	const defaultLayoutId = React.useId();
	const sharedStyleClassNames = [className];
	const componentViewport = useComponentViewport();
	return (
		<LayoutGroup
			id={layoutId !== null && layoutId !== void 0 ? layoutId : defaultLayoutId}
		>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<Link href={FlgPlKh9o} openInNewTab={false}>
						<MotionAWithSlideUpOnHover
							{...restProps}
							className={`${cx(serializationHash, ...sharedStyleClassNames, "framer-1cb0hdp", className2, classNames)} framer-tk5fw6`}
							data-border={true}
							data-framer-name={"Default"}
							data-highlight={true}
							layoutDependency={layoutDependency}
							layoutId={"dxepszk8h"}
							onHoverEnd={() =>
								setGestureState({
									isHovered: false,
								})
							}
							onHoverStart={() =>
								setGestureState({
									isHovered: true,
								})
							}
							onMouseLeave={onMouseLeavelm9gxe}
							onTap={() =>
								setGestureState({
									isPressed: false,
								})
							}
							onTapCancel={() =>
								setGestureState({
									isPressed: false,
								})
							}
							onTapStart={() =>
								setGestureState({
									isPressed: true,
								})
							}
							ref={ref !== null && ref !== void 0 ? ref : ref1}
							style={{
								"--border-bottom-width": "2px",
								"--border-color": "rgba(255, 255, 255, 0.35)",
								"--border-left-width": "2px",
								"--border-right-width": "2px",
								"--border-style": "solid",
								"--border-top-width": "2px",
								backdropFilter: "blur(10px)",
								background:
									"linear-gradient(180deg, rgba(255, 255, 255, 0.25) 0%, rgba(247, 247, 247, 0.8) 100%)",
								borderBottomLeftRadius: 24,
								borderBottomRightRadius: 24,
								borderTopLeftRadius: 24,
								borderTopRightRadius: 24,
								WebkitBackdropFilter: "blur(10px)",
								...style,
							}}
							variants={{
								"dxepszk8h-hover": {
									"--border-color": "rgba(255, 255, 255, 0.65)",
									background:
										"linear-gradient(180deg, rgba(255, 255, 255, 0.5) 0%, rgb(247, 247, 247) 100%)",
								},
								sgAdZPNpi: {
									backdropFilter: "blur(8px)",
									background:
										"linear-gradient(180deg, rgba(255, 255, 255, 0.25) 0%, rgb(247, 247, 247) 100%)",
									borderBottomLeftRadius: 16,
									borderBottomRightRadius: 16,
									borderTopLeftRadius: 16,
									borderTopRightRadius: 16,
									WebkitBackdropFilter: "blur(8px)",
								},
							}}
							{...addPropertyOverrides(
								{
									"dxepszk8h-hover": {
										"data-framer-name": void 0,
									},
									qmxCHXkK7: {
										"data-framer-name": "Large Hover",
										onMouseLeave: onMouseLeavegbyzgv,
									},
									sgAdZPNpi: {
										"data-framer-name": "Mobile",
										"data-highlight": void 0,
										onMouseLeave: void 0,
									},
									va3ugk0SI: {
										"data-framer-name": "Large",
										onMouseEnter: onMouseEnter1qfyv2v,
									},
								},
								baseVariant,
								gestureVariant,
							)}
						>
							<motion.div
								className={"framer-c7rwr8"}
								data-framer-name={"Content"}
								layoutDependency={layoutDependency}
								layoutId={"E3DFHuBKH"}
							>
								<motion.div
									className={"framer-khfi1u"}
									data-framer-name={"Text"}
									layoutDependency={layoutDependency}
									layoutId={"g5IfevzyK"}
								>
									<RichText
										__fromCanvasComponent={true}
										className={"framer-ng8lly"}
										data-framer-name={"Cameo Licensing"}
										fonts={["CUSTOM;Geist Medium"]}
										layoutDependency={layoutDependency}
										layoutId={"FVJl_f979"}
										style={{
											"--extracted-a0htzi":
												"var(--token-38e34800-80da-44a7-911f-74b9aae91a0c, rgba(0, 0, 0, 0.9))",
											"--framer-paragraph-spacing": "0px",
										}}
										text={Hqz1nZvRF}
										verticalAlignment={"top"}
										withExternalLayout={true}
										{...addPropertyOverrides(
											{
												qmxCHXkK7: {
													children: (
														<React.Fragment>
															<motion.h3
																style={{
																	"--font-selector":
																		"Q1VTVE9NO0dlaXN0IE1lZGl1bQ==",
																	"--framer-font-family":
																		'"Geist Medium", "Geist Medium Placeholder", sans-serif',
																	"--framer-font-size": "28px",
																	"--framer-letter-spacing": "-0.02em",
																	"--framer-line-height": "1.5em",
																	"--framer-text-color":
																		"var(--extracted-a0htzi, var(--token-38e34800-80da-44a7-911f-74b9aae91a0c, rgba(0, 0, 0, 0.9)))",
																}}
															>
																{"Cameo Licensing"}
															</motion.h3>
														</React.Fragment>
													),
												},
												sgAdZPNpi: {
													children: (
														<React.Fragment>
															<motion.h3
																className={"framer-styles-preset-gdhw34"}
																data-styles-preset={"im8OSauR5"}
															>
																{"Cameo Licensing"}
															</motion.h3>
														</React.Fragment>
													),
													fonts: void 0,
												},
												va3ugk0SI: {
													children: (
														<React.Fragment>
															<motion.h3
																style={{
																	"--font-selector":
																		"Q1VTVE9NO0dlaXN0IE1lZGl1bQ==",
																	"--framer-font-family":
																		'"Geist Medium", "Geist Medium Placeholder", sans-serif',
																	"--framer-font-size": "28px",
																	"--framer-letter-spacing": "-0.02em",
																	"--framer-line-height": "1.5em",
																	"--framer-text-color":
																		"var(--extracted-a0htzi, var(--token-38e34800-80da-44a7-911f-74b9aae91a0c, rgba(0, 0, 0, 0.9)))",
																}}
															>
																{"Cameo Licensing"}
															</motion.h3>
														</React.Fragment>
													),
												},
											},
											baseVariant,
											gestureVariant,
										)}
									>
										<React.Fragment>
											<motion.h3
												style={{
													"--font-selector": "Q1VTVE9NO0dlaXN0IE1lZGl1bQ==",
													"--framer-font-family":
														'"Geist Medium", "Geist Medium Placeholder", sans-serif',
													"--framer-font-size": "22px",
													"--framer-letter-spacing": "-0.02em",
													"--framer-line-height": "1.5em",
													"--framer-text-color":
														"var(--extracted-a0htzi, var(--token-38e34800-80da-44a7-911f-74b9aae91a0c, rgba(0, 0, 0, 0.9)))",
												}}
											>
												{"Cameo Licensing"}
											</motion.h3>
										</React.Fragment>
									</RichText>
									<RichText
										__fromCanvasComponent={true}
										className={"framer-lo8gd"}
										data-framer-name={
											"Automating licensing agreements between businesses and celebrity content creators."
										}
										fonts={["CUSTOM;Geist Regular"]}
										layoutDependency={layoutDependency}
										layoutId={"cVwRjBSRh"}
										style={{
											"--extracted-r6o4lv":
												"var(--token-c3ec4201-05df-4ec8-93fe-fe8f0231d7fb, rgba(0, 0, 0, 0.75))",
											"--framer-paragraph-spacing": "0px",
										}}
										text={PnznjCIhq}
										verticalAlignment={"top"}
										withExternalLayout={true}
										{...addPropertyOverrides(
											{
												qmxCHXkK7: {
													children: (
														<React.Fragment>
															<motion.p
																style={{
																	"--font-selector":
																		"Q1VTVE9NO0dlaXN0IFJlZ3VsYXI=",
																	"--framer-font-family":
																		'"Geist Regular", "Geist Regular Placeholder", sans-serif',
																	"--framer-font-size": "20px",
																	"--framer-line-height": "1.5em",
																	"--framer-text-color":
																		"var(--extracted-r6o4lv, var(--token-c3ec4201-05df-4ec8-93fe-fe8f0231d7fb, rgba(0, 0, 0, 0.75)))",
																}}
															>
																{"The first steps of a new product."}
															</motion.p>
														</React.Fragment>
													),
												},
												va3ugk0SI: {
													children: (
														<React.Fragment>
															<motion.p
																style={{
																	"--font-selector":
																		"Q1VTVE9NO0dlaXN0IFJlZ3VsYXI=",
																	"--framer-font-family":
																		'"Geist Regular", "Geist Regular Placeholder", sans-serif',
																	"--framer-font-size": "20px",
																	"--framer-line-height": "1.5em",
																	"--framer-text-color":
																		"var(--extracted-r6o4lv, var(--token-c3ec4201-05df-4ec8-93fe-fe8f0231d7fb, rgba(0, 0, 0, 0.75)))",
																}}
															>
																{"The first steps of a new product."}
															</motion.p>
														</React.Fragment>
													),
												},
											},
											baseVariant,
											gestureVariant,
										)}
									>
										<React.Fragment>
											<motion.p
												style={{
													"--font-selector": "Q1VTVE9NO0dlaXN0IFJlZ3VsYXI=",
													"--framer-font-family":
														'"Geist Regular", "Geist Regular Placeholder", sans-serif',
													"--framer-line-height": "1.5em",
													"--framer-text-color":
														"var(--extracted-r6o4lv, var(--token-c3ec4201-05df-4ec8-93fe-fe8f0231d7fb, rgba(0, 0, 0, 0.75)))",
												}}
											>
												{
													"Automating licensing agreements between businesses and celebrity content creators."
												}
											</motion.p>
										</React.Fragment>
									</RichText>
								</motion.div>
								<motion.div
									className={"framer-1a7p2uo"}
									data-framer-name={"Button Container"}
									layoutDependency={layoutDependency}
									layoutId={"RLtkqN7l1"}
								>
									<motion.div
										className={"framer-nrfojf"}
										data-framer-name={"Button"}
										layoutDependency={layoutDependency}
										layoutId={"lmRHHJgLp"}
										style={{
											backdropFilter: "none",
											backgroundColor:
												"var(--token-68366ab7-03aa-46f4-96ae-993f4367e005, rgb(247, 247, 247))",
											borderBottomLeftRadius: 100,
											borderBottomRightRadius: 100,
											borderTopLeftRadius: 100,
											borderTopRightRadius: 100,
											opacity: 0,
											WebkitBackdropFilter: "none",
										}}
										variants={{
											"dxepszk8h-hover": {
												backgroundColor:
													"var(--token-0646263c-1e98-47cd-9020-0c1d771c1075, rgb(255, 255, 255))",
												opacity: 1,
											},
											qmxCHXkK7: {
												opacity: 1,
											},
											sgAdZPNpi: {
												backdropFilter: "blur(40px)",
												backgroundColor: "rgba(255, 255, 255, 0.5)",
												opacity: 1,
												WebkitBackdropFilter: "blur(40px)",
											},
										}}
										{...addPropertyOverrides(
											{
												"dxepszk8h-hover": {
													transformTemplate: transformTemplate1,
												},
											},
											baseVariant,
											gestureVariant,
										)}
									>
										<SVG
											className={"framer-1e3clrf"}
											data-framer-name={"graphic"}
											fill={"black"}
											intrinsicHeight={14}
											intrinsicWidth={18}
											layoutDependency={layoutDependency}
											layoutId={"egKb3Xhy8"}
											svg={
												'<svg width="18" height="14" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M17.063 6.654a.796.796 0 0 1-.264.59l-5.845 5.826a.803.803 0 0 1-.571.246.74.74 0 0 1-.545-.22.711.711 0 0 1-.22-.536c0-.105.018-.205.053-.298a.67.67 0 0 1 .158-.255l1.969-2.004 3.49-3.173.175.43-2.83.177H1.515a.762.762 0 0 1-.563-.22.779.779 0 0 1-.21-.563.78.78 0 0 1 .21-.562.762.762 0 0 1 .563-.22h11.118l2.83.176-.176.44-3.49-3.182L9.83 1.302a.683.683 0 0 1-.158-.246.918.918 0 0 1-.053-.308.71.71 0 0 1 .22-.536.74.74 0 0 1 .545-.22c.105 0 .205.02.299.062a.9.9 0 0 1 .29.202l5.827 5.81c.176.17.264.366.264.588Z" fill="#000" fill-opacity=".9" style="fill:#000;fill-opacity:.9"/></svg>'
											}
											withExternalLayout={true}
										/>
									</motion.div>
								</motion.div>
							</motion.div>
							<motion.div
								background={{
									alt: "",
									fit: "fill",
								}}
								className={"framer-qsw6vk"}
								data-framer-name={"Image Container"}
								layoutDependency={layoutDependency}
								layoutId={"mnBUutkJl"}
							>
								<Image
									background={{
										alt: "",
										fit: "fill",
										intrinsicHeight: 1440,
										intrinsicWidth: 1920,
										pixelHeight: 1440,
										pixelWidth: 1920,
										sizes:
											(componentViewport === null ||
											componentViewport === void 0
												? void 0
												: componentViewport.width) || "100vw",
										...toResponsiveImage(PFUUW7APZ),
									}}
									className={"framer-i3eev6"}
									data-framer-name={"Image"}
									layoutDependency={layoutDependency}
									layoutId={"nphJKuKj9"}
								/>
							</motion.div>
						</MotionAWithSlideUpOnHover>
					</Link>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css2 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-TWpLq.framer-tk5fw6, .framer-TWpLq .framer-tk5fw6 { display: block; }",
	".framer-TWpLq.framer-1cb0hdp { align-content: flex-start; align-items: flex-start; cursor: pointer; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: flex-start; overflow: hidden; padding: 0px 0px 0px 0px; position: relative; text-decoration: none; width: 520px; will-change: var(--framer-will-change-override, transform); }",
	".framer-TWpLq .framer-c7rwr8 { align-content: flex-end; align-items: flex-end; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 8px; height: min-content; justify-content: flex-start; overflow: visible; padding: 32px 32px 32px 32px; position: relative; width: 100%; }",
	".framer-TWpLq .framer-khfi1u { align-content: flex-start; align-items: flex-start; display: flex; flex: 1 0 0px; flex-direction: column; flex-wrap: nowrap; gap: 2px; height: min-content; justify-content: flex-start; overflow: hidden; padding: 0px 0px 0px 0px; position: relative; width: 1px; }",
	".framer-TWpLq .framer-ng8lly, .framer-TWpLq .framer-lo8gd { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
	".framer-TWpLq .framer-1a7p2uo { aspect-ratio: 1 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 44px); overflow: visible; position: absolute; right: 24px; top: 24px; width: 44px; z-index: 1; }",
	".framer-TWpLq .framer-nrfojf { align-content: center; align-items: center; aspect-ratio: 1 / 1; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: var(--framer-aspect-ratio-supported, 1px); justify-content: center; left: -1px; overflow: hidden; padding: 0px 0px 0px 0px; position: absolute; top: 24px; width: 1px; will-change: var(--framer-will-change-override, transform); }",
	".framer-TWpLq .framer-1e3clrf { aspect-ratio: 1.2857142857142858 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 14px); position: relative; width: 18px; }",
	".framer-TWpLq .framer-qsw6vk { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: auto; justify-content: center; overflow: hidden; padding: 0px 0px 0px 0px; position: relative; width: 100%; }",
	".framer-TWpLq .framer-i3eev6 { aspect-ratio: 1.3333333333333333 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 390px); overflow: hidden; position: relative; width: 100%; }",
	"@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-TWpLq.framer-1cb0hdp, .framer-TWpLq .framer-c7rwr8, .framer-TWpLq .framer-khfi1u, .framer-TWpLq .framer-nrfojf, .framer-TWpLq .framer-qsw6vk { gap: 0px; } .framer-TWpLq.framer-1cb0hdp > * { margin: 0px; margin-bottom: calc(0px / 2); margin-top: calc(0px / 2); } .framer-TWpLq.framer-1cb0hdp > :first-child, .framer-TWpLq .framer-khfi1u > :first-child, .framer-TWpLq .framer-nrfojf > :first-child { margin-top: 0px; } .framer-TWpLq.framer-1cb0hdp > :last-child, .framer-TWpLq .framer-khfi1u > :last-child, .framer-TWpLq .framer-nrfojf > :last-child { margin-bottom: 0px; } .framer-TWpLq .framer-c7rwr8 > * { margin: 0px; margin-left: calc(8px / 2); margin-right: calc(8px / 2); } .framer-TWpLq .framer-c7rwr8 > :first-child, .framer-TWpLq .framer-qsw6vk > :first-child { margin-left: 0px; } .framer-TWpLq .framer-c7rwr8 > :last-child, .framer-TWpLq .framer-qsw6vk > :last-child { margin-right: 0px; } .framer-TWpLq .framer-khfi1u > * { margin: 0px; margin-bottom: calc(2px / 2); margin-top: calc(2px / 2); } .framer-TWpLq .framer-nrfojf > * { margin: 0px; margin-bottom: calc(10px / 2); margin-top: calc(10px / 2); } .framer-TWpLq .framer-qsw6vk > * { margin: 0px; margin-left: calc(10px / 2); margin-right: calc(10px / 2); } }",
	".framer-TWpLq.framer-v-19c7tc4.framer-1cb0hdp, .framer-TWpLq.framer-v-160rici.framer-1cb0hdp, .framer-TWpLq.framer-v-1dbxl4u.framer-1cb0hdp { cursor: unset; }",
	".framer-TWpLq.framer-v-19c7tc4 .framer-c7rwr8 { order: 0; padding: 20px 20px 20px 20px; }",
	".framer-TWpLq.framer-v-19c7tc4 .framer-khfi1u { gap: 4px; }",
	".framer-TWpLq.framer-v-19c7tc4 .framer-1a7p2uo { align-content: center; align-items: center; aspect-ratio: unset; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; padding: 0px 0px 0px 0px; right: 20px; top: 20px; width: min-content; }",
	".framer-TWpLq.framer-v-19c7tc4 .framer-nrfojf { height: var(--framer-aspect-ratio-supported, 36px); left: unset; position: relative; top: unset; width: 36px; }",
	".framer-TWpLq.framer-v-19c7tc4 .framer-qsw6vk { order: 1; }",
	"@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-TWpLq.framer-v-19c7tc4 .framer-khfi1u, .framer-TWpLq.framer-v-19c7tc4 .framer-1a7p2uo { gap: 0px; } .framer-TWpLq.framer-v-19c7tc4 .framer-khfi1u > * { margin: 0px; margin-bottom: calc(4px / 2); margin-top: calc(4px / 2); } .framer-TWpLq.framer-v-19c7tc4 .framer-khfi1u > :first-child { margin-top: 0px; } .framer-TWpLq.framer-v-19c7tc4 .framer-khfi1u > :last-child { margin-bottom: 0px; } .framer-TWpLq.framer-v-19c7tc4 .framer-1a7p2uo > * { margin: 0px; margin-left: calc(10px / 2); margin-right: calc(10px / 2); } .framer-TWpLq.framer-v-19c7tc4 .framer-1a7p2uo > :first-child { margin-left: 0px; } .framer-TWpLq.framer-v-19c7tc4 .framer-1a7p2uo > :last-child { margin-right: 0px; } }",
	".framer-TWpLq.framer-v-160rici .framer-1a7p2uo { top: 32px; }",
	".framer-TWpLq.framer-v-1dbxl4u .framer-1a7p2uo { right: 32px; top: 32px; }",
	".framer-TWpLq.framer-v-1dbxl4u .framer-nrfojf { height: var(--framer-aspect-ratio-supported, 44px); left: 0px; top: 0px; width: 44px; }",
	".framer-TWpLq.framer-v-1cb0hdp.hover .framer-c7rwr8 { align-content: flex-start; align-items: flex-start; }",
	".framer-TWpLq.framer-v-1cb0hdp.hover .framer-nrfojf { height: var(--framer-aspect-ratio-supported, 44px); left: 0px; top: 50%; width: 44px; }",
	...css,
	'.framer-TWpLq[data-border="true"]::after, .framer-TWpLq [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; pointer-events: none; }',
];
var FramerDdmKe7fcT = withCSS(Component, css2, "framer-TWpLq");
var stdin_default = FramerDdmKe7fcT;
FramerDdmKe7fcT.displayName = "Case Study Card";
FramerDdmKe7fcT.defaultProps = {
	height: 513,
	width: 520,
};
addPropertyControls(FramerDdmKe7fcT, {
	variant: {
		options: ["dxepszk8h", "sgAdZPNpi", "va3ugk0SI", "qmxCHXkK7"],
		optionTitles: ["Default", "Mobile", "Large", "Large Hover"],
		title: "Variant",
		type: ControlType.Enum,
	},
	Hqz1nZvRF: {
		defaultValue: "Cameo Licensing",
		displayTextArea: false,
		title: "Title",
		type: ControlType.String,
	},
	PnznjCIhq: {
		defaultValue: "The first steps of a new product.",
		displayTextArea: true,
		title: "Description",
		type: ControlType.String,
	},
	PFUUW7APZ: {
		__defaultAssetReference:
			"data:framer/asset-reference,QdBK4VJp9eM2GBYRPT7BOWM0ZQ.png?originalFilename=image.png&preferredSize=auto",
		title: "Image",
		type: ControlType.ResponsiveImage,
	},
	FlgPlKh9o: {
		title: "Link",
		type: ControlType.Link,
	},
});
addFonts(FramerDdmKe7fcT, [
	{
		family: "Geist Medium",
		source: "custom",
		url: "https://framerusercontent.com/assets/dNqH0c4qjo3RGmYZnJknwKtT0.woff2",
	},
	{
		family: "Geist Regular",
		source: "custom",
		url: "https://framerusercontent.com/assets/fmgcvoo7Pvi75XN7wkBOp5g4i4s.woff2",
	},
	...fonts,
]);

// virtual:case-study-card
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"1763929c89cf4969ad190da187fc25ea516fa82b7cf163cf1161896117bee1d5"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders CaseStudyCardFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"1763929c89cf4969ad190da187fc25ea516fa82b7cf163cf1161896117bee1d5"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var case_study_card_default = ComponentWithRoot;
export { case_study_card_default as default };
