// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 1763929c89cf4969 "Patrick McKowen", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Dark Mode' | 'M Dark Mode' | 'Light Mode' | 'M Light Mode' // Variant
}} Props

 */
import { routes } from "./chunks/chunk-IRNZKG45.js";

// virtual:cs-bullet
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/K31Fm2hzdh8HBtYRFmkz/jqKFQZtAvw2qmdK2OFrl/Tl81w42ed.js
import { jsx as _jsx } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
var cycleOrder = ["u45ZYtwFr", "KCx9ZmQcn", "BfCNPwuKs", "RAufyy5su"];
var serializationHash = "framer-Da5PE";
var variantClassNames = {
	BfCNPwuKs: "framer-v-8fim8x",
	KCx9ZmQcn: "framer-v-zyni1s",
	RAufyy5su: "framer-v-mwpfnu",
	u45ZYtwFr: "framer-v-yubc4n",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants === null || variants === void 0
		? void 0
		: variants.forEach(
				(variant) =>
					variant && Object.assign(nextOverrides, overrides[variant]),
			);
	return nextOverrides;
}
var transition1 = {
	damping: 60,
	delay: 0,
	mass: 1,
	stiffness: 500,
	type: "spring",
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition =
		value !== null && value !== void 0 ? value : config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion(React.Fragment);
var humanReadableVariantMap = {
	"Dark Mode": "u45ZYtwFr",
	"Light Mode": "BfCNPwuKs",
	"M Dark Mode": "KCx9ZmQcn",
	"M Light Mode": "RAufyy5su",
};
var getProps = ({ height, id, width, ...props }) => {
	var _humanReadableVariantMap_props_variant, _ref;
	return {
		...props,
		variant:
			(_ref =
				(_humanReadableVariantMap_props_variant =
					humanReadableVariantMap[props.variant]) !== null &&
				_humanReadableVariantMap_props_variant !== void 0
					? _humanReadableVariantMap_props_variant
					: props.variant) !== null && _ref !== void 0
				? _ref
				: "u45ZYtwFr",
	};
};
var createLayoutDependency = (props, variants) =>
	variants.join("-") + props.layoutDependency;
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const { activeLocale, setLocale } = useLocaleInfo();
	const { style, className, layoutId, variant, ...restProps } = getProps(props);
	const {
		baseVariant,
		classNames,
		gestureVariant,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "u45ZYtwFr",
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const ref1 = React.useRef(null);
	const defaultLayoutId = React.useId();
	const sharedStyleClassNames = [];
	const componentViewport = useComponentViewport();
	return (
		<LayoutGroup
			id={layoutId !== null && layoutId !== void 0 ? layoutId : defaultLayoutId}
		>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.div
						{...restProps}
						className={cx(
							serializationHash,
							...sharedStyleClassNames,
							"framer-yubc4n",
							className,
							classNames,
						)}
						data-framer-name={"Dark Mode"}
						layoutDependency={layoutDependency}
						layoutId={"u45ZYtwFr"}
						onHoverEnd={() =>
							setGestureState({
								isHovered: false,
							})
						}
						onHoverStart={() =>
							setGestureState({
								isHovered: true,
							})
						}
						onTap={() =>
							setGestureState({
								isPressed: false,
							})
						}
						onTapCancel={() =>
							setGestureState({
								isPressed: false,
							})
						}
						onTapStart={() =>
							setGestureState({
								isPressed: true,
							})
						}
						ref={ref !== null && ref !== void 0 ? ref : ref1}
						style={{
							borderBottomLeftRadius: 100,
							borderBottomRightRadius: 100,
							borderTopLeftRadius: 100,
							borderTopRightRadius: 100,
							...style,
						}}
						variants={{
							KCx9ZmQcn: {
								borderBottomLeftRadius: 0,
								borderBottomRightRadius: 0,
								borderTopLeftRadius: 0,
								borderTopRightRadius: 0,
							},
							RAufyy5su: {
								borderBottomLeftRadius: 0,
								borderBottomRightRadius: 0,
								borderTopLeftRadius: 0,
								borderTopRightRadius: 0,
							},
						}}
						{...addPropertyOverrides(
							{
								BfCNPwuKs: {
									"data-framer-name": "Light Mode",
								},
								KCx9ZmQcn: {
									"data-framer-name": "M Dark Mode",
								},
								RAufyy5su: {
									"data-framer-name": "M Light Mode",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion.div
							className={"framer-2do45h"}
							data-border={true}
							data-framer-name={"Bullet"}
							layoutDependency={layoutDependency}
							layoutId={"bUlM7hsuz"}
							style={{
								"--border-bottom-width": "1px",
								"--border-color":
									"var(--token-5dff30ad-54df-442f-b02e-27fac6b1c11f, rgba(255, 255, 255, 0.5))",
								"--border-left-width": "1px",
								"--border-right-width": "1px",
								"--border-style": "solid",
								"--border-top-width": "1px",
								borderBottomLeftRadius: 100,
								borderBottomRightRadius: 100,
								borderTopLeftRadius: 100,
								borderTopRightRadius: 100,
							}}
							variants={{
								BfCNPwuKs: {
									"--border-color": "rgba(0, 0, 0, 0.65)",
								},
								RAufyy5su: {
									"--border-color": "rgba(0, 0, 0, 0.5)",
								},
							}}
						/>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-Da5PE.framer-10w2yon, .framer-Da5PE .framer-10w2yon { display: block; }",
	".framer-Da5PE.framer-yubc4n { align-content: center; align-items: center; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: 10px; justify-content: flex-start; overflow: hidden; padding: 0px; position: relative; width: 10px; will-change: var(--framer-will-change-override, transform); }",
	".framer-Da5PE .framer-2do45h { aspect-ratio: 1 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 10px); overflow: hidden; position: relative; width: 10px; will-change: var(--framer-will-change-override, transform); }",
	"@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-Da5PE.framer-yubc4n { gap: 0px; } .framer-Da5PE.framer-yubc4n > * { margin: 0px; margin-left: calc(10px / 2); margin-right: calc(10px / 2); } .framer-Da5PE.framer-yubc4n > :first-child { margin-left: 0px; } .framer-Da5PE.framer-yubc4n > :last-child { margin-right: 0px; } }",
	".framer-Da5PE.framer-v-zyni1s.framer-yubc4n, .framer-Da5PE.framer-v-mwpfnu.framer-yubc4n { height: auto; padding: 8px 0px 0px 0px; width: auto; }",
	".framer-Da5PE.framer-v-zyni1s .framer-2do45h, .framer-Da5PE.framer-v-mwpfnu .framer-2do45h { height: var(--framer-aspect-ratio-supported, 8px); width: 8px; }",
	".framer-Da5PE.framer-v-8fim8x.framer-yubc4n { aspect-ratio: 1 / 1; height: var(--framer-aspect-ratio-supported, 10px); }",
	'.framer-Da5PE[data-border="true"]::after, .framer-Da5PE [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; pointer-events: none; }',
];
var FramerTl81w42ed = withCSS(Component, css, "framer-Da5PE");
var stdin_default = FramerTl81w42ed;
FramerTl81w42ed.displayName = "CS Bullet";
FramerTl81w42ed.defaultProps = {
	height: 10,
	width: 10,
};
addPropertyControls(FramerTl81w42ed, {
	variant: {
		options: ["u45ZYtwFr", "KCx9ZmQcn", "BfCNPwuKs", "RAufyy5su"],
		optionTitles: ["Dark Mode", "M Dark Mode", "Light Mode", "M Light Mode"],
		title: "Variant",
		type: ControlType.Enum,
	},
});
addFonts(
	FramerTl81w42ed,
	[
		{
			explicitInter: true,
			fonts: [],
		},
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:cs-bullet
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "KCx9ZmQcn",
	xl: "BfCNPwuKs",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"1763929c89cf4969ad190da187fc25ea516fa82b7cf163cf1161896117bee1d5"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders CsBulletFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"1763929c89cf4969ad190da187fc25ea516fa82b7cf163cf1161896117bee1d5"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var cs_bullet_default = ComponentWithRoot;
export { cs_bullet_default as default };
