// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 1763929c89cf4969 "Patrick McKowen", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Dark Mode' | 'M Light Mode' | 'Light Mode' | 'M Dark Mode' // Variant
 * title?: string // Title
 * number?: string // Number
}} Props

 */
import { stdin_default } from "./chunks/chunk-7B6ZFXEJ.js";
import "./chunks/chunk-SNIB7V3T.js";
import "./chunks/chunk-T6M5HMBG.js";
import { routes } from "./chunks/chunk-IRNZKG45.js";

// virtual:cs-section-header
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/G7Wga7DYLrpdTRnSuvSH/QfMnF5BvuUVUPgrs9mY7/E6NwIheFv.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	getFonts,
	RichText,
	useConstant,
	useIsOnFramerCanvas,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";

// /:https://framerusercontent.com/modules/3ZAka0cax2pdFdQmzz4T/NUzoznxSviZXzpTSahvg/DqgyYQx9o.js
import { fontStore } from "unframer";
fontStore.loadFonts(["CUSTOM;Tiempos Headline Light"]);
var fonts = [
	{
		family: "Tiempos Headline Light",
		source: "custom",
		url: "https://framerusercontent.com/assets/US3zYftZiVXwDdufpPquGbnkU.woff",
	},
];
var css = [
	'.framer-h7yKg .framer-styles-preset-z84o0n:not(.rich-text-wrapper), .framer-h7yKg .framer-styles-preset-z84o0n.rich-text-wrapper h1 { --framer-font-family: "Tiempos Headline Light", "Tiempos Headline Light Placeholder", sans-serif; --framer-font-size: 96px; --framer-font-style: normal; --framer-font-weight: 400; --framer-letter-spacing: -1px; --framer-line-height: 1.25em; --framer-paragraph-spacing: 0px; --framer-text-alignment: start; --framer-text-color: var(--token-38e34800-80da-44a7-911f-74b9aae91a0c, rgba(0, 0, 0, 0.9)); --framer-text-decoration: none; --framer-text-transform: none; }',
	'@media (max-width: 1199px) and (min-width: 501px) { .framer-h7yKg .framer-styles-preset-z84o0n:not(.rich-text-wrapper), .framer-h7yKg .framer-styles-preset-z84o0n.rich-text-wrapper h1 { --framer-font-family: "Tiempos Headline Light", "Tiempos Headline Light Placeholder", sans-serif; --framer-font-size: 64px; --framer-font-style: normal; --framer-font-weight: 400; --framer-letter-spacing: -1px; --framer-line-height: 1.25em; --framer-paragraph-spacing: 0px; --framer-text-alignment: start; --framer-text-color: var(--token-38e34800-80da-44a7-911f-74b9aae91a0c, rgba(0, 0, 0, 0.9)); --framer-text-decoration: none; --framer-text-transform: none; } }',
	'@media (max-width: 500px) and (min-width: 0px) { .framer-h7yKg .framer-styles-preset-z84o0n:not(.rich-text-wrapper), .framer-h7yKg .framer-styles-preset-z84o0n.rich-text-wrapper h1 { --framer-font-family: "Tiempos Headline Light", "Tiempos Headline Light Placeholder", sans-serif; --framer-font-size: 44px; --framer-font-style: normal; --framer-font-weight: 400; --framer-letter-spacing: -1px; --framer-line-height: 1.25em; --framer-paragraph-spacing: 0px; --framer-text-alignment: start; --framer-text-color: var(--token-38e34800-80da-44a7-911f-74b9aae91a0c, rgba(0, 0, 0, 0.9)); --framer-text-decoration: none; --framer-text-transform: none; } }',
];
var className = "framer-h7yKg";

// /:https://framerusercontent.com/modules/QILvfPSMkoeCDz6zhDSe/UUFXpIQcd4D9lIfYf2kT/pUjbPuiTc.js
import { fontStore as fontStore2 } from "unframer";
fontStore2.loadFonts(["CUSTOM;Tiempos Headline Light"]);
var fonts2 = [
	{
		family: "Tiempos Headline Light",
		source: "custom",
		url: "https://framerusercontent.com/assets/US3zYftZiVXwDdufpPquGbnkU.woff",
	},
];
var css2 = [
	'.framer-N6iNp .framer-styles-preset-1bkecfj:not(.rich-text-wrapper), .framer-N6iNp .framer-styles-preset-1bkecfj.rich-text-wrapper h2 { --framer-font-family: "Tiempos Headline Light", "Tiempos Headline Light Placeholder", sans-serif; --framer-font-size: 64px; --framer-font-style: normal; --framer-font-weight: 400; --framer-letter-spacing: 0em; --framer-line-height: 1.25em; --framer-paragraph-spacing: 0px; --framer-text-alignment: start; --framer-text-color: var(--token-38e34800-80da-44a7-911f-74b9aae91a0c, rgba(0, 0, 0, 0.9)); --framer-text-decoration: none; --framer-text-transform: none; }',
	'@media (max-width: 1199px) and (min-width: 501px) { .framer-N6iNp .framer-styles-preset-1bkecfj:not(.rich-text-wrapper), .framer-N6iNp .framer-styles-preset-1bkecfj.rich-text-wrapper h2 { --framer-font-family: "Tiempos Headline Light", "Tiempos Headline Light Placeholder", sans-serif; --framer-font-size: 48px; --framer-font-style: normal; --framer-font-weight: 400; --framer-letter-spacing: 0em; --framer-line-height: 1.25em; --framer-paragraph-spacing: 0px; --framer-text-alignment: start; --framer-text-color: var(--token-38e34800-80da-44a7-911f-74b9aae91a0c, rgba(0, 0, 0, 0.9)); --framer-text-decoration: none; --framer-text-transform: none; } }',
	'@media (max-width: 500px) and (min-width: 0px) { .framer-N6iNp .framer-styles-preset-1bkecfj:not(.rich-text-wrapper), .framer-N6iNp .framer-styles-preset-1bkecfj.rich-text-wrapper h2 { --framer-font-family: "Tiempos Headline Light", "Tiempos Headline Light Placeholder", sans-serif; --framer-font-size: 36px; --framer-font-style: normal; --framer-font-weight: 400; --framer-letter-spacing: 0em; --framer-line-height: 1.25em; --framer-paragraph-spacing: 0px; --framer-text-alignment: start; --framer-text-color: var(--token-38e34800-80da-44a7-911f-74b9aae91a0c, rgba(0, 0, 0, 0.9)); --framer-text-decoration: none; --framer-text-transform: none; } }',
];
var className2 = "framer-N6iNp";

// /:https://framerusercontent.com/modules/G7Wga7DYLrpdTRnSuvSH/QfMnF5BvuUVUPgrs9mY7/E6NwIheFv.js
var SectionNumberCopyFonts = getFonts(stdin_default);
var cycleOrder = ["y4znLlweb", "E6od26Slr", "tS6x3re8k", "xrLstY_4M"];
var serializationHash = "framer-ZhFxV";
var variantClassNames = {
	E6od26Slr: "framer-v-24syt5",
	tS6x3re8k: "framer-v-1k5o2b7",
	xrLstY_4M: "framer-v-14muio8",
	y4znLlweb: "framer-v-806rq2",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants === null || variants === void 0
		? void 0
		: variants.forEach(
				(variant) =>
					variant && Object.assign(nextOverrides, overrides[variant]),
			);
	return nextOverrides;
}
var transitions = {
	default: {
		damping: 60,
		delay: 0,
		mass: 1,
		stiffness: 500,
		type: "spring",
	},
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition =
		value !== null && value !== void 0 ? value : config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var humanReadableVariantMap = {
	"Dark Mode": "y4znLlweb",
	"Light Mode": "tS6x3re8k",
	"M Dark Mode": "xrLstY_4M",
	"M Light Mode": "E6od26Slr",
};
var getProps = ({ height, id, number, title, width, ...props }) => {
	var _ref, _ref1, _humanReadableVariantMap_props_variant, _ref2;
	return {
		...props,
		Be4l9UJs3:
			(_ref = title !== null && title !== void 0 ? title : props.Be4l9UJs3) !==
				null && _ref !== void 0
				? _ref
				: "Context",
		IfIpVxoKc:
			(_ref1 =
				number !== null && number !== void 0 ? number : props.IfIpVxoKc) !==
				null && _ref1 !== void 0
				? _ref1
				: "01",
		variant:
			(_ref2 =
				(_humanReadableVariantMap_props_variant =
					humanReadableVariantMap[props.variant]) !== null &&
				_humanReadableVariantMap_props_variant !== void 0
					? _humanReadableVariantMap_props_variant
					: props.variant) !== null && _ref2 !== void 0
				? _ref2
				: "y4znLlweb",
	};
};
var createLayoutDependency = (props, variants) =>
	variants.join("-") + props.layoutDependency;
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const { activeLocale, setLocale } = useLocaleInfo();
	const {
		style,
		className: className3,
		layoutId,
		variant,
		Be4l9UJs3,
		IfIpVxoKc,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		gestureVariant,
		setGestureState,
		setVariant,
		transition,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "y4znLlweb",
		transitions,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const isOnCanvas = useIsOnFramerCanvas();
	const initialVariant = useConstant(() => variant);
	const ref1 = React.useRef(null);
	const isDisplayed = () => {
		if (["E6od26Slr", "xrLstY_4M"].includes(baseVariant)) return false;
		return true;
	};
	const defaultLayoutId = React.useId();
	const sharedStyleClassNames = [className2, className];
	return (
		<LayoutGroup
			id={layoutId !== null && layoutId !== void 0 ? layoutId : defaultLayoutId}
		>
			<Transition value={transition}>
				<motion.div
					{...restProps}
					animate={variants}
					className={cx(
						serializationHash,
						...sharedStyleClassNames,
						"framer-806rq2",
						className3,
						classNames,
					)}
					data-framer-name={"Dark Mode"}
					initial={isOnCanvas ? variant : initialVariant}
					layoutDependency={layoutDependency}
					layoutId={"y4znLlweb"}
					onHoverEnd={() =>
						setGestureState({
							isHovered: false,
						})
					}
					onHoverStart={() =>
						setGestureState({
							isHovered: true,
						})
					}
					onTap={() =>
						setGestureState({
							isPressed: false,
						})
					}
					onTapCancel={() =>
						setGestureState({
							isPressed: false,
						})
					}
					onTapStart={() =>
						setGestureState({
							isPressed: true,
						})
					}
					ref={ref !== null && ref !== void 0 ? ref : ref1}
					style={{
						...style,
					}}
					{...addPropertyOverrides(
						{
							E6od26Slr: {
								"data-framer-name": "M Light Mode",
							},
							tS6x3re8k: {
								"data-framer-name": "Light Mode",
							},
							xrLstY_4M: {
								"data-framer-name": "M Dark Mode",
							},
						},
						baseVariant,
						gestureVariant,
					)}
				>
					{isDisplayed() && (
						<motion.div
							className={"framer-1geu0p9-container"}
							layoutDependency={layoutDependency}
							layoutId={"c1PWdStXt-container"}
						>
							{_jsx(stdin_default, {
								eYAdJzwoc: IfIpVxoKc,
								height: "100%",
								id: "c1PWdStXt",
								layoutId: "c1PWdStXt",
								style: {
									height: "100%",
									width: "100%",
								},
								variant: "vQ85ns5t9",
								width: "100%",
								...addPropertyOverrides(
									{
										tS6x3re8k: {
											variant: "BjSZ9phOd",
										},
									},
									baseVariant,
									gestureVariant,
								),
							})}
						</motion.div>
					)}
					<RichText
						__fromCanvasComponent={true}
						className={"framer-orf4ia"}
						layoutDependency={layoutDependency}
						layoutId={"pbKxgk8sI"}
						style={{
							"--extracted-1of0zx5":
								"var(--token-0646263c-1e98-47cd-9020-0c1d771c1075, rgb(255, 255, 255))",
							"--framer-link-text-color": "rgb(0, 153, 255)",
							"--framer-link-text-decoration": "underline",
						}}
						text={Be4l9UJs3}
						variants={{
							E6od26Slr: {
								"--extracted-gdpscs":
									"var(--token-38e34800-80da-44a7-911f-74b9aae91a0c, rgba(0, 0, 0, 0.9))",
							},
							tS6x3re8k: {
								"--extracted-1of0zx5":
									"var(--token-38e34800-80da-44a7-911f-74b9aae91a0c, rgba(0, 0, 0, 0.9))",
							},
							xrLstY_4M: {
								"--extracted-gdpscs":
									"var(--token-0646263c-1e98-47cd-9020-0c1d771c1075, rgb(255, 255, 255))",
							},
						}}
						verticalAlignment={"top"}
						withExternalLayout={true}
						{...addPropertyOverrides(
							{
								E6od26Slr: {
									children: (
										<React.Fragment>
											<motion.h1
												className={"framer-styles-preset-z84o0n"}
												data-styles-preset={"DqgyYQx9o"}
												style={{
													"--framer-text-color":
														"var(--extracted-gdpscs, var(--token-38e34800-80da-44a7-911f-74b9aae91a0c, rgba(0, 0, 0, 0.9)))",
												}}
											>
												{"Context"}
											</motion.h1>
										</React.Fragment>
									),
								},
								tS6x3re8k: {
									children: (
										<React.Fragment>
											<motion.h2
												className={"framer-styles-preset-1bkecfj"}
												data-styles-preset={"pUjbPuiTc"}
												style={{
													"--framer-text-color":
														"var(--extracted-1of0zx5, var(--token-38e34800-80da-44a7-911f-74b9aae91a0c, rgba(0, 0, 0, 0.9)))",
												}}
											>
												{"Context"}
											</motion.h2>
										</React.Fragment>
									),
								},
								xrLstY_4M: {
									children: (
										<React.Fragment>
											<motion.h1
												className={"framer-styles-preset-z84o0n"}
												data-styles-preset={"DqgyYQx9o"}
												style={{
													"--framer-text-color":
														"var(--extracted-gdpscs, var(--token-0646263c-1e98-47cd-9020-0c1d771c1075, rgb(255, 255, 255)))",
												}}
											>
												{"Context"}
											</motion.h1>
										</React.Fragment>
									),
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<React.Fragment>
							<motion.h2
								className={"framer-styles-preset-1bkecfj"}
								data-styles-preset={"pUjbPuiTc"}
								style={{
									"--framer-text-color":
										"var(--extracted-1of0zx5, var(--token-0646263c-1e98-47cd-9020-0c1d771c1075, rgb(255, 255, 255)))",
								}}
							>
								{"Context"}
							</motion.h2>
						</React.Fragment>
					</RichText>
				</motion.div>
			</Transition>
		</LayoutGroup>
	);
});
var css3 = [
	'.framer-ZhFxV[data-border="true"]::after, .framer-ZhFxV [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; pointer-events: none; }',
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-ZhFxV.framer-1pelkp8, .framer-ZhFxV .framer-1pelkp8 { display: block; }",
	".framer-ZhFxV.framer-806rq2 { align-content: flex-start; align-items: flex-start; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: center; overflow: visible; padding: 0px 0px 24px 0px; position: relative; width: 1360px; }",
	".framer-ZhFxV .framer-1geu0p9-container { flex: none; height: 64px; left: -88px; position: absolute; top: 8px; width: 64px; z-index: 1; }",
	".framer-ZhFxV .framer-orf4ia { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
	"@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-ZhFxV.framer-806rq2 { gap: 0px; } .framer-ZhFxV.framer-806rq2 > * { margin: 0px; margin-bottom: calc(0px / 2); margin-top: calc(0px / 2); } .framer-ZhFxV.framer-806rq2 > :first-child { margin-top: 0px; } .framer-ZhFxV.framer-806rq2 > :last-child { margin-bottom: 0px; } }",
	".framer-ZhFxV.framer-v-24syt5.framer-806rq2 { padding: 0px 0px 0px 0px; width: 390px; }",
	".framer-ZhFxV.framer-v-14muio8.framer-806rq2 { gap: 8px; padding: 0px 0px 0px 0px; width: 768px; }",
	"@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-ZhFxV.framer-v-14muio8.framer-806rq2 { gap: 0px; } .framer-ZhFxV.framer-v-14muio8.framer-806rq2 > * { margin: 0px; margin-bottom: calc(8px / 2); margin-top: calc(8px / 2); } .framer-ZhFxV.framer-v-14muio8.framer-806rq2 > :first-child { margin-top: 0px; } .framer-ZhFxV.framer-v-14muio8.framer-806rq2 > :last-child { margin-bottom: 0px; } }",
	...css2,
	...css,
];
var FramerE6NwIheFv = withCSS(Component, css3, "framer-ZhFxV");
var stdin_default2 = FramerE6NwIheFv;
FramerE6NwIheFv.displayName = "CS Section Header";
FramerE6NwIheFv.defaultProps = {
	height: 104,
	width: 1360,
};
addPropertyControls(FramerE6NwIheFv, {
	variant: {
		options: ["y4znLlweb", "E6od26Slr", "tS6x3re8k", "xrLstY_4M"],
		optionTitles: ["Dark Mode", "M Light Mode", "Light Mode", "M Dark Mode"],
		title: "Variant",
		type: ControlType.Enum,
	},
	Be4l9UJs3: {
		defaultValue: "Context",
		displayTextArea: false,
		title: "Title",
		type: ControlType.String,
	},
	IfIpVxoKc: {
		defaultValue: "01",
		displayTextArea: false,
		title: "Number",
		type: ControlType.String,
	},
});
addFonts(FramerE6NwIheFv, [...SectionNumberCopyFonts, ...fonts2, ...fonts]);

// virtual:cs-section-header
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "E6od26Slr",
	xl: "tS6x3re8k",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"1763929c89cf4969ad190da187fc25ea516fa82b7cf163cf1161896117bee1d5"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default2, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders CsSectionHeaderFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"1763929c89cf4969ad190da187fc25ea516fa82b7cf163cf1161896117bee1d5"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default2}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default2);
var cs_section_header_default = ComponentWithRoot;
export { cs_section_header_default as default };
