// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 1763929c89cf4969 "Patrick McKowen", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Dark Mode' | 'Dark Mode Collapsed' | 'Light Mode' | 'LIght Mode Collapsed' // Variant
 * title?: string // Title
}} Props

 */
import { className, css, fonts } from "./chunks/chunk-RRAHJCFQ.js";
import { routes } from "./chunks/chunk-IRNZKG45.js";

// virtual:cs-section-subhead
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/gCex7lM2WV4qkPUqarGd/Od2gCgMIVgYyRihixmpp/MffcJUdoK.js
import { jsx as _jsx } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	RichText,
	useConstant,
	useIsOnFramerCanvas,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
var cycleOrder = ["IZ8JLLAFg", "f6IF6os7q", "z94CtyTww", "tpp72QhZY"];
var serializationHash = "framer-NUy09";
var variantClassNames = {
	f6IF6os7q: "framer-v-1lwf5ps",
	IZ8JLLAFg: "framer-v-f3m44r",
	tpp72QhZY: "framer-v-9h5tb4",
	z94CtyTww: "framer-v-151jndy",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants === null || variants === void 0
		? void 0
		: variants.forEach(
				(variant) =>
					variant && Object.assign(nextOverrides, overrides[variant]),
			);
	return nextOverrides;
}
var transitions = {
	default: {
		damping: 60,
		delay: 0,
		mass: 1,
		stiffness: 500,
		type: "spring",
	},
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition =
		value !== null && value !== void 0 ? value : config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var humanReadableVariantMap = {
	"Dark Mode Collapsed": "f6IF6os7q",
	"Dark Mode": "IZ8JLLAFg",
	"LIght Mode Collapsed": "tpp72QhZY",
	"Light Mode": "z94CtyTww",
};
var getProps = ({ height, id, title, width, ...props }) => {
	var _humanReadableVariantMap_props_variant, _ref, _ref1;
	return {
		...props,
		variant:
			(_ref =
				(_humanReadableVariantMap_props_variant =
					humanReadableVariantMap[props.variant]) !== null &&
				_humanReadableVariantMap_props_variant !== void 0
					? _humanReadableVariantMap_props_variant
					: props.variant) !== null && _ref !== void 0
				? _ref
				: "IZ8JLLAFg",
		xMWnZrdBx:
			(_ref1 = title !== null && title !== void 0 ? title : props.xMWnZrdBx) !==
				null && _ref1 !== void 0
				? _ref1
				: "Problem definitions",
	};
};
var createLayoutDependency = (props, variants) =>
	variants.join("-") + props.layoutDependency;
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const { activeLocale, setLocale } = useLocaleInfo();
	const {
		style,
		className: className2,
		layoutId,
		variant,
		xMWnZrdBx,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		gestureVariant,
		setGestureState,
		setVariant,
		transition,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "IZ8JLLAFg",
		transitions,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const isOnCanvas = useIsOnFramerCanvas();
	const initialVariant = useConstant(() => variant);
	const ref1 = React.useRef(null);
	const defaultLayoutId = React.useId();
	const sharedStyleClassNames = [className];
	return (
		<LayoutGroup
			id={layoutId !== null && layoutId !== void 0 ? layoutId : defaultLayoutId}
		>
			<Transition value={transition}>
				<motion.div
					{...restProps}
					animate={variants}
					className={cx(
						serializationHash,
						...sharedStyleClassNames,
						"framer-f3m44r",
						className2,
						classNames,
					)}
					data-framer-name={"Dark Mode"}
					initial={isOnCanvas ? variant : initialVariant}
					layoutDependency={layoutDependency}
					layoutId={"IZ8JLLAFg"}
					onHoverEnd={() =>
						setGestureState({
							isHovered: false,
						})
					}
					onHoverStart={() =>
						setGestureState({
							isHovered: true,
						})
					}
					onTap={() =>
						setGestureState({
							isPressed: false,
						})
					}
					onTapCancel={() =>
						setGestureState({
							isPressed: false,
						})
					}
					onTapStart={() =>
						setGestureState({
							isPressed: true,
						})
					}
					ref={ref !== null && ref !== void 0 ? ref : ref1}
					style={{
						...style,
					}}
					{...addPropertyOverrides(
						{
							f6IF6os7q: {
								"data-framer-name": "Dark Mode Collapsed",
							},
							tpp72QhZY: {
								"data-framer-name": "LIght Mode Collapsed",
							},
							z94CtyTww: {
								"data-framer-name": "Light Mode",
							},
						},
						baseVariant,
						gestureVariant,
					)}
				>
					<RichText
						__fromCanvasComponent={true}
						className={"framer-psiy8k"}
						layoutDependency={layoutDependency}
						layoutId={"FReU8o5j5"}
						style={{
							"--extracted-a0htzi":
								"var(--token-0646263c-1e98-47cd-9020-0c1d771c1075, rgb(255, 255, 255))",
							"--framer-link-text-color": "rgb(0, 153, 255)",
							"--framer-link-text-decoration": "underline",
						}}
						text={xMWnZrdBx}
						verticalAlignment={"top"}
						withExternalLayout={true}
						{...addPropertyOverrides(
							{
								tpp72QhZY: {
									children: (
										<React.Fragment>
											<motion.h3
												className={"framer-styles-preset-gdhw34"}
												data-styles-preset={"im8OSauR5"}
											>
												{"Problem definitions"}
											</motion.h3>
										</React.Fragment>
									),
								},
								z94CtyTww: {
									children: (
										<React.Fragment>
											<motion.h3
												className={"framer-styles-preset-gdhw34"}
												data-styles-preset={"im8OSauR5"}
											>
												{"Problem definitions"}
											</motion.h3>
										</React.Fragment>
									),
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<React.Fragment>
							<motion.h3
								className={"framer-styles-preset-gdhw34"}
								data-styles-preset={"im8OSauR5"}
								style={{
									"--framer-text-color":
										"var(--extracted-a0htzi, var(--token-0646263c-1e98-47cd-9020-0c1d771c1075, rgb(255, 255, 255)))",
								}}
							>
								{"Problem definitions"}
							</motion.h3>
						</React.Fragment>
					</RichText>
				</motion.div>
			</Transition>
		</LayoutGroup>
	);
});
var css2 = [
	'.framer-NUy09[data-border="true"]::after, .framer-NUy09 [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; pointer-events: none; }',
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-NUy09.framer-1iogs0i, .framer-NUy09 .framer-1iogs0i { display: block; }",
	".framer-NUy09.framer-f3m44r { align-content: center; align-items: center; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: hidden; padding: 24px 0px 0px 0px; position: relative; width: 640px; }",
	".framer-NUy09 .framer-psiy8k { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
	"@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-NUy09.framer-f3m44r { gap: 0px; } .framer-NUy09.framer-f3m44r > * { margin: 0px; margin-left: calc(10px / 2); margin-right: calc(10px / 2); } .framer-NUy09.framer-f3m44r > :first-child { margin-left: 0px; } .framer-NUy09.framer-f3m44r > :last-child { margin-right: 0px; } }",
	".framer-NUy09.framer-v-1lwf5ps.framer-f3m44r, .framer-NUy09.framer-v-9h5tb4.framer-f3m44r { padding: 0px 0px 0px 0px; }",
	...css,
];
var FramerMffcJUdoK = withCSS(Component, css2, "framer-NUy09");
var stdin_default = FramerMffcJUdoK;
FramerMffcJUdoK.displayName = "CS Section Subhead";
FramerMffcJUdoK.defaultProps = {
	height: 60,
	width: 640,
};
addPropertyControls(FramerMffcJUdoK, {
	variant: {
		options: ["IZ8JLLAFg", "f6IF6os7q", "z94CtyTww", "tpp72QhZY"],
		optionTitles: [
			"Dark Mode",
			"Dark Mode Collapsed",
			"Light Mode",
			"LIght Mode Collapsed",
		],
		title: "Variant",
		type: ControlType.Enum,
	},
	xMWnZrdBx: {
		defaultValue: "Problem definitions",
		displayTextArea: false,
		title: "Title",
		type: ControlType.String,
	},
});
addFonts(FramerMffcJUdoK, [...fonts]);

// virtual:cs-section-subhead
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "z94CtyTww",
	xl: "IZ8JLLAFg",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"1763929c89cf4969ad190da187fc25ea516fa82b7cf163cf1161896117bee1d5"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders CsSectionSubheadFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"1763929c89cf4969ad190da187fc25ea516fa82b7cf163cf1161896117bee1d5"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var cs_section_subhead_default = ComponentWithRoot;
export { cs_section_subhead_default as default };
