// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 1763929c89cf4969 "Patrick McKowen", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'C4B Licensing' | 'Mobile' | 'Tablet' // Variant
}} Props

 */
import { stdin_default } from "./chunks/chunk-L2WUYNVA.js";
import "./chunks/chunk-F3PUWBZ4.js";
import "./chunks/chunk-AWZNHXD6.js";
import { routes } from "./chunks/chunk-IRNZKG45.js";

// virtual:hero-image
import { Fragment } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/lcfXBB9H1pQ8Pr88M5x2/k0s4cHWdi36vrRSUMDy9/CJ7_dL2m2.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	getFonts,
	Image,
	useConstant,
	useIsOnFramerCanvas,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
var DesktopVideoFonts = getFonts(stdin_default);
var cycleOrder = ["oYDwgDP3X", "GqKUsDHqC", "EmmO_V6Gz"];
var serializationHash = "framer-CoJkR";
var variantClassNames = {
	EmmO_V6Gz: "framer-v-1t4lbod",
	GqKUsDHqC: "framer-v-kzb8ik",
	oYDwgDP3X: "framer-v-1x2xp0r",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants === null || variants === void 0
		? void 0
		: variants.forEach(
				(variant) =>
					variant && Object.assign(nextOverrides, overrides[variant]),
			);
	return nextOverrides;
}
var transitions = {
	default: {
		damping: 60,
		delay: 0,
		mass: 1,
		stiffness: 500,
		type: "spring",
	},
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition =
		value !== null && value !== void 0 ? value : config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var humanReadableVariantMap = {
	"C4B Licensing": "oYDwgDP3X",
	Mobile: "GqKUsDHqC",
	Tablet: "EmmO_V6Gz",
};
var getProps = ({ height, id, width, ...props }) => {
	var _humanReadableVariantMap_props_variant, _ref;
	return {
		...props,
		variant:
			(_ref =
				(_humanReadableVariantMap_props_variant =
					humanReadableVariantMap[props.variant]) !== null &&
				_humanReadableVariantMap_props_variant !== void 0
					? _humanReadableVariantMap_props_variant
					: props.variant) !== null && _ref !== void 0
				? _ref
				: "oYDwgDP3X",
	};
};
var createLayoutDependency = (props, variants) =>
	variants.join("-") + props.layoutDependency;
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const { activeLocale, setLocale } = useLocaleInfo();
	const { style, className, layoutId, variant, ...restProps } = getProps(props);
	const {
		baseVariant,
		classNames,
		gestureVariant,
		setGestureState,
		setVariant,
		transition,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "oYDwgDP3X",
		transitions,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const isOnCanvas = useIsOnFramerCanvas();
	const initialVariant = useConstant(() => variant);
	const ref1 = React.useRef(null);
	const defaultLayoutId = React.useId();
	const sharedStyleClassNames = [];
	return (
		<LayoutGroup
			id={layoutId !== null && layoutId !== void 0 ? layoutId : defaultLayoutId}
		>
			<Transition value={transition}>
				<motion.div
					{...restProps}
					animate={variants}
					background={{
						alt: "",
						fit: "fill",
						intrinsicHeight: 2160,
						intrinsicWidth: 3840,
					}}
					className={cx(
						serializationHash,
						...sharedStyleClassNames,
						"framer-1x2xp0r",
						className,
						classNames,
					)}
					data-framer-name={"C4B Licensing"}
					initial={isOnCanvas ? variant : initialVariant}
					layoutDependency={layoutDependency}
					layoutId={"oYDwgDP3X"}
					onHoverEnd={() =>
						setGestureState({
							isHovered: false,
						})
					}
					onHoverStart={() =>
						setGestureState({
							isHovered: true,
						})
					}
					onTap={() =>
						setGestureState({
							isPressed: false,
						})
					}
					onTapCancel={() =>
						setGestureState({
							isPressed: false,
						})
					}
					onTapStart={() =>
						setGestureState({
							isPressed: true,
						})
					}
					ref={ref !== null && ref !== void 0 ? ref : ref1}
					style={{
						borderBottomLeftRadius: 4,
						borderBottomRightRadius: 4,
						borderTopLeftRadius: 4,
						borderTopRightRadius: 4,
						...style,
					}}
					variants={{
						EmmO_V6Gz: {
							borderBottomLeftRadius: 8,
							borderBottomRightRadius: 8,
							borderTopLeftRadius: 8,
							borderTopRightRadius: 8,
						},
						GqKUsDHqC: {
							borderBottomLeftRadius: 0,
							borderBottomRightRadius: 0,
							borderTopLeftRadius: 0,
							borderTopRightRadius: 0,
						},
					}}
					{...addPropertyOverrides(
						{
							EmmO_V6Gz: {
								"data-framer-name": "Tablet",
							},
							GqKUsDHqC: {
								"data-framer-name": "Mobile",
							},
						},
						baseVariant,
						gestureVariant,
					)}
				>
					<Image
						background={{
							alt: "",
							fit: "fill",
							intrinsicHeight: 1440,
							intrinsicWidth: 1920,
							pixelHeight: 1440,
							pixelWidth: 1920,
							sizes: "calc(min(1200px, 100vw) - 160px)",
							src: "https://framerusercontent.com/images/bwQaTAjxoaakxIbykvDNlbh8zig.jpg",
							srcSet:
								"https://framerusercontent.com/images/bwQaTAjxoaakxIbykvDNlbh8zig.jpg?scale-down-to=512 512w, https://framerusercontent.com/images/bwQaTAjxoaakxIbykvDNlbh8zig.jpg?scale-down-to=1024 1024w, https://framerusercontent.com/images/bwQaTAjxoaakxIbykvDNlbh8zig.jpg 1920w",
						}}
						className={"framer-18aqmql"}
						data-framer-name={"Wallpaper"}
						layoutDependency={layoutDependency}
						layoutId={"nPJS0bdr_"}
						{...addPropertyOverrides(
							{
								EmmO_V6Gz: {
									background: {
										alt: "",
										fit: "fill",
										intrinsicHeight: 1440,
										intrinsicWidth: 1920,
										pixelHeight: 1440,
										pixelWidth: 1920,
										sizes: "calc(min(1200px, 100vw) - 80px)",
										src: "https://framerusercontent.com/images/bwQaTAjxoaakxIbykvDNlbh8zig.jpg",
										srcSet:
											"https://framerusercontent.com/images/bwQaTAjxoaakxIbykvDNlbh8zig.jpg?scale-down-to=512 512w, https://framerusercontent.com/images/bwQaTAjxoaakxIbykvDNlbh8zig.jpg?scale-down-to=1024 1024w, https://framerusercontent.com/images/bwQaTAjxoaakxIbykvDNlbh8zig.jpg 1920w",
									},
								},
								GqKUsDHqC: {
									background: {
										alt: "",
										fit: "fill",
										intrinsicHeight: 1440,
										intrinsicWidth: 1920,
										pixelHeight: 1440,
										pixelWidth: 1920,
										sizes: "calc(min(1200px, 100vw) - 40px)",
										src: "https://framerusercontent.com/images/bwQaTAjxoaakxIbykvDNlbh8zig.jpg",
										srcSet:
											"https://framerusercontent.com/images/bwQaTAjxoaakxIbykvDNlbh8zig.jpg?scale-down-to=512 512w, https://framerusercontent.com/images/bwQaTAjxoaakxIbykvDNlbh8zig.jpg?scale-down-to=1024 1024w, https://framerusercontent.com/images/bwQaTAjxoaakxIbykvDNlbh8zig.jpg 1920w",
									},
								},
							},
							baseVariant,
							gestureVariant,
						)}
					/>
					<motion.div
						className={"framer-1p375h0"}
						data-framer-name={"Video Container"}
						layoutDependency={layoutDependency}
						layoutId={"RibIBJFMw"}
						style={{
							backgroundColor:
								"var(--token-818e09a1-3c74-421a-9212-ad9736d0fcd6, rgb(18, 17, 20))",
							borderBottomLeftRadius: 16,
							borderBottomRightRadius: 16,
							borderTopLeftRadius: 16,
							borderTopRightRadius: 16,
							boxShadow:
								"0px 0.7961918735236395px 0.7961918735236395px 0px rgba(0, 0, 0, 0.00796), 0px 2.414506143104518px 2.414506143104518px 0px rgba(0, 0, 0, 0.02415), 0px 6.382653521484461px 6.382653521484461px 0px rgba(0, 0, 0, 0.06383), 0px 20px 20px 0px rgba(0, 0, 0, 0.2), 0px 0px 0px 4px rgb(0, 0, 0)",
						}}
						variants={{
							EmmO_V6Gz: {
								borderBottomLeftRadius: 8,
								borderBottomRightRadius: 8,
								borderTopLeftRadius: 8,
								borderTopRightRadius: 8,
								boxShadow:
									"0px 0.7961918735236395px 0.7961918735236395px 0px rgba(0, 0, 0, 0.00796), 0px 2.414506143104518px 2.414506143104518px 0px rgba(0, 0, 0, 0.02415), 0px 6.382653521484461px 6.382653521484461px 0px rgba(0, 0, 0, 0.06383), 0px 20px 20px 0px rgba(0, 0, 0, 0.2), 0px 0px 0px 2px rgb(0, 0, 0)",
							},
							GqKUsDHqC: {
								borderBottomLeftRadius: 8,
								borderBottomRightRadius: 8,
								borderTopLeftRadius: 8,
								borderTopRightRadius: 8,
								boxShadow:
									"0px 0.7961918735236395px 0.7961918735236395px 0px rgba(0, 0, 0, 0.00796), 0px 2.414506143104518px 2.414506143104518px 0px rgba(0, 0, 0, 0.02415), 0px 6.382653521484461px 6.382653521484461px 0px rgba(0, 0, 0, 0.06383), 0px 20px 20px 0px rgba(0, 0, 0, 0.2), 0px 0px 0px 2px rgb(0, 0, 0)",
							},
						}}
					>
						<motion.div
							className={"framer-1dae8r-container"}
							layoutDependency={layoutDependency}
							layoutId={"rDqAMgEkr-container"}
						>
							{_jsx(stdin_default, {
								height: "100%",
								id: "rDqAMgEkr",
								kyhStz601: true,
								layoutId: "rDqAMgEkr",
								O7lx0VYWZ: false,
								style: {
									height: "100%",
									width: "100%",
								},
								uI5PmX3Gn: true,
								variant: "CT8OHTyOX",
								width: "100%",
								...addPropertyOverrides(
									{
										GqKUsDHqC: {
											kyhStz601: false,
											O7lx0VYWZ: true,
											uI5PmX3Gn: false,
										},
									},
									baseVariant,
									gestureVariant,
								),
							})}
						</motion.div>
					</motion.div>
				</motion.div>
			</Transition>
		</LayoutGroup>
	);
});
var css = [
	'.framer-CoJkR[data-border="true"]::after, .framer-CoJkR [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; pointer-events: none; }',
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-CoJkR.framer-147z447, .framer-CoJkR .framer-147z447 { display: block; }",
	".framer-CoJkR.framer-1x2xp0r { align-content: center; align-items: center; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 0px; height: auto; justify-content: center; overflow: hidden; padding: 80px 80px 80px 80px; position: relative; width: 1200px; will-change: var(--framer-will-change-override, transform); }",
	".framer-CoJkR .framer-18aqmql { aspect-ratio: 1.3333333333333333 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 900px); left: 0px; overflow: visible; position: absolute; top: 0px; width: 100%; z-index: 0; }",
	".framer-CoJkR .framer-1p375h0 { align-content: center; align-items: center; aspect-ratio: 1.6 / 1; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: var(--framer-aspect-ratio-supported, 650px); justify-content: center; overflow: hidden; padding: 0px 0px 0px 0px; position: relative; width: 100%; will-change: var(--framer-will-change-override, transform); }",
	".framer-CoJkR .framer-1dae8r-container { flex: none; height: 100%; position: relative; width: 100%; }",
	"@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-CoJkR.framer-1x2xp0r, .framer-CoJkR .framer-1p375h0 { gap: 0px; } .framer-CoJkR.framer-1x2xp0r > * { margin: 0px; margin-left: calc(0px / 2); margin-right: calc(0px / 2); } .framer-CoJkR.framer-1x2xp0r > :first-child, .framer-CoJkR .framer-1p375h0 > :first-child { margin-left: 0px; } .framer-CoJkR.framer-1x2xp0r > :last-child, .framer-CoJkR .framer-1p375h0 > :last-child { margin-right: 0px; } .framer-CoJkR .framer-1p375h0 > * { margin: 0px; margin-left: calc(10px / 2); margin-right: calc(10px / 2); } }",
	".framer-CoJkR.framer-v-kzb8ik.framer-1x2xp0r { padding: 20px 20px 20px 20px; }",
	".framer-CoJkR.framer-v-kzb8ik .framer-1p375h0 { height: var(--framer-aspect-ratio-supported, 725px); }",
	".framer-CoJkR.framer-v-1t4lbod.framer-1x2xp0r { padding: 40px 40px 40px 40px; }",
	".framer-CoJkR.framer-v-1t4lbod .framer-1p375h0 { height: var(--framer-aspect-ratio-supported, 700px); }",
];
var FramerCJ7_dL2m2 = withCSS(Component, css, "framer-CoJkR");
var stdin_default2 = FramerCJ7_dL2m2;
FramerCJ7_dL2m2.displayName = "Hero Image";
FramerCJ7_dL2m2.defaultProps = {
	height: 810,
	width: 1200,
};
addPropertyControls(FramerCJ7_dL2m2, {
	variant: {
		options: ["oYDwgDP3X", "GqKUsDHqC", "EmmO_V6Gz"],
		optionTitles: ["C4B Licensing", "Mobile", "Tablet"],
		title: "Variant",
		type: ControlType.Enum,
	},
});
addFonts(FramerCJ7_dL2m2, [...DesktopVideoFonts]);

// virtual:hero-image
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"1763929c89cf4969ad190da187fc25ea516fa82b7cf163cf1161896117bee1d5"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default2, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders HeroImageFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"1763929c89cf4969ad190da187fc25ea516fa82b7cf163cf1161896117bee1d5"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default2}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default2);
var hero_image_default = ComponentWithRoot;
export { hero_image_default as default };
