// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 1763929c89cf4969 "Patrick McKowen", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Work' | 'About' | 'Contact' | 'Close Light Mode' | 'Close Dark Mode' // Variant
}} Props

 */
import { stdin_default } from "./chunks/chunk-PCKV72B2.js";
import "./chunks/chunk-T6M5HMBG.js";
import "./chunks/chunk-VSMRQKYW.js";
import { routes } from "./chunks/chunk-IRNZKG45.js";

// virtual:navigation
import { Fragment } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/3jSFRAebevMLOHjnVUOC/ydd4vMJHGXaZ2isuspHm/QHnTUzDag.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	getFonts,
	ResolveLinks,
	useConstant,
	useIsOnFramerCanvas,
	useLocaleInfo,
	useRouter,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
var NavItemFonts = getFonts(stdin_default);
var cycleOrder = [
	"gBtKeRftK",
	"XzpkCjV_T",
	"fSEZN2i_F",
	"eRN9aHEW5",
	"iXbqbsiDP",
];
var serializationHash = "framer-TDysm";
var variantClassNames = {
	eRN9aHEW5: "framer-v-1dzbeo9",
	fSEZN2i_F: "framer-v-dlblzs",
	gBtKeRftK: "framer-v-11cp9up",
	iXbqbsiDP: "framer-v-sjfp53",
	XzpkCjV_T: "framer-v-1m62vs3",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants === null || variants === void 0
		? void 0
		: variants.forEach(
				(variant) =>
					variant && Object.assign(nextOverrides, overrides[variant]),
			);
	return nextOverrides;
}
var transitions = {
	default: {
		damping: 60,
		delay: 0,
		mass: 1,
		stiffness: 500,
		type: "spring",
	},
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition =
		value !== null && value !== void 0 ? value : config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var humanReadableVariantMap = {
	"Close Dark Mode": "iXbqbsiDP",
	"Close Light Mode": "eRN9aHEW5",
	About: "XzpkCjV_T",
	Contact: "fSEZN2i_F",
	Work: "gBtKeRftK",
};
var getProps = ({ height, id, width, ...props }) => {
	var _humanReadableVariantMap_props_variant, _ref;
	return {
		...props,
		variant:
			(_ref =
				(_humanReadableVariantMap_props_variant =
					humanReadableVariantMap[props.variant]) !== null &&
				_humanReadableVariantMap_props_variant !== void 0
					? _humanReadableVariantMap_props_variant
					: props.variant) !== null && _ref !== void 0
				? _ref
				: "gBtKeRftK",
	};
};
var createLayoutDependency = (props, variants) =>
	variants.join("-") + props.layoutDependency;
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const { activeLocale, setLocale } = useLocaleInfo();
	const { style, className, layoutId, variant, ...restProps } = getProps(props);
	const {
		baseVariant,
		classNames,
		gestureVariant,
		setGestureState,
		setVariant,
		transition,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "gBtKeRftK",
		transitions,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const isOnCanvas = useIsOnFramerCanvas();
	const initialVariant = useConstant(() => variant);
	const ref1 = React.useRef(null);
	const isDisplayed = () => {
		if (["XzpkCjV_T", "fSEZN2i_F"].includes(baseVariant)) return false;
		return true;
	};
	const router = useRouter();
	const isDisplayed1 = () => {
		if (["eRN9aHEW5", "iXbqbsiDP"].includes(baseVariant)) return false;
		return true;
	};
	const isDisplayed2 = () => {
		if (baseVariant === "fSEZN2i_F") return true;
		return false;
	};
	const isDisplayed3 = () => {
		if (baseVariant === "XzpkCjV_T") return true;
		return false;
	};
	const defaultLayoutId = React.useId();
	const sharedStyleClassNames = [];
	return (
		<LayoutGroup
			id={layoutId !== null && layoutId !== void 0 ? layoutId : defaultLayoutId}
		>
			<Transition value={transition}>
				<motion.div
					{...restProps}
					animate={variants}
					className={cx(
						serializationHash,
						...sharedStyleClassNames,
						"framer-11cp9up",
						className,
						classNames,
					)}
					data-framer-name={"Work"}
					initial={isOnCanvas ? variant : initialVariant}
					layoutDependency={layoutDependency}
					layoutId={"gBtKeRftK"}
					onHoverEnd={() =>
						setGestureState({
							isHovered: false,
						})
					}
					onHoverStart={() =>
						setGestureState({
							isHovered: true,
						})
					}
					onTap={() =>
						setGestureState({
							isPressed: false,
						})
					}
					onTapCancel={() =>
						setGestureState({
							isPressed: false,
						})
					}
					onTapStart={() =>
						setGestureState({
							isPressed: true,
						})
					}
					ref={ref !== null && ref !== void 0 ? ref : ref1}
					style={{
						...style,
					}}
					{...addPropertyOverrides(
						{
							eRN9aHEW5: {
								"data-framer-name": "Close Light Mode",
							},
							fSEZN2i_F: {
								"data-framer-name": "Contact",
							},
							iXbqbsiDP: {
								"data-framer-name": "Close Dark Mode",
							},
							XzpkCjV_T: {
								"data-framer-name": "About",
							},
						},
						baseVariant,
						gestureVariant,
					)}
				>
					{isDisplayed() && (
						<ResolveLinks
							links={[
								{
									href: {
										hash: ":w7R6Yl18p",
										webPageId: "augiA20Il",
									},
									implicitPathVariables: void 0,
								},
								{
									href: {
										hash: ":w7R6Yl18p",
										webPageId: "augiA20Il",
									},
									implicitPathVariables: void 0,
								},
								{
									href: {
										hash: ":w7R6Yl18p",
										webPageId: "augiA20Il",
									},
									implicitPathVariables: void 0,
								},
							]}
						>
							{(resolvedLinks) => (
								<motion.div
									className={"framer-1pm8f77-container"}
									layoutDependency={layoutDependency}
									layoutId={"XVzPKk3Jv-container"}
								>
									{_jsx(stdin_default, {
										h0W7hUzj4: true,
										height: "100%",
										id: "XVzPKk3Jv",
										JULf1wZ4P: "Work",
										layoutId: "XVzPKk3Jv",
										variant: "jvQh8r8Hf",
										width: "100%",
										zslPDGqUu: resolvedLinks[0],
										...addPropertyOverrides(
											{
												eRN9aHEW5: {
													h0W7hUzj4: false,
													style: {
														height: "100%",
														width: "100%",
													},
													variant: "xKSrJ_3PO",
													zslPDGqUu: resolvedLinks[1],
												},
												iXbqbsiDP: {
													h0W7hUzj4: false,
													style: {
														height: "100%",
														width: "100%",
													},
													variant: "V1HopxI5W",
													zslPDGqUu: resolvedLinks[2],
												},
											},
											baseVariant,
											gestureVariant,
										),
									})}
								</motion.div>
							)}
						</ResolveLinks>
					)}
					{isDisplayed1() && (
						<ResolveLinks
							links={[
								{
									href: {
										hash: ":adkHggR49",
										webPageId: "augiA20Il",
									},
									implicitPathVariables: void 0,
								},
								{
									href: {
										hash: ":adkHggR49",
										webPageId: "augiA20Il",
									},
									implicitPathVariables: void 0,
								},
								{
									href: {
										hash: ":adkHggR49",
										webPageId: "augiA20Il",
									},
									implicitPathVariables: void 0,
								},
							]}
						>
							{(resolvedLinks1) => (
								<motion.div
									className={"framer-cdz97z-container"}
									layoutDependency={layoutDependency}
									layoutId={"YcYHyeWqn-container"}
								>
									{_jsx(stdin_default, {
										h0W7hUzj4: true,
										height: "100%",
										id: "YcYHyeWqn",
										JULf1wZ4P: "About",
										layoutId: "YcYHyeWqn",
										variant: "a0J5cRopZ",
										width: "100%",
										zslPDGqUu: resolvedLinks1[0],
										...addPropertyOverrides(
											{
												fSEZN2i_F: {
													zslPDGqUu: resolvedLinks1[2],
												},
												XzpkCjV_T: {
													variant: "hm4nRvR6U",
													zslPDGqUu: resolvedLinks1[1],
												},
											},
											baseVariant,
											gestureVariant,
										),
									})}
								</motion.div>
							)}
						</ResolveLinks>
					)}
					{isDisplayed2() && (
						<ResolveLinks
							links={[
								{
									href: {
										hash: ":w7R6Yl18p",
										webPageId: "augiA20Il",
									},
									implicitPathVariables: void 0,
								},
								{
									href: {
										hash: ":w7R6Yl18p",
										webPageId: "augiA20Il",
									},
									implicitPathVariables: void 0,
								},
							]}
						>
							{(resolvedLinks2) => (
								<motion.div
									className={"framer-182ewj9-container"}
									layoutDependency={layoutDependency}
									layoutId={"vFNla9NTS-container"}
								>
									{_jsx(stdin_default, {
										h0W7hUzj4: true,
										height: "100%",
										id: "vFNla9NTS",
										JULf1wZ4P: "Work",
										layoutId: "vFNla9NTS",
										variant: "a0J5cRopZ",
										width: "100%",
										zslPDGqUu: resolvedLinks2[0],
										...addPropertyOverrides(
											{
												fSEZN2i_F: {
													zslPDGqUu: resolvedLinks2[1],
												},
											},
											baseVariant,
											gestureVariant,
										),
									})}
								</motion.div>
							)}
						</ResolveLinks>
					)}
					{isDisplayed1() && (
						<ResolveLinks
							links={[
								{
									href: {
										hash: ":gyR50iNkQ",
										webPageId: "augiA20Il",
									},
									implicitPathVariables: void 0,
								},
								{
									href: {
										hash: ":gyR50iNkQ",
										webPageId: "augiA20Il",
									},
									implicitPathVariables: void 0,
								},
								{
									href: {
										hash: ":gyR50iNkQ",
										webPageId: "augiA20Il",
									},
									implicitPathVariables: void 0,
								},
							]}
						>
							{(resolvedLinks3) => (
								<motion.div
									className={"framer-1gizqau-container"}
									layoutDependency={layoutDependency}
									layoutId={"FaCdvGB8q-container"}
								>
									{_jsx(stdin_default, {
										h0W7hUzj4: true,
										height: "100%",
										id: "FaCdvGB8q",
										JULf1wZ4P: "Contact",
										layoutId: "FaCdvGB8q",
										variant: "a0J5cRopZ",
										width: "100%",
										zslPDGqUu: resolvedLinks3[0],
										...addPropertyOverrides(
											{
												fSEZN2i_F: {
													variant: "jvQh8r8Hf",
													zslPDGqUu: resolvedLinks3[2],
												},
												XzpkCjV_T: {
													variant: "kgFBsi_Nl",
													zslPDGqUu: resolvedLinks3[1],
												},
											},
											baseVariant,
											gestureVariant,
										),
									})}
								</motion.div>
							)}
						</ResolveLinks>
					)}
					{isDisplayed3() && (
						<ResolveLinks
							links={[
								{
									href: {
										hash: ":w7R6Yl18p",
										webPageId: "augiA20Il",
									},
									implicitPathVariables: void 0,
								},
								{
									href: {
										hash: ":w7R6Yl18p",
										webPageId: "augiA20Il",
									},
									implicitPathVariables: void 0,
								},
							]}
						>
							{(resolvedLinks4) => (
								<motion.div
									className={"framer-xxa8sk-container"}
									layoutDependency={layoutDependency}
									layoutId={"eJ5mdYUeO-container"}
								>
									{_jsx(stdin_default, {
										h0W7hUzj4: true,
										height: "100%",
										id: "eJ5mdYUeO",
										JULf1wZ4P: "Work",
										layoutId: "eJ5mdYUeO",
										variant: "kgFBsi_Nl",
										width: "100%",
										zslPDGqUu: resolvedLinks4[0],
										...addPropertyOverrides(
											{
												XzpkCjV_T: {
													zslPDGqUu: resolvedLinks4[1],
												},
											},
											baseVariant,
											gestureVariant,
										),
									})}
								</motion.div>
							)}
						</ResolveLinks>
					)}
				</motion.div>
			</Transition>
		</LayoutGroup>
	);
});
var css = [
	'.framer-TDysm[data-border="true"]::after, .framer-TDysm [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; pointer-events: none; }',
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-TDysm.framer-1aogyoo, .framer-TDysm .framer-1aogyoo { display: block; }",
	".framer-TDysm.framer-11cp9up { align-content: center; align-items: center; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: flex-end; padding: 0px 0px 0px 0px; position: relative; width: min-content; }",
	".framer-TDysm .framer-1pm8f77-container, .framer-TDysm .framer-cdz97z-container, .framer-TDysm .framer-182ewj9-container, .framer-TDysm .framer-1gizqau-container, .framer-TDysm .framer-xxa8sk-container { flex: none; height: auto; position: relative; width: auto; }",
	"@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-TDysm.framer-11cp9up { gap: 0px; } .framer-TDysm.framer-11cp9up > * { margin: 0px; margin-left: calc(10px / 2); margin-right: calc(10px / 2); } .framer-TDysm.framer-11cp9up > :first-child { margin-left: 0px; } .framer-TDysm.framer-11cp9up > :last-child { margin-right: 0px; } }",
	".framer-TDysm.framer-v-1m62vs3 .framer-cdz97z-container, .framer-TDysm.framer-v-dlblzs .framer-cdz97z-container { order: 2; }",
	".framer-TDysm.framer-v-1m62vs3 .framer-1gizqau-container { order: 4; }",
	".framer-TDysm.framer-v-1m62vs3 .framer-xxa8sk-container, .framer-TDysm.framer-v-dlblzs .framer-182ewj9-container { order: 1; }",
	".framer-TDysm.framer-v-dlblzs .framer-1gizqau-container { order: 3; }",
	".framer-TDysm.framer-v-1dzbeo9.framer-11cp9up, .framer-TDysm.framer-v-sjfp53.framer-11cp9up { height: 47px; width: 47px; }",
	".framer-TDysm.framer-v-1dzbeo9 .framer-1pm8f77-container, .framer-TDysm.framer-v-sjfp53 .framer-1pm8f77-container { flex: 1 0 0px; height: 100%; width: 1px; }",
];
var FramerQHnTUzDag = withCSS(Component, css, "framer-TDysm");
var stdin_default2 = FramerQHnTUzDag;
FramerQHnTUzDag.displayName = "Navigation";
FramerQHnTUzDag.defaultProps = {
	height: 47,
	width: 294.5,
};
addPropertyControls(FramerQHnTUzDag, {
	variant: {
		options: ["gBtKeRftK", "XzpkCjV_T", "fSEZN2i_F", "eRN9aHEW5", "iXbqbsiDP"],
		optionTitles: [
			"Work",
			"About",
			"Contact",
			"Close Light Mode",
			"Close Dark Mode",
		],
		title: "Variant",
		type: ControlType.Enum,
	},
});
addFonts(FramerQHnTUzDag, [...NavItemFonts]);

// virtual:navigation
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "eRN9aHEW5",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"1763929c89cf4969ad190da187fc25ea516fa82b7cf163cf1161896117bee1d5"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default2, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders NavigationFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"1763929c89cf4969ad190da187fc25ea516fa82b7cf163cf1161896117bee1d5"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default2}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default2);
var navigation_default = ComponentWithRoot;
export { navigation_default as default };
