// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 1763929c89cf4969 "Patrick McKowen", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * num?: string // Num
}} Props

 */
import { className, css, fonts } from "./chunks/chunk-T6M5HMBG.js";
import { routes } from "./chunks/chunk-IRNZKG45.js";

// virtual:numbered-bullet
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/s4rEW57WBF8f2GHaAnHh/XvagQPQyCkdba24LkTdi/kd78L2atH.js
import { jsx as _jsx } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	RichText,
	useConstant,
	useIsOnFramerCanvas,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
var cycleOrder = ["XUuFakKbu"];
var serializationHash = "framer-YF50c";
var variantClassNames = {
	XUuFakKbu: "framer-v-9yek4t",
};
var transitions = {
	default: {
		damping: 60,
		delay: 0,
		mass: 1,
		stiffness: 500,
		type: "spring",
	},
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition =
		value !== null && value !== void 0 ? value : config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var getProps = ({ height, id, num, width, ...props }) => {
	var _ref;
	return {
		...props,
		xaxz1Pli8:
			(_ref = num !== null && num !== void 0 ? num : props.xaxz1Pli8) !==
				null && _ref !== void 0
				? _ref
				: "1",
	};
};
var createLayoutDependency = (props, variants) =>
	variants.join("-") + props.layoutDependency;
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const { activeLocale, setLocale } = useLocaleInfo();
	const {
		style,
		className: className2,
		layoutId,
		variant,
		xaxz1Pli8,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		gestureVariant,
		setGestureState,
		setVariant,
		transition,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "XUuFakKbu",
		transitions,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const isOnCanvas = useIsOnFramerCanvas();
	const initialVariant = useConstant(() => variant);
	const ref1 = React.useRef(null);
	const defaultLayoutId = React.useId();
	const sharedStyleClassNames = [className];
	return (
		<LayoutGroup
			id={layoutId !== null && layoutId !== void 0 ? layoutId : defaultLayoutId}
		>
			<Transition value={transition}>
				<motion.div
					{...restProps}
					animate={variants}
					className={cx(
						serializationHash,
						...sharedStyleClassNames,
						"framer-9yek4t",
						className2,
						classNames,
					)}
					data-framer-name={"Variant 1"}
					initial={isOnCanvas ? variant : initialVariant}
					layoutDependency={layoutDependency}
					layoutId={"XUuFakKbu"}
					onHoverEnd={() =>
						setGestureState({
							isHovered: false,
						})
					}
					onHoverStart={() =>
						setGestureState({
							isHovered: true,
						})
					}
					onTap={() =>
						setGestureState({
							isPressed: false,
						})
					}
					onTapCancel={() =>
						setGestureState({
							isPressed: false,
						})
					}
					onTapStart={() =>
						setGestureState({
							isPressed: true,
						})
					}
					ref={ref !== null && ref !== void 0 ? ref : ref1}
					style={{
						...style,
					}}
				>
					<motion.div
						className={"framer-e05ru1"}
						data-framer-name={"Number"}
						layoutDependency={layoutDependency}
						layoutId={"oh8BJFL3g"}
						style={{
							borderBottomLeftRadius: 100,
							borderBottomRightRadius: 100,
							borderTopLeftRadius: 100,
							borderTopRightRadius: 100,
						}}
					>
						<RichText
							__fromCanvasComponent={true}
							className={"framer-weg8p1"}
							layoutDependency={layoutDependency}
							layoutId={"FW7Qpud_R"}
							style={{
								"--extracted-r6o4lv":
									"var(--token-c3ec4201-05df-4ec8-93fe-fe8f0231d7fb, rgba(0, 0, 0, 0.75))",
								"--framer-link-text-color": "rgb(0, 153, 255)",
								"--framer-link-text-decoration": "underline",
							}}
							text={xaxz1Pli8}
							verticalAlignment={"top"}
							withExternalLayout={true}
						>
							<React.Fragment>
								<motion.p
									className={"framer-styles-preset-1f40k0m"}
									data-styles-preset={"YYoNxvhFL"}
									style={{
										"--framer-text-color":
											"var(--extracted-r6o4lv, var(--token-c3ec4201-05df-4ec8-93fe-fe8f0231d7fb, rgba(0, 0, 0, 0.75)))",
									}}
								>
									{"1"}
								</motion.p>
							</React.Fragment>
						</RichText>
					</motion.div>
				</motion.div>
			</Transition>
		</LayoutGroup>
	);
});
var css2 = [
	'.framer-YF50c[data-border="true"]::after, .framer-YF50c [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; pointer-events: none; }',
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-YF50c.framer-t205mi, .framer-YF50c .framer-t205mi { display: block; }",
	".framer-YF50c.framer-9yek4t { align-content: center; align-items: center; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: 24px; justify-content: center; overflow: hidden; padding: 0px 0px 0px 0px; position: relative; width: 24px; }",
	".framer-YF50c .framer-e05ru1 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: 24px; justify-content: center; left: calc(50.00000000000002% - 24px / 2); overflow: hidden; padding: 0px 0px 0px 0px; position: absolute; top: calc(50.00000000000002% - 24px / 2); width: 24px; will-change: var(--framer-will-change-override, transform); z-index: 1; }",
	".framer-YF50c .framer-weg8p1 { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
	"@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-YF50c.framer-9yek4t, .framer-YF50c .framer-e05ru1 { gap: 0px; } .framer-YF50c.framer-9yek4t > *, .framer-YF50c .framer-e05ru1 > * { margin: 0px; margin-left: calc(10px / 2); margin-right: calc(10px / 2); } .framer-YF50c.framer-9yek4t > :first-child, .framer-YF50c .framer-e05ru1 > :first-child { margin-left: 0px; } .framer-YF50c.framer-9yek4t > :last-child, .framer-YF50c .framer-e05ru1 > :last-child { margin-right: 0px; } }",
	...css,
];
var Framerkd78L2atH = withCSS(Component, css2, "framer-YF50c");
var stdin_default = Framerkd78L2atH;
Framerkd78L2atH.displayName = "Numbered Bullet";
Framerkd78L2atH.defaultProps = {
	height: 24,
	width: 24,
};
addPropertyControls(Framerkd78L2atH, {
	xaxz1Pli8: {
		defaultValue: "1",
		displayTextArea: false,
		title: "Num",
		type: ControlType.String,
	},
});
addFonts(Framerkd78L2atH, [...fonts]);

// virtual:numbered-bullet
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"1763929c89cf4969ad190da187fc25ea516fa82b7cf163cf1161896117bee1d5"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders NumberedBulletFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"1763929c89cf4969ad190da187fc25ea516fa82b7cf163cf1161896117bee1d5"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var numbered_bullet_default = ComponentWithRoot;
export { numbered_bullet_default as default };
