// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 1763929c89cf4969 "Patrick McKowen", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
}} Props

 */
import { stdin_default } from "./chunks/chunk-WXUWL4WN.js";
import { routes } from "./chunks/chunk-IRNZKG45.js";

// virtual:page-background
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/DpBbn6pVLwiBaFJbNQoj/0ts9YF5mn77KsWJK298t/aR_X40FXd.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ComponentViewportProvider,
	ControlType,
	cx,
	getFonts,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
var ShaderGradientFonts = getFonts(stdin_default);
var cycleOrder = [
	"xjrSxQbyx",
	"af26P6cqb",
	"cxTxR8w7X",
	"r8hu8NVX6",
	"F_MuT09aC",
];
var serializationHash = "framer-wGJfJ";
var variantClassNames = {
	af26P6cqb: "framer-v-otdt2e",
	cxTxR8w7X: "framer-v-dsqzzx",
	F_MuT09aC: "framer-v-2e70bh",
	r8hu8NVX6: "framer-v-ozxsty",
	xjrSxQbyx: "framer-v-15t9wf",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants === null || variants === void 0
		? void 0
		: variants.forEach(
				(variant) =>
					variant && Object.assign(nextOverrides, overrides[variant]),
			);
	return nextOverrides;
}
var transition1 = {
	delay: 0,
	duration: 1,
	ease: [0.44, 0, 0.56, 1],
	type: "tween",
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition =
		value !== null && value !== void 0 ? value : config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion(React.Fragment);
var humanReadableVariantMap = {
	"M Orange Green": "af26P6cqb",
	"M Red Blue": "r8hu8NVX6",
	"Orange Green": "xjrSxQbyx",
	"Red Blue": "cxTxR8w7X",
	Cameo: "F_MuT09aC",
};
var getProps = ({ height, id, width, ...props }) => {
	var _humanReadableVariantMap_props_variant, _ref;
	return {
		...props,
		variant:
			(_ref =
				(_humanReadableVariantMap_props_variant =
					humanReadableVariantMap[props.variant]) !== null &&
				_humanReadableVariantMap_props_variant !== void 0
					? _humanReadableVariantMap_props_variant
					: props.variant) !== null && _ref !== void 0
				? _ref
				: "xjrSxQbyx",
	};
};
var createLayoutDependency = (props, variants) =>
	variants.join("-") + props.layoutDependency;
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const { activeLocale, setLocale } = useLocaleInfo();
	const { style, className, layoutId, variant, ...restProps } = getProps(props);
	const {
		baseVariant,
		classNames,
		gestureVariant,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "xjrSxQbyx",
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const ref1 = React.useRef(null);
	const defaultLayoutId = React.useId();
	const sharedStyleClassNames = [];
	const componentViewport = useComponentViewport();
	return (
		<LayoutGroup
			id={layoutId !== null && layoutId !== void 0 ? layoutId : defaultLayoutId}
		>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.div
						{...restProps}
						className={cx(
							serializationHash,
							...sharedStyleClassNames,
							"framer-15t9wf",
							className,
							classNames,
						)}
						data-framer-name={"Orange Green"}
						layoutDependency={layoutDependency}
						layoutId={"xjrSxQbyx"}
						onHoverEnd={() =>
							setGestureState({
								isHovered: false,
							})
						}
						onHoverStart={() =>
							setGestureState({
								isHovered: true,
							})
						}
						onTap={() =>
							setGestureState({
								isPressed: false,
							})
						}
						onTapCancel={() =>
							setGestureState({
								isPressed: false,
							})
						}
						onTapStart={() =>
							setGestureState({
								isPressed: true,
							})
						}
						ref={ref !== null && ref !== void 0 ? ref : ref1}
						style={{
							opacity: 1,
							...style,
						}}
						variants={{
							r8hu8NVX6: {
								opacity: 0.4,
							},
						}}
						{...addPropertyOverrides(
							{
								af26P6cqb: {
									"data-framer-name": "M Orange Green",
								},
								cxTxR8w7X: {
									"data-framer-name": "Red Blue",
								},
								F_MuT09aC: {
									"data-framer-name": "Cameo",
								},
								r8hu8NVX6: {
									"data-framer-name": "M Red Blue",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion.div
							className={"framer-1tarkcy"}
							data-framer-name={"Mask"}
							layoutDependency={layoutDependency}
							layoutId={"cyJ3k0Chm"}
							style={{
								background:
									'linear-gradient(180deg, rgba(247, 247, 247, 0) 0%, var(--token-68366ab7-03aa-46f4-96ae-993f4367e005, rgb(247, 247, 247)) /* {"name":"White BG Primary"} */ 85.72307692307693%)',
							}}
							variants={{
								cxTxR8w7X: {
									background:
										'radial-gradient(50% 50% at 50% 50%, rgba(247, 247, 247, 0) 0%, var(--token-68366ab7-03aa-46f4-96ae-993f4367e005, rgb(247, 247, 247)) /* {"name":"White BG Primary"} */ 100%)',
								},
								F_MuT09aC: {
									background:
										'linear-gradient(180deg, rgba(33, 30, 36, 0) 0%, var(--token-99cbe996-90d5-49a4-a63d-ca8b81e97bf8, rgb(32, 30, 35)) /* {"name":"Cameo BG"} */ 100%)',
								},
								r8hu8NVX6: {
									background:
										'linear-gradient(180deg, rgba(247, 247, 247, 0) 0%, var(--token-68366ab7-03aa-46f4-96ae-993f4367e005, rgb(247, 247, 247)) /* {"name":"White BG Primary"} */ 85%)',
								},
							}}
						/>
						<ComponentViewportProvider>
							<motion.div
								className={"framer-2sxxf0-container"}
								layoutDependency={layoutDependency}
								layoutId={"rxTATkTk6-container"}
								style={{
									opacity: 0.7,
								}}
								variants={{
									af26P6cqb: {
										opacity: 1,
									},
									cxTxR8w7X: {
										opacity: 0.5,
									},
									F_MuT09aC: {
										opacity: 0.2,
									},
									r8hu8NVX6: {
										opacity: 1,
									},
								}}
							>
								{_jsx(stdin_default, {
									activeTab: "View",
									animate: "on",
									brightness: 1.2,
									cameraAngle: {
										cAzimuthAngle: 0,
										cPolarAngle: 90,
									},
									cameraZoom: 1,
									cDistance: 2,
									color1: "rgb(255, 198, 140)",
									color2: "rgb(128, 255, 232)",
									color3: "rgb(146, 152, 252)",
									control: "props",
									envPreset: "lobby",
									grain: "off",
									height: "100%",
									id: "rxTATkTk6",
									layoutId: "rxTATkTk6",
									lightType: "3d",
									noise: {
										uDensity: 1.5,
										uStrength: 2.5,
									},
									performantOnCanvas: true,
									pixelDensity: 1,
									pointerEvents: "none",
									position: {
										positionX: 0,
										positionY: 0,
										positionZ: 0,
									},
									reflection: 1,
									rotation: {
										rotationX: 0,
										rotationY: 0,
										rotationZ: 0,
									},
									shader: "defaults",
									style: {
										height: "100%",
										width: "100%",
									},
									toggleAxis: false,
									type: "waterPlane",
									uAmplitude: 0.1,
									urlString: "",
									uSpeed: 0.1,
									uTime: 0,
									width: "100%",
									zoomOut: false,
									...addPropertyOverrides(
										{
											af26P6cqb: {
												cDistance: 7,
											},
											cxTxR8w7X: {
												activeTab: "Colors",
												color1: "rgb(144, 189, 55)",
												color2: "rgb(237, 42, 36)",
												color3: "rgb(20, 2, 202)",
											},
											F_MuT09aC: {
												activeTab: "Colors",
												color1: "rgb(240, 10, 186)",
												color2: "rgb(128, 54, 224)",
												color3: "rgb(0, 173, 87)",
												performantOnCanvas: false,
											},
											r8hu8NVX6: {
												activeTab: "Colors",
												cDistance: 4,
												color1: "rgb(144, 189, 55)",
												color2: "rgb(237, 42, 36)",
												color3: "rgb(20, 2, 202)",
											},
										},
										baseVariant,
										gestureVariant,
									),
								})}
							</motion.div>
						</ComponentViewportProvider>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-wGJfJ.framer-sedlqi, .framer-wGJfJ .framer-sedlqi { display: block; }",
	".framer-wGJfJ.framer-15t9wf { align-content: center; align-items: center; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: 800px; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 1878px; }",
	".framer-wGJfJ .framer-1tarkcy { flex: none; height: calc(var(--framer-viewport-height, 100vh) * 1); left: 0px; overflow: hidden; position: absolute; top: 0px; width: 100%; z-index: 1; }",
	".framer-wGJfJ .framer-2sxxf0-container { flex: none; height: calc(var(--framer-viewport-height, 100vh) * 1); left: calc(50.00000000000002% - 100% / 2); position: absolute; top: 0px; width: 100%; z-index: 0; }",
	"@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-wGJfJ.framer-15t9wf { gap: 0px; } .framer-wGJfJ.framer-15t9wf > * { margin: 0px; margin-left: calc(10px / 2); margin-right: calc(10px / 2); } .framer-wGJfJ.framer-15t9wf > :first-child { margin-left: 0px; } .framer-wGJfJ.framer-15t9wf > :last-child { margin-right: 0px; } }",
	".framer-wGJfJ.framer-v-otdt2e.framer-15t9wf, .framer-wGJfJ.framer-v-ozxsty.framer-15t9wf { width: 600px; }",
	".framer-wGJfJ.framer-v-dsqzzx .framer-1tarkcy { bottom: 0px; height: 150%; top: unset; }",
	".framer-wGJfJ.framer-v-dsqzzx .framer-2sxxf0-container { height: 100%; }",
];
var FrameraR_X40FXd = withCSS(Component, css, "framer-wGJfJ");
var stdin_default2 = FrameraR_X40FXd;
FrameraR_X40FXd.displayName = "Page Background";
FrameraR_X40FXd.defaultProps = {
	height: 800,
	width: 1878,
};
addPropertyControls(FrameraR_X40FXd, {
	variant: {
		options: ["xjrSxQbyx", "af26P6cqb", "cxTxR8w7X", "r8hu8NVX6", "F_MuT09aC"],
		optionTitles: [
			"Orange Green",
			"M Orange Green",
			"Red Blue",
			"M Red Blue",
			"Cameo",
		],
		title: "Variant",
		type: ControlType.Enum,
	},
});
addFonts(
	FrameraR_X40FXd,
	[
		{
			explicitInter: true,
			fonts: [],
		},
		...ShaderGradientFonts,
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:page-background
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "r8hu8NVX6",
	xl: "cxTxR8w7X",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"1763929c89cf4969ad190da187fc25ea516fa82b7cf163cf1161896117bee1d5"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default2, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders PageBackgroundFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"1763929c89cf4969ad190da187fc25ea516fa82b7cf163cf1161896117bee1d5"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default2}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default2);
var page_background_default = ComponentWithRoot;
export { page_background_default as default };
