// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 1763929c89cf4969 "Patrick McKowen", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Dark Mode' | 'Light Mode' | 'Dark Mode Large' | 'Light Mode Large' | 'M Dark Mode' // Variant
 * image?: {src: string, srcSet?: string, alt?: string} // Image
}} Props

 */
import { routes } from "./chunks/chunk-IRNZKG45.js";

// virtual:phone-mockup-dark-border
import { Fragment } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/6M64O7ieO3wCwwB63rPT/lVJAaAP8ib9HvWfcLzfq/z_7JCbhte.js
import { jsx as _jsx } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	Image,
	useConstant,
	useIsOnFramerCanvas,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, MotionConfigContext } from "unframer";
import * as React from "react";
var cycleOrder = [
	"HxKhZKvVO",
	"OkTQBBewL",
	"ClB1WfBEE",
	"UkEMT_Keh",
	"VqEdWVFeZ",
];
var serializationHash = "framer-oILUr";
var variantClassNames = {
	ClB1WfBEE: "framer-v-14p0f5v",
	HxKhZKvVO: "framer-v-2vhe66",
	OkTQBBewL: "framer-v-cdchcn",
	UkEMT_Keh: "framer-v-a5t8xb",
	VqEdWVFeZ: "framer-v-1nvx785",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants === null || variants === void 0
		? void 0
		: variants.forEach(
				(variant) =>
					variant && Object.assign(nextOverrides, overrides[variant]),
			);
	return nextOverrides;
}
var transitions = {
	default: {
		damping: 60,
		delay: 0,
		mass: 1,
		stiffness: 500,
		type: "spring",
	},
};
var toResponsiveImage = (value) => {
	if (
		typeof value === "object" &&
		value !== null &&
		typeof value.src === "string"
	) {
		return value;
	}
	return typeof value === "string"
		? {
				src: value,
			}
		: void 0;
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition =
		value !== null && value !== void 0 ? value : config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var humanReadableVariantMap = {
	"Dark Mode Large": "ClB1WfBEE",
	"Dark Mode": "HxKhZKvVO",
	"Light Mode Large": "UkEMT_Keh",
	"Light Mode": "OkTQBBewL",
	"M Dark Mode": "VqEdWVFeZ",
};
var getProps = ({ height, id, image, width, ...props }) => {
	var _humanReadableVariantMap_props_variant, _ref;
	return {
		...props,
		variant:
			(_ref =
				(_humanReadableVariantMap_props_variant =
					humanReadableVariantMap[props.variant]) !== null &&
				_humanReadableVariantMap_props_variant !== void 0
					? _humanReadableVariantMap_props_variant
					: props.variant) !== null && _ref !== void 0
				? _ref
				: "HxKhZKvVO",
		ZRrNkyTY8: image !== null && image !== void 0 ? image : props.ZRrNkyTY8,
	};
};
var createLayoutDependency = (props, variants) =>
	variants.join("-") + props.layoutDependency;
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const { activeLocale, setLocale } = useLocaleInfo();
	const { style, className, layoutId, variant, ZRrNkyTY8, ...restProps } =
		getProps(props);
	const {
		baseVariant,
		classNames,
		gestureVariant,
		setGestureState,
		setVariant,
		transition,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "HxKhZKvVO",
		transitions,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const isOnCanvas = useIsOnFramerCanvas();
	const initialVariant = useConstant(() => variant);
	const ref1 = React.useRef(null);
	const defaultLayoutId = React.useId();
	const sharedStyleClassNames = [];
	return (
		<LayoutGroup
			id={layoutId !== null && layoutId !== void 0 ? layoutId : defaultLayoutId}
		>
			<Transition value={transition}>
				<Image
					{...restProps}
					animate={variants}
					background={{
						alt: "",
						fit: "fill",
						intrinsicHeight: 812,
						intrinsicWidth: 375,
						pixelHeight: 1624,
						pixelWidth: 750,
						sizes: "min(375px, 100vw)",
						...toResponsiveImage(ZRrNkyTY8),
					}}
					className={cx(
						serializationHash,
						...sharedStyleClassNames,
						"framer-2vhe66",
						className,
						classNames,
					)}
					data-framer-name={"Dark Mode"}
					initial={isOnCanvas ? variant : initialVariant}
					layoutDependency={layoutDependency}
					layoutId={"HxKhZKvVO"}
					onHoverEnd={() =>
						setGestureState({
							isHovered: false,
						})
					}
					onHoverStart={() =>
						setGestureState({
							isHovered: true,
						})
					}
					onTap={() =>
						setGestureState({
							isPressed: false,
						})
					}
					onTapCancel={() =>
						setGestureState({
							isPressed: false,
						})
					}
					onTapStart={() =>
						setGestureState({
							isPressed: true,
						})
					}
					ref={ref !== null && ref !== void 0 ? ref : ref1}
					style={{
						borderBottomLeftRadius: 24,
						borderBottomRightRadius: 24,
						borderTopLeftRadius: 24,
						borderTopRightRadius: 24,
						boxShadow:
							"0px 0px 0px 4px rgb(0, 0, 0), 0px 0.7113342898827977px 1.280401721789036px -0.4px rgba(0, 0, 0, 0.04059), 0px 1.9371521717053837px 3.4868739090696907px -0.8px rgba(0, 0, 0, 0.04161), 0px 4.253285051195417px 7.655913092151751px -1.2px rgba(0, 0, 0, 0.04354), 0px 9.4413216807344px 16.994379025321923px -1.6px rgba(0, 0, 0, 0.04787), 0px 24px 43.2px -2px rgba(0, 0, 0, 0.06)",
						...style,
					}}
					variants={{
						ClB1WfBEE: {
							borderBottomLeftRadius: 28,
							borderBottomRightRadius: 28,
							borderTopLeftRadius: 28,
							borderTopRightRadius: 28,
							boxShadow:
								"0px 0px 0px 8px rgb(0, 0, 0), 0px 0.7113342898827977px 1.280401721789036px 0px rgba(0, 0, 0, 0.00741), 0px 1.9371521717053837px 3.4868739090696907px 0px rgba(0, 0, 0, 0.02018), 0px 4.253285051195417px 7.655913092151751px 0px rgba(0, 0, 0, 0.04431), 0px 9.4413216807344px 16.994379025321923px 0px rgba(0, 0, 0, 0.09835), 0px 24px 43.2px 0px rgba(0, 0, 0, 0.25)",
						},
						OkTQBBewL: {
							boxShadow:
								"0px 0px 0px 4px rgb(255, 255, 255), 0px 0.7113342898827977px 1.280401721789036px -0.4px rgba(0, 0, 0, 0.04059), 0px 1.9371521717053837px 3.4868739090696907px -0.8px rgba(0, 0, 0, 0.04161), 0px 4.253285051195417px 7.655913092151751px -1.2px rgba(0, 0, 0, 0.04354), 0px 9.4413216807344px 16.994379025321923px -1.6px rgba(0, 0, 0, 0.04787), 0px 24px 43.2px -2px rgba(0, 0, 0, 0.06)",
						},
						UkEMT_Keh: {
							borderBottomLeftRadius: 28,
							borderBottomRightRadius: 28,
							borderTopLeftRadius: 28,
							borderTopRightRadius: 28,
							boxShadow:
								'0px 0px 0px 8px var(--token-464632b9-70af-47b9-93b4-8eb38f80e40f, rgb(255, 255, 255)) /* {"name":"White"} */, 0px 0.7113342898827977px 1.280401721789036px 0px rgba(0, 0, 0, 0.00296), 0px 1.9371521717053837px 3.4868739090696907px 0px rgba(0, 0, 0, 0.00807), 0px 4.253285051195417px 7.655913092151751px 0px rgba(0, 0, 0, 0.01772), 0px 9.4413216807344px 16.994379025321923px 0px rgba(0, 0, 0, 0.03934), 0px 24px 43.2px 0px rgba(0, 0, 0, 0.1)',
						},
						VqEdWVFeZ: {
							boxShadow:
								"0px 0px 0px 4px rgb(0, 0, 0), 0px 0.7961918735236395px 1.4331453723425511px 0px rgba(0, 0, 0, 0.00398), 0px 2.414506143104518px 4.346111057588132px 0px rgba(0, 0, 0, 0.01207), 0px 6.382653521484461px 11.48877633867203px 0px rgba(0, 0, 0, 0.03191), 0px 20px 36px 0px rgba(0, 0, 0, 0.1)",
						},
					}}
					{...addPropertyOverrides(
						{
							ClB1WfBEE: {
								"data-framer-name": "Dark Mode Large",
							},
							OkTQBBewL: {
								"data-framer-name": "Light Mode",
							},
							UkEMT_Keh: {
								"data-framer-name": "Light Mode Large",
							},
							VqEdWVFeZ: {
								"data-framer-name": "M Dark Mode",
							},
						},
						baseVariant,
						gestureVariant,
					)}
				/>
			</Transition>
		</LayoutGroup>
	);
});
var css = [
	'.framer-oILUr[data-border="true"]::after, .framer-oILUr [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; pointer-events: none; }',
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-oILUr.framer-l8hvc0, .framer-oILUr .framer-l8hvc0 { display: block; }",
	".framer-oILUr.framer-2vhe66 { height: 812px; overflow: visible; position: relative; width: 375px; }",
	".framer-oILUr.framer-v-cdchcn.framer-2vhe66, .framer-oILUr.framer-v-14p0f5v.framer-2vhe66, .framer-oILUr.framer-v-a5t8xb.framer-2vhe66, .framer-oILUr.framer-v-1nvx785.framer-2vhe66 { aspect-ratio: 0.4618226600985222 / 1; height: var(--framer-aspect-ratio-supported, 812px); }",
];
var Framerz_7JCbhte = withCSS(Component, css, "framer-oILUr");
var stdin_default = Framerz_7JCbhte;
Framerz_7JCbhte.displayName = "Phone Mockup Dark Border";
Framerz_7JCbhte.defaultProps = {
	height: 812,
	width: 375,
};
addPropertyControls(Framerz_7JCbhte, {
	variant: {
		options: ["HxKhZKvVO", "OkTQBBewL", "ClB1WfBEE", "UkEMT_Keh", "VqEdWVFeZ"],
		optionTitles: [
			"Dark Mode",
			"Light Mode",
			"Dark Mode Large",
			"Light Mode Large",
			"M Dark Mode",
		],
		title: "Variant",
		type: ControlType.Enum,
	},
	ZRrNkyTY8: {
		title: "Image",
		type: ControlType.ResponsiveImage,
	},
});
addFonts(Framerz_7JCbhte, []);

// virtual:phone-mockup-dark-border
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "VqEdWVFeZ",
	xl: "HxKhZKvVO",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"1763929c89cf4969ad190da187fc25ea516fa82b7cf163cf1161896117bee1d5"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders PhoneMockupDarkBorderFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"1763929c89cf4969ad190da187fc25ea516fa82b7cf163cf1161896117bee1d5"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var phone_mockup_dark_border_default = ComponentWithRoot;
export { phone_mockup_dark_border_default as default };
