// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 1763929c89cf4969 "Patrick McKowen", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Default' | 'Playing' // Variant
 * file?: string // File
}} Props

 */
import { Video } from "./chunks/chunk-F3PUWBZ4.js";
import { Video as Video2 } from "./chunks/chunk-4JZSFPWQ.js";
import "./chunks/chunk-AWZNHXD6.js";
import { routes } from "./chunks/chunk-IRNZKG45.js";

// virtual:phone-video
import { Fragment } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/88qmYogBVYRuS5II6mMq/bf60QtFeHv1jelG79Sf3/Xwf5xDafR.js
import { jsx as _jsx } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	getFonts,
	getPropertyControls,
	useConstant,
	useIsOnFramerCanvas,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
var VideoFonts = getFonts(Video);
var Video1Controls = getPropertyControls(Video2);
var cycleOrder = ["KkWQ_c0T2", "wy51qmbFT"];
var serializationHash = "framer-JZs7V";
var variantClassNames = {
	KkWQ_c0T2: "framer-v-1uc65i2",
	wy51qmbFT: "framer-v-z6l9bv",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants === null || variants === void 0
		? void 0
		: variants.forEach(
				(variant) =>
					variant && Object.assign(nextOverrides, overrides[variant]),
			);
	return nextOverrides;
}
var transitions = {
	default: {
		damping: 60,
		delay: 0,
		mass: 1,
		stiffness: 500,
		type: "spring",
	},
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition =
		value !== null && value !== void 0 ? value : config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var humanReadableVariantMap = {
	Default: "KkWQ_c0T2",
	Playing: "wy51qmbFT",
};
var getProps = ({ file, height, id, width, ...props }) => {
	var _humanReadableVariantMap_props_variant, _ref;
	return {
		...props,
		dj4_hqYv_: file !== null && file !== void 0 ? file : props.dj4_hqYv_,
		variant:
			(_ref =
				(_humanReadableVariantMap_props_variant =
					humanReadableVariantMap[props.variant]) !== null &&
				_humanReadableVariantMap_props_variant !== void 0
					? _humanReadableVariantMap_props_variant
					: props.variant) !== null && _ref !== void 0
				? _ref
				: "KkWQ_c0T2",
	};
};
var createLayoutDependency = (props, variants) =>
	variants.join("-") + props.layoutDependency;
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const { activeLocale, setLocale } = useLocaleInfo();
	const { style, className, layoutId, variant, dj4_hqYv_, ...restProps } =
		getProps(props);
	const {
		baseVariant,
		classNames,
		gestureVariant,
		setGestureState,
		setVariant,
		transition,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "KkWQ_c0T2",
		transitions,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const isOnCanvas = useIsOnFramerCanvas();
	const initialVariant = useConstant(() => variant);
	const ref1 = React.useRef(null);
	const defaultLayoutId = React.useId();
	const sharedStyleClassNames = [];
	return (
		<LayoutGroup
			id={layoutId !== null && layoutId !== void 0 ? layoutId : defaultLayoutId}
		>
			<Transition value={transition}>
				<motion.div
					{...restProps}
					animate={variants}
					className={cx(
						serializationHash,
						...sharedStyleClassNames,
						"framer-1uc65i2",
						className,
						classNames,
					)}
					data-framer-name={"Default"}
					initial={isOnCanvas ? variant : initialVariant}
					layoutDependency={layoutDependency}
					layoutId={"KkWQ_c0T2"}
					onHoverEnd={() =>
						setGestureState({
							isHovered: false,
						})
					}
					onHoverStart={() =>
						setGestureState({
							isHovered: true,
						})
					}
					onTap={() =>
						setGestureState({
							isPressed: false,
						})
					}
					onTapCancel={() =>
						setGestureState({
							isPressed: false,
						})
					}
					onTapStart={() =>
						setGestureState({
							isPressed: true,
						})
					}
					ref={ref !== null && ref !== void 0 ? ref : ref1}
					style={{
						borderBottomLeftRadius: 24,
						borderBottomRightRadius: 24,
						borderTopLeftRadius: 24,
						borderTopRightRadius: 24,
						boxShadow:
							'0px 0px 0px 4px var(--token-464632b9-70af-47b9-93b4-8eb38f80e40f, rgb(255, 255, 255)) /* {"name":"White"} */, 0px 0.7113342898827977px 1.280401721789036px -0.4px rgba(0, 0, 0, 0.04059), 0px 1.9371521717053837px 3.4868739090696907px -0.8px rgba(0, 0, 0, 0.04161), 0px 4.253285051195417px 7.655913092151751px -1.2px rgba(0, 0, 0, 0.04354), 0px 9.4413216807344px 16.994379025321923px -1.6px rgba(0, 0, 0, 0.04787), 0px 24px 43.2px -2px rgba(0, 0, 0, 0.06)',
						...style,
					}}
					{...addPropertyOverrides(
						{
							wy51qmbFT: {
								"data-framer-name": "Playing",
							},
						},
						baseVariant,
						gestureVariant,
					)}
				>
					<motion.div
						className={"framer-19s46vk-container"}
						layoutDependency={layoutDependency}
						layoutId={"rzR_BStf6-container"}
					>
						<Video
							backgroundColor={"rgba(0, 0, 0, 0)"}
							borderRadius={4}
							bottomLeftRadius={4}
							bottomRightRadius={4}
							controls={false}
							height={"100%"}
							id={"rzR_BStf6"}
							isMixedBorderRadius={false}
							layoutId={"rzR_BStf6"}
							loop={true}
							muted={true}
							objectFit={"cover"}
							playing={false}
							posterEnabled={false}
							srcFile={dj4_hqYv_}
							srcType={"Upload"}
							srcUrl={
								"https://assets.mixkit.co/videos/preview/mixkit-ice-cream-glass-of-red-soda-5094-small.mp4"
							}
							startTime={0}
							style={{
								height: "100%",
								width: "100%",
							}}
							topLeftRadius={4}
							topRightRadius={4}
							volume={25}
							width={"100%"}
							{...addPropertyOverrides(
								{
									wy51qmbFT: {
										playing: true,
									},
								},
								baseVariant,
								gestureVariant,
							)}
						/>
					</motion.div>
				</motion.div>
			</Transition>
		</LayoutGroup>
	);
});
var css = [
	'.framer-JZs7V[data-border="true"]::after, .framer-JZs7V [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; pointer-events: none; }',
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-JZs7V.framer-7mkgx1, .framer-JZs7V .framer-7mkgx1 { display: block; }",
	".framer-JZs7V.framer-1uc65i2 { align-content: center; align-items: center; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: hidden; padding: 0px 0px 0px 0px; position: relative; width: 294px; will-change: var(--framer-will-change-override, transform); }",
	".framer-JZs7V .framer-19s46vk-container { aspect-ratio: 0.4618226600985222 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 637px); position: relative; width: 100%; }",
	"@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-JZs7V.framer-1uc65i2 { gap: 0px; } .framer-JZs7V.framer-1uc65i2 > * { margin: 0px; margin-left: calc(10px / 2); margin-right: calc(10px / 2); } .framer-JZs7V.framer-1uc65i2 > :first-child { margin-left: 0px; } .framer-JZs7V.framer-1uc65i2 > :last-child { margin-right: 0px; } }",
];
var FramerXwf5xDafR = withCSS(Component, css, "framer-JZs7V");
var stdin_default = FramerXwf5xDafR;
FramerXwf5xDafR.displayName = "Phone Video";
FramerXwf5xDafR.defaultProps = {
	height: 636.5,
	width: 294,
};
addPropertyControls(FramerXwf5xDafR, {
	variant: {
		options: ["KkWQ_c0T2", "wy51qmbFT"],
		optionTitles: ["Default", "Playing"],
		title: "Variant",
		type: ControlType.Enum,
	},
	dj4_hqYv_: (Video1Controls === null || Video1Controls === void 0
		? void 0
		: Video1Controls["srcFile"]) && {
		...Video1Controls["srcFile"],
		__defaultAssetReference: "",
		description: void 0,
		hidden: void 0,
		title: "File",
	},
});
addFonts(FramerXwf5xDafR, [...VideoFonts]);

// virtual:phone-video
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"1763929c89cf4969ad190da187fc25ea516fa82b7cf163cf1161896117bee1d5"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders PhoneVideoFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"1763929c89cf4969ad190da187fc25ea516fa82b7cf163cf1161896117bee1d5"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var phone_video_default = ComponentWithRoot;
export { phone_video_default as default };
