// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 1763929c89cf4969 "Patrick McKowen", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Large' | 'Mobile' // Variant
 * image?: {src: string, srcSet?: string, alt?: string} // Image
 * mobileImage?: {src: string, srcSet?: string, alt?: string} // Mobile Image
 * icon?: {src: string, srcSet?: string, alt?: string} // Icon
 * headline?: string // Headline
 * link?: string // Link
 * padding?: number // Padding
 * gap?: number // Gap
}} Props

 */
import { stdin_default } from "./chunks/chunk-JIOE72XF.js";
import { withSlideUpOnHover } from "./chunks/chunk-VSMRQKYW.js";
import { routes } from "./chunks/chunk-IRNZKG45.js";

// virtual:project-card
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/b98ZsTiiJ8BwTLUku7ky/WlYR5jWXUIwpRoFj6e6K/LDHHFyFz0.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ComponentViewportProvider,
	ControlType,
	cx,
	getFonts,
	Image,
	Link,
	RichText,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
var LinkButtonFonts = getFonts(stdin_default);
var MotionAWithSlideUpOnHover = withSlideUpOnHover(motion.a);
var enabledGestures = {
	SsskJBqHW: {
		hover: true,
	},
};
var cycleOrder = ["SsskJBqHW", "jI8WPXyBN"];
var serializationHash = "framer-weyW7";
var variantClassNames = {
	jI8WPXyBN: "framer-v-1t34i5y",
	SsskJBqHW: "framer-v-dm1mpm",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	damping: 60,
	delay: 0,
	mass: 1,
	stiffness: 500,
	type: "spring",
};
var toResponsiveImage = (value) => {
	if (
		typeof value === "object" &&
		value !== null &&
		typeof value.src === "string"
	) {
		return value;
	}
	return typeof value === "string"
		? {
				src: value,
			}
		: void 0;
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion(React.Fragment);
var humanReadableVariantMap = {
	Large: "SsskJBqHW",
	Mobile: "jI8WPXyBN",
};
var getProps = ({
	gap,
	headline,
	height,
	icon,
	id,
	image,
	link,
	mobileImage,
	padding,
	width,
	...props
}) => {
	return {
		...props,
		aoKN1fgc1: mobileImage ??
			props.aoKN1fgc1 ?? {
				src: "https://framerusercontent.com/images/pjzjj6MnILAx2z8KB4r813cIIQ.png?scale-down-to=1024",
				srcSet:
					"https://framerusercontent.com/images/pjzjj6MnILAx2z8KB4r813cIIQ.png?scale-down-to=512 512w,https://framerusercontent.com/images/pjzjj6MnILAx2z8KB4r813cIIQ.png?scale-down-to=1024 1024w,https://framerusercontent.com/images/pjzjj6MnILAx2z8KB4r813cIIQ.png 1200w",
			},
		eUvLsMmaI: link ?? props.eUvLsMmaI,
		GcdPndt9s: gap ?? props.GcdPndt9s ?? 20,
		lgWUklt8e:
			headline ??
			props.lgWUklt8e ??
			"Connecting brands and star creators with Cameo for Business.",
		omjqZujYC: icon ??
			props.omjqZujYC ?? {
				src: "https://framerusercontent.com/images/aeUkRcJxVRUs0RmWoJGG8rSt0.png",
			},
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "SsskJBqHW",
		w_ZHIrSlP: padding ?? props.w_ZHIrSlP ?? 40,
		xW88rvAgh: image ??
			props.xW88rvAgh ?? {
				src: "https://framerusercontent.com/images/83iHGNnBxp1qLhf2Qvd9EVE0XwU.png?scale-down-to=1024",
				srcSet:
					"https://framerusercontent.com/images/83iHGNnBxp1qLhf2Qvd9EVE0XwU.png?scale-down-to=512 512w,https://framerusercontent.com/images/83iHGNnBxp1qLhf2Qvd9EVE0XwU.png?scale-down-to=1024 1024w,https://framerusercontent.com/images/83iHGNnBxp1qLhf2Qvd9EVE0XwU.png 1200w",
			},
	};
};
var createLayoutDependency = (props, variants) =>
	variants.join("-") + props.layoutDependency;
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const { activeLocale, setLocale } = useLocaleInfo();
	const {
		style,
		className,
		layoutId,
		variant,
		xW88rvAgh,
		aoKN1fgc1,
		omjqZujYC,
		lgWUklt8e,
		eUvLsMmaI,
		w_ZHIrSlP,
		GcdPndt9s,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		gestureVariant,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "SsskJBqHW",
		enabledGestures,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const ref1 = React.useRef(null);
	const defaultLayoutId = React.useId();
	const sharedStyleClassNames = [];
	const componentViewport = useComponentViewport();
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<Link href={eUvLsMmaI}>
						<MotionAWithSlideUpOnHover
							{...restProps}
							className={`${cx(serializationHash, ...sharedStyleClassNames, "framer-dm1mpm", className, classNames)} framer-5x038w`}
							data-border={true}
							data-framer-name={"Large"}
							layoutDependency={layoutDependency}
							layoutId={"SsskJBqHW"}
							onHoverEnd={() =>
								setGestureState({
									isHovered: false,
								})
							}
							onHoverStart={() =>
								setGestureState({
									isHovered: true,
								})
							}
							onTap={() =>
								setGestureState({
									isPressed: false,
								})
							}
							onTapCancel={() =>
								setGestureState({
									isPressed: false,
								})
							}
							onTapStart={() =>
								setGestureState({
									isPressed: true,
								})
							}
							ref={ref ?? ref1}
							style={{
								"--border-bottom-width": "1px",
								"--border-color": "rgba(0, 0, 0, 0.08)",
								"--border-left-width": "1px",
								"--border-right-width": "1px",
								"--border-style": "solid",
								"--border-top-width": "1px",
								backdropFilter: "blur(8px)",
								backgroundColor: "rgba(241, 241, 243, 0.45)",
								borderBottomLeftRadius: 24,
								borderBottomRightRadius: 24,
								borderTopLeftRadius: 24,
								borderTopRightRadius: 24,
								WebkitBackdropFilter: "blur(8px)",
								...style,
							}}
							variants={{
								"SsskJBqHW-hover": {
									backgroundColor: "rgba(255, 255, 255, 0.45)",
								},
								jI8WPXyBN: {
									borderBottomLeftRadius: 16,
									borderBottomRightRadius: 16,
									borderTopLeftRadius: 16,
									borderTopRightRadius: 16,
								},
							}}
							{...addPropertyOverrides(
								{
									"SsskJBqHW-hover": {
										"data-framer-name": void 0,
									},
									jI8WPXyBN: {
										"data-framer-name": "Mobile",
									},
								},
								baseVariant,
								gestureVariant,
							)}
						>
							<Image
								background={{
									alt: "",
									fit: "fill",
									pixelHeight: 900,
									pixelWidth: 1200,
									sizes: componentViewport?.width || "100vw",
									...toResponsiveImage(xW88rvAgh),
								}}
								className={"framer-di44zo"}
								data-framer-name={"Image"}
								layoutDependency={layoutDependency}
								layoutId={"Jz6q0grbK"}
								{...addPropertyOverrides(
									{
										jI8WPXyBN: {
											background: {
												alt: "",
												fit: "fill",
												pixelHeight: 900,
												pixelWidth: 1200,
												sizes: componentViewport?.width || "100vw",
												...toResponsiveImage(aoKN1fgc1),
											},
										},
									},
									baseVariant,
									gestureVariant,
								)}
							/>
							<motion.div
								className={"framer-152ryll"}
								data-border={true}
								data-framer-name={"Info"}
								layoutDependency={layoutDependency}
								layoutId={"AauS5XXOP"}
								style={{
									"--11ng9bb": GcdPndt9s,
									"--16h67fj": w_ZHIrSlP,
									"--border-bottom-width": "0px",
									"--border-color": "rgba(0, 0, 0, 0.08)",
									"--border-left-width": "0px",
									"--border-right-width": "0px",
									"--border-style": "solid",
									"--border-top-width": "1px",
									backgroundColor: "rgb(242, 242, 243)",
								}}
								variants={{
									"SsskJBqHW-hover": {
										backgroundColor:
											"var(--token-5f52f7d8-6e1b-4663-9cb5-3ea98ad338df, rgba(255, 255, 255, 0.65))",
									},
								}}
							>
								<Image
									background={{
										alt: "",
										fit: "fill",
										pixelHeight: 192,
										pixelWidth: 192,
										sizes: "32px",
										...toResponsiveImage(omjqZujYC),
									}}
									className={"framer-1j0jide"}
									data-framer-name={"Icon"}
									layoutDependency={layoutDependency}
									layoutId={"szMWjUKYO"}
								/>
								<RichText
									__fromCanvasComponent={true}
									className={"framer-1tuhcfr"}
									fonts={["CUSTOM;Geist Medium"]}
									layoutDependency={layoutDependency}
									layoutId={"qlEjjfQ0E"}
									style={{
										"--extracted-a0htzi":
											"var(--token-38e34800-80da-44a7-911f-74b9aae91a0c, rgba(0, 0, 0, 0.9))",
										"--framer-link-text-color": "rgb(0, 153, 255)",
										"--framer-link-text-decoration": "underline",
									}}
									text={lgWUklt8e}
									verticalAlignment={"top"}
									withExternalLayout={true}
								>
									<React.Fragment>
										<motion.h3
											style={{
												"--font-selector": "Q1VTVE9NO0dlaXN0IE1lZGl1bQ==",
												"--framer-font-family":
													'"Geist Medium", "Geist Medium Placeholder", sans-serif',
												"--framer-font-size": "24px",
												"--framer-letter-spacing": "-0.02em",
												"--framer-line-height": "1.35em",
												"--framer-text-color":
													"var(--extracted-a0htzi, var(--token-38e34800-80da-44a7-911f-74b9aae91a0c, rgba(0, 0, 0, 0.9)))",
											}}
										>
											{
												"Connecting brands and star creators with Cameo for Business."
											}
										</motion.h3>
									</React.Fragment>
								</RichText>
								<ComponentViewportProvider>
									<motion.div
										className={"framer-10d3h15-container"}
										layoutDependency={layoutDependency}
										layoutId={"AhG0gTXmN-container"}
									>
										{_jsx(stdin_default, {
											h_tzILmxT: 16,
											height: "100%",
											id: "AhG0gTXmN",
											layoutId: "AhG0gTXmN",
											width: "100%",
											...addPropertyOverrides(
												{
													jI8WPXyBN: {
														h_tzILmxT: 18,
													},
												},
												baseVariant,
												gestureVariant,
											),
										})}
									</motion.div>
								</ComponentViewportProvider>
							</motion.div>
						</MotionAWithSlideUpOnHover>
					</Link>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-weyW7.framer-5x038w, .framer-weyW7 .framer-5x038w { display: block; }",
	".framer-weyW7.framer-dm1mpm { align-content: flex-start; align-items: flex-start; cursor: pointer; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: flex-start; overflow: hidden; padding: 0px; position: relative; text-decoration: none; width: 600px; will-change: var(--framer-will-change-override, transform); }",
	".framer-weyW7 .framer-di44zo { aspect-ratio: 1.3333333333333333 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 450px); overflow: hidden; position: relative; width: 100%; }",
	".framer-weyW7 .framer-152ryll { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: calc(max(0, var(--11ng9bb)) * 1px); height: min-content; justify-content: flex-start; overflow: hidden; padding: calc(max(0, var(--16h67fj)) * 1px); position: relative; width: 100%; }",
	".framer-weyW7 .framer-1j0jide { aspect-ratio: 1 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 32px); overflow: hidden; position: relative; width: 32px; }",
	".framer-weyW7 .framer-1tuhcfr { flex: none; height: auto; max-width: 450px; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
	".framer-weyW7 .framer-10d3h15-container { flex: none; height: auto; position: relative; width: auto; }",
	"@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-weyW7.framer-dm1mpm, .framer-weyW7 .framer-152ryll { gap: 0px; } .framer-weyW7.framer-dm1mpm > * { margin: 0px; margin-bottom: calc(0px / 2); margin-top: calc(0px / 2); } .framer-weyW7.framer-dm1mpm > :first-child, .framer-weyW7 .framer-152ryll > :first-child { margin-top: 0px; } .framer-weyW7.framer-dm1mpm > :last-child, .framer-weyW7 .framer-152ryll > :last-child { margin-bottom: 0px; } .framer-weyW7 .framer-152ryll > * { margin: 0px; margin-bottom: calc(calc(max(0, var(--11ng9bb)) * 1px) / 2); margin-top: calc(calc(max(0, var(--11ng9bb)) * 1px) / 2); } }",
	".framer-weyW7.framer-v-1t34i5y.framer-dm1mpm { cursor: unset; width: 335px; }",
	".framer-weyW7.framer-v-1t34i5y .framer-di44zo { aspect-ratio: 1.7777777777777777 / 1; height: var(--framer-aspect-ratio-supported, 189px); }",
	'.framer-weyW7[data-border="true"]::after, .framer-weyW7 [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; pointer-events: none; }',
];
var FramerLDHHFyFz0 = withCSS(Component, css, "framer-weyW7");
var stdin_default2 = FramerLDHHFyFz0;
FramerLDHHFyFz0.displayName = "Project Card";
FramerLDHHFyFz0.defaultProps = {
	height: 691,
	width: 600,
};
addPropertyControls(FramerLDHHFyFz0, {
	variant: {
		options: ["SsskJBqHW", "jI8WPXyBN"],
		optionTitles: ["Large", "Mobile"],
		title: "Variant",
		type: ControlType.Enum,
	},
	xW88rvAgh: {
		__defaultAssetReference:
			"data:framer/asset-reference,83iHGNnBxp1qLhf2Qvd9EVE0XwU.png?originalFilename=C4B+Home+thumb+4x3.png&preferredSize=auto",
		title: "Image",
		type: ControlType.ResponsiveImage,
	},
	aoKN1fgc1: {
		__defaultAssetReference:
			"data:framer/asset-reference,pjzjj6MnILAx2z8KB4r813cIIQ.png?originalFilename=Edit+Story+Thumb+Mobile.png&preferredSize=auto",
		title: "Mobile Image",
		type: ControlType.ResponsiveImage,
	},
	omjqZujYC: {
		__defaultAssetReference:
			"data:framer/asset-reference,aeUkRcJxVRUs0RmWoJGG8rSt0.png?originalFilename=Cameo+App+Icon.png&preferredSize=auto",
		title: "Icon",
		type: ControlType.ResponsiveImage,
	},
	lgWUklt8e: {
		defaultValue:
			"Connecting brands and star creators with Cameo for Business.",
		displayTextArea: false,
		title: "Headline",
		type: ControlType.String,
	},
	eUvLsMmaI: {
		title: "Link",
		type: ControlType.Link,
	},
	w_ZHIrSlP: {
		defaultValue: 40,
		min: 0,
		title: "Padding",
		type: ControlType.Number,
	},
	GcdPndt9s: {
		defaultValue: 20,
		min: 0,
		title: "Gap",
		type: ControlType.Number,
	},
});
addFonts(
	FramerLDHHFyFz0,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "Geist Medium",
					source: "custom",
					url: "https://framerusercontent.com/assets/dNqH0c4qjo3RGmYZnJknwKtT0.woff2",
				},
			],
		},
		...LinkButtonFonts,
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:project-card
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "jI8WPXyBN",
	xl: "SsskJBqHW",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"1763929c89cf4969ad190da187fc25ea516fa82b7cf163cf1161896117bee1d5"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default2, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders ProjectCardFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"1763929c89cf4969ad190da187fc25ea516fa82b7cf163cf1161896117bee1d5"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default2}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default2);
var project_card_default = ComponentWithRoot;
export { project_card_default as default };
