// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 1763929c89cf4969 "Patrick McKowen", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Dark Mode' | 'Light Mode' // Variant
 * amount?: string // Amount
}} Props

 */
import { className, css, fonts } from "./chunks/chunk-SNIB7V3T.js";
import { routes } from "./chunks/chunk-IRNZKG45.js";

// virtual:section-number
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/J4DDgkm5QMXtgu56PQo3/SA7GxCqLhUKLU6Wd6E50/jPd56Qj0q.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	RichText,
	useConstant,
	useIsOnFramerCanvas,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
var cycleOrder = ["cSILRVm2J", "q4kH3z8pK"];
var serializationHash = "framer-4NeTF";
var variantClassNames = {
	cSILRVm2J: "framer-v-k8i02r",
	q4kH3z8pK: "framer-v-1hsijvw",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants === null || variants === void 0
		? void 0
		: variants.forEach(
				(variant) =>
					variant && Object.assign(nextOverrides, overrides[variant]),
			);
	return nextOverrides;
}
var transitions = {
	default: {
		damping: 60,
		delay: 0,
		mass: 1,
		stiffness: 500,
		type: "spring",
	},
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition =
		value !== null && value !== void 0 ? value : config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var humanReadableVariantMap = {
	"Dark Mode": "cSILRVm2J",
	"Light Mode": "q4kH3z8pK",
};
var getProps = ({ amount, height, id, width, ...props }) => {
	var _ref, _humanReadableVariantMap_props_variant, _ref1;
	return {
		...props,
		eYAdJzwoc:
			(_ref =
				amount !== null && amount !== void 0 ? amount : props.eYAdJzwoc) !==
				null && _ref !== void 0
				? _ref
				: "01",
		variant:
			(_ref1 =
				(_humanReadableVariantMap_props_variant =
					humanReadableVariantMap[props.variant]) !== null &&
				_humanReadableVariantMap_props_variant !== void 0
					? _humanReadableVariantMap_props_variant
					: props.variant) !== null && _ref1 !== void 0
				? _ref1
				: "cSILRVm2J",
	};
};
var createLayoutDependency = (props, variants) =>
	variants.join("-") + props.layoutDependency;
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const { activeLocale, setLocale } = useLocaleInfo();
	const {
		style,
		className: className2,
		layoutId,
		variant,
		eYAdJzwoc,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		gestureVariant,
		setGestureState,
		setVariant,
		transition,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "cSILRVm2J",
		transitions,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const isOnCanvas = useIsOnFramerCanvas();
	const initialVariant = useConstant(() => variant);
	const ref1 = React.useRef(null);
	const defaultLayoutId = React.useId();
	const sharedStyleClassNames = [className];
	return (
		<LayoutGroup
			id={layoutId !== null && layoutId !== void 0 ? layoutId : defaultLayoutId}
		>
			<Transition value={transition}>
				<motion.div
					{...restProps}
					animate={variants}
					className={cx(
						serializationHash,
						...sharedStyleClassNames,
						"framer-k8i02r",
						className2,
						classNames,
					)}
					data-framer-name={"Dark Mode"}
					initial={isOnCanvas ? variant : initialVariant}
					layoutDependency={layoutDependency}
					layoutId={"cSILRVm2J"}
					onHoverEnd={() =>
						setGestureState({
							isHovered: false,
						})
					}
					onHoverStart={() =>
						setGestureState({
							isHovered: true,
						})
					}
					onTap={() =>
						setGestureState({
							isPressed: false,
						})
					}
					onTapCancel={() =>
						setGestureState({
							isPressed: false,
						})
					}
					onTapStart={() =>
						setGestureState({
							isPressed: true,
						})
					}
					ref={ref !== null && ref !== void 0 ? ref : ref1}
					style={{
						...style,
					}}
					{...addPropertyOverrides(
						{
							q4kH3z8pK: {
								"data-framer-name": "Light Mode",
							},
						},
						baseVariant,
						gestureVariant,
					)}
				>
					<motion.div
						className={"framer-1qnolx0"}
						data-border={true}
						data-framer-name={"Diamond"}
						layoutDependency={layoutDependency}
						layoutId={"tGM2zH2no"}
						style={{
							"--border-bottom-width": "1px",
							"--border-color":
								'var(--token-5dff30ad-54df-442f-b02e-27fac6b1c11f, rgba(255, 255, 255, 0.5)) /* {"name":"Border Primary Dark"} */',
							"--border-left-width": "1px",
							"--border-right-width": "1px",
							"--border-style": "solid",
							"--border-top-width": "1px",
							rotate: 45,
						}}
						variants={{
							q4kH3z8pK: {
								"--border-color":
									'var(--token-b0b454dc-1460-4fbe-a1ad-173ec5f9672f, rgba(0, 0, 0, 0.4)) /* {"name":"Border Primary Light"} */',
							},
						}}
					/>
					<RichText
						__fromCanvasComponent={true}
						className={"framer-1ff850v"}
						layoutDependency={layoutDependency}
						layoutId={"pJLkuJZrG"}
						style={{
							"--extracted-r6o4lv":
								"var(--token-896a38fe-d0ec-4731-b86b-9b448c2d2dcc, rgba(255, 255, 255, 0.45))",
							"--framer-link-text-color": "rgb(0, 153, 255)",
							"--framer-link-text-decoration": "underline",
						}}
						text={eYAdJzwoc}
						verticalAlignment={"top"}
						withExternalLayout={true}
						{...addPropertyOverrides(
							{
								q4kH3z8pK: {
									children: (
										<React.Fragment>
											<motion.p
												className={"framer-styles-preset-127lwpz"}
												data-styles-preset={"ux3sgvyv3"}
											>
												{"01"}
											</motion.p>
										</React.Fragment>
									),
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<React.Fragment>
							<motion.p
								className={"framer-styles-preset-127lwpz"}
								data-styles-preset={"ux3sgvyv3"}
								style={{
									"--framer-text-color":
										"var(--extracted-r6o4lv, var(--token-896a38fe-d0ec-4731-b86b-9b448c2d2dcc, rgba(255, 255, 255, 0.45)))",
								}}
							>
								{"01"}
							</motion.p>
						</React.Fragment>
					</RichText>
				</motion.div>
			</Transition>
		</LayoutGroup>
	);
});
var css2 = [
	'.framer-4NeTF[data-border="true"]::after, .framer-4NeTF [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; pointer-events: none; }',
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-4NeTF.framer-13nvc3d, .framer-4NeTF .framer-13nvc3d { display: block; }",
	".framer-4NeTF.framer-k8i02r { align-content: center; align-items: center; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: 64px; justify-content: center; overflow: hidden; padding: 0px 0px 0px 0px; position: relative; width: 64px; }",
	".framer-4NeTF .framer-1qnolx0 { flex: none; height: 40px; left: calc(50.00000000000002% - 40px / 2); overflow: hidden; position: absolute; top: 12px; width: 40px; z-index: 1; }",
	".framer-4NeTF .framer-1ff850v { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
	"@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-4NeTF.framer-k8i02r { gap: 0px; } .framer-4NeTF.framer-k8i02r > * { margin: 0px; margin-bottom: calc(10px / 2); margin-top: calc(10px / 2); } .framer-4NeTF.framer-k8i02r > :first-child { margin-top: 0px; } .framer-4NeTF.framer-k8i02r > :last-child { margin-bottom: 0px; } }",
	".framer-4NeTF.framer-v-1hsijvw.framer-k8i02r { aspect-ratio: 1 / 1; height: var(--framer-aspect-ratio-supported, 64px); }",
	...css,
];
var FramerjPd56Qj0q = withCSS(Component, css2, "framer-4NeTF");
var stdin_default = FramerjPd56Qj0q;
FramerjPd56Qj0q.displayName = "Section Number";
FramerjPd56Qj0q.defaultProps = {
	height: 64,
	width: 64,
};
addPropertyControls(FramerjPd56Qj0q, {
	variant: {
		options: ["cSILRVm2J", "q4kH3z8pK"],
		optionTitles: ["Dark Mode", "Light Mode"],
		title: "Variant",
		type: ControlType.Enum,
	},
	eYAdJzwoc: {
		defaultValue: "01",
		displayTextArea: false,
		title: "Amount",
		type: ControlType.String,
	},
});
addFonts(FramerjPd56Qj0q, [...fonts]);

// virtual:section-number
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"1763929c89cf4969ad190da187fc25ea516fa82b7cf163cf1161896117bee1d5"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders SectionNumberFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"1763929c89cf4969ad190da187fc25ea516fa82b7cf163cf1161896117bee1d5"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var section_number_default = ComponentWithRoot;
export { section_number_default as default };
