// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 1763929c89cf4969 "Patrick McKowen", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Desktop' | 'Tablet' | 'Mobile' | 'Tablet Case Study' | 'Mobile Case Study' | 'DM Tablet Case Study' | 'DM Mobile Case Study' | 'DM Desktop' // Variant
 * color?: string // Color
}} Props

 */
import { className, css, fonts } from "./chunks/chunk-VWB5RE47.js";
import { routes } from "./chunks/chunk-IRNZKG45.js";

// virtual:site-title
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/rR9SJSMxira3cI8p2E1M/drvWOrgHzcTKl1U36qXs/Q9b__6jzS.js
import { jsx as _jsx } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	getFontsFromSharedStyle,
	Link,
	RichText,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";

// /:https://framerusercontent.com/modules/nZwlm4fhYlqeJlea3lUY/g5hNf1Itj0TwAOqHbhJJ/Uoxt1hbSR.js
import { fontStore } from "unframer";
fontStore.loadFonts([]);
var fonts2 = [];
var css2 = [
	'.framer-aTEF4 .framer-styles-preset-v50zqe:not(.rich-text-wrapper), .framer-aTEF4 .framer-styles-preset-v50zqe.rich-text-wrapper a { --framer-link-current-text-color: var(--token-0646263c-1e98-47cd-9020-0c1d771c1075, #ffffff) /* {"name":"White"} */; --framer-link-current-text-decoration: none; --framer-link-hover-text-color: var(--token-0646263c-1e98-47cd-9020-0c1d771c1075, #ffffff) /* {"name":"White"} */; --framer-link-hover-text-decoration: none; --framer-link-text-color: var(--token-0646263c-1e98-47cd-9020-0c1d771c1075, #ffffff); --framer-link-text-decoration: none; }',
];
var className2 = "framer-aTEF4";

// /:https://framerusercontent.com/modules/Vh4NEnEqdWHvCbvdFCwa/SQ8KZLqYwvZAFvY0Iia7/vdHOOPfOQ.js
import { fontStore as fontStore2 } from "unframer";
fontStore2.loadFonts([]);
var fonts3 = [];
var css3 = [
	'.framer-QDHLm .framer-styles-preset-hqh3k3:not(.rich-text-wrapper), .framer-QDHLm .framer-styles-preset-hqh3k3.rich-text-wrapper a { --framer-link-current-text-color: var(--token-c3ec4201-05df-4ec8-93fe-fe8f0231d7fb, rgba(0, 0, 0, 0.75)) /* {"name":"Black Text Secondary"} */; --framer-link-current-text-decoration: none; --framer-link-hover-text-color: var(--token-c3ec4201-05df-4ec8-93fe-fe8f0231d7fb, rgba(0, 0, 0, 0.75)) /* {"name":"Black Text Secondary"} */; --framer-link-hover-text-decoration: none; --framer-link-text-color: var(--token-c3ec4201-05df-4ec8-93fe-fe8f0231d7fb, rgba(0, 0, 0, 0.75)); --framer-link-text-decoration: none; }',
];
var className3 = "framer-QDHLm";

// /:https://framerusercontent.com/modules/rR9SJSMxira3cI8p2E1M/drvWOrgHzcTKl1U36qXs/Q9b__6jzS.js
var cycleOrder = [
	"LvoaopbQz",
	"vc49LGISs",
	"qIGGa2PYs",
	"l8PGLW0a_",
	"g3PmTIMgm",
	"LQ69zFeX8",
	"kbXvllZqT",
	"vb1XZW3pk",
];
var serializationHash = "framer-l8wrB";
var variantClassNames = {
	g3PmTIMgm: "framer-v-1ee1r6l",
	kbXvllZqT: "framer-v-5zc9gr",
	l8PGLW0a_: "framer-v-19z7hqb",
	LQ69zFeX8: "framer-v-fuvj16",
	LvoaopbQz: "framer-v-1w32osl",
	qIGGa2PYs: "framer-v-165h38y",
	vb1XZW3pk: "framer-v-owpxup",
	vc49LGISs: "framer-v-17x0ra4",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants === null || variants === void 0
		? void 0
		: variants.forEach(
				(variant) =>
					variant && Object.assign(nextOverrides, overrides[variant]),
			);
	return nextOverrides;
}
var transition1 = {
	damping: 60,
	delay: 0,
	mass: 1,
	stiffness: 500,
	type: "spring",
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition =
		value !== null && value !== void 0 ? value : config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion(React.Fragment);
var humanReadableVariantMap = {
	"DM Desktop": "vb1XZW3pk",
	"DM Mobile Case Study": "kbXvllZqT",
	"DM Tablet Case Study": "LQ69zFeX8",
	"Mobile Case Study": "g3PmTIMgm",
	"Tablet Case Study": "l8PGLW0a_",
	Desktop: "LvoaopbQz",
	Mobile: "qIGGa2PYs",
	Tablet: "vc49LGISs",
};
var getProps = ({ color, height, id, width, ...props }) => {
	var _ref, _humanReadableVariantMap_props_variant, _ref1;
	return {
		...props,
		pjQQtpSJ_:
			(_ref = color !== null && color !== void 0 ? color : props.pjQQtpSJ_) !==
				null && _ref !== void 0
				? _ref
				: "var(--token-38e34800-80da-44a7-911f-74b9aae91a0c, rgba(0, 0, 0, 0.9))",
		variant:
			(_ref1 =
				(_humanReadableVariantMap_props_variant =
					humanReadableVariantMap[props.variant]) !== null &&
				_humanReadableVariantMap_props_variant !== void 0
					? _humanReadableVariantMap_props_variant
					: props.variant) !== null && _ref1 !== void 0
				? _ref1
				: "LvoaopbQz",
	};
};
var createLayoutDependency = (props, variants) =>
	variants.join("-") + props.layoutDependency;
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const { activeLocale, setLocale } = useLocaleInfo();
	const {
		style,
		className: className4,
		layoutId,
		variant,
		pjQQtpSJ_,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		gestureVariant,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "LvoaopbQz",
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const ref1 = React.useRef(null);
	const defaultLayoutId = React.useId();
	const sharedStyleClassNames = [className, className3, className2];
	const componentViewport = useComponentViewport();
	return (
		<LayoutGroup
			id={layoutId !== null && layoutId !== void 0 ? layoutId : defaultLayoutId}
		>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.div
						{...restProps}
						className={cx(
							serializationHash,
							...sharedStyleClassNames,
							"framer-1w32osl",
							className4,
							classNames,
						)}
						data-framer-name={"Desktop"}
						layoutDependency={layoutDependency}
						layoutId={"LvoaopbQz"}
						onHoverEnd={() =>
							setGestureState({
								isHovered: false,
							})
						}
						onHoverStart={() =>
							setGestureState({
								isHovered: true,
							})
						}
						onTap={() =>
							setGestureState({
								isPressed: false,
							})
						}
						onTapCancel={() =>
							setGestureState({
								isPressed: false,
							})
						}
						onTapStart={() =>
							setGestureState({
								isPressed: true,
							})
						}
						ref={ref !== null && ref !== void 0 ? ref : ref1}
						style={{
							...style,
						}}
						{...addPropertyOverrides(
							{
								g3PmTIMgm: {
									"data-framer-name": "Mobile Case Study",
								},
								kbXvllZqT: {
									"data-framer-name": "DM Mobile Case Study",
								},
								l8PGLW0a_: {
									"data-framer-name": "Tablet Case Study",
								},
								LQ69zFeX8: {
									"data-framer-name": "DM Tablet Case Study",
								},
								qIGGa2PYs: {
									"data-framer-name": "Mobile",
								},
								vb1XZW3pk: {
									"data-framer-name": "DM Desktop",
								},
								vc49LGISs: {
									"data-framer-name": "Tablet",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<RichText
							__fromCanvasComponent={true}
							className={"framer-1kctq59"}
							fonts={["Inter", "Inter-Bold"]}
							layoutDependency={layoutDependency}
							layoutId={"k0yGH_TyD"}
							style={{
								"--extracted-r6o4lv":
									"var(--variable-reference-pjQQtpSJ_-Q9b__6jzS)",
								"--variable-reference-pjQQtpSJ_-Q9b__6jzS": pjQQtpSJ_,
							}}
							verticalAlignment={"center"}
							withExternalLayout={true}
							{...addPropertyOverrides(
								{
									kbXvllZqT: {
										children: (
											<React.Fragment>
												<motion.p
													className={"framer-styles-preset-buwpek"}
													data-styles-preset={"RQuvxa0Qb"}
													style={{
														"--framer-text-color":
															"var(--extracted-r6o4lv, var(--variable-reference-pjQQtpSJ_-Q9b__6jzS))",
													}}
												>
													<Link
														href={{
															webPageId: "augiA20Il",
														}}
														openInNewTab={false}
														smoothScroll={false}
													>
														<motion.a
															className={"framer-styles-preset-v50zqe"}
															data-styles-preset={"Uoxt1hbSR"}
														>
															<motion.strong>{"Patrick McKowen"}</motion.strong>
														</motion.a>
													</Link>
												</motion.p>
											</React.Fragment>
										),
									},
									LQ69zFeX8: {
										children: (
											<React.Fragment>
												<motion.p
													className={"framer-styles-preset-buwpek"}
													data-styles-preset={"RQuvxa0Qb"}
													style={{
														"--framer-text-color":
															"var(--extracted-r6o4lv, var(--variable-reference-pjQQtpSJ_-Q9b__6jzS))",
													}}
												>
													<Link
														href={{
															webPageId: "augiA20Il",
														}}
														openInNewTab={false}
														smoothScroll={false}
													>
														<motion.a
															className={"framer-styles-preset-v50zqe"}
															data-styles-preset={"Uoxt1hbSR"}
														>
															<motion.strong>{"Patrick McKowen"}</motion.strong>
														</motion.a>
													</Link>
												</motion.p>
											</React.Fragment>
										),
									},
									vb1XZW3pk: {
										children: (
											<React.Fragment>
												<motion.p
													className={"framer-styles-preset-buwpek"}
													data-styles-preset={"RQuvxa0Qb"}
													style={{
														"--framer-text-color":
															"var(--extracted-r6o4lv, var(--variable-reference-pjQQtpSJ_-Q9b__6jzS))",
													}}
												>
													<Link
														href={{
															webPageId: "augiA20Il",
														}}
														openInNewTab={false}
														smoothScroll={false}
													>
														<motion.a
															className={"framer-styles-preset-v50zqe"}
															data-styles-preset={"Uoxt1hbSR"}
														>
															<motion.strong>{"Patrick McKowen"}</motion.strong>
														</motion.a>
													</Link>
												</motion.p>
											</React.Fragment>
										),
									},
								},
								baseVariant,
								gestureVariant,
							)}
						>
							<React.Fragment>
								<motion.p
									className={"framer-styles-preset-buwpek"}
									data-styles-preset={"RQuvxa0Qb"}
									style={{
										"--framer-text-color":
											"var(--extracted-r6o4lv, var(--variable-reference-pjQQtpSJ_-Q9b__6jzS))",
									}}
								>
									<Link
										href={{
											webPageId: "augiA20Il",
										}}
										openInNewTab={false}
										smoothScroll={false}
									>
										<motion.a
											className={"framer-styles-preset-hqh3k3"}
											data-styles-preset={"vdHOOPfOQ"}
										>
											<motion.strong>{"Patrick McKowen"}</motion.strong>
										</motion.a>
									</Link>
								</motion.p>
							</React.Fragment>
						</RichText>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css4 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-l8wrB.framer-14nfi2k, .framer-l8wrB .framer-14nfi2k { display: block; }",
	".framer-l8wrB.framer-1w32osl { align-content: center; align-items: center; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: flex-start; overflow: hidden; padding: 44px 0px 0px 0px; position: relative; width: 1040px; }",
	".framer-l8wrB .framer-1kctq59 { flex: none; height: 47px; position: relative; white-space: pre; width: auto; }",
	"@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-l8wrB.framer-1w32osl { gap: 0px; } .framer-l8wrB.framer-1w32osl > * { margin: 0px; margin-left: calc(10px / 2); margin-right: calc(10px / 2); } .framer-l8wrB.framer-1w32osl > :first-child { margin-left: 0px; } .framer-l8wrB.framer-1w32osl > :last-child { margin-right: 0px; } }",
	".framer-l8wrB.framer-v-17x0ra4.framer-1w32osl { padding: 22px 40px 0px 40px; }",
	".framer-l8wrB.framer-v-165h38y.framer-1w32osl { height: 80px; padding: 20px 20px 20px 0px; width: 390px; }",
	".framer-l8wrB.framer-v-165h38y .framer-1kctq59, .framer-l8wrB.framer-v-1ee1r6l .framer-1kctq59, .framer-l8wrB.framer-v-5zc9gr .framer-1kctq59 { height: auto; }",
	".framer-l8wrB.framer-v-19z7hqb.framer-1w32osl, .framer-l8wrB.framer-v-fuvj16.framer-1w32osl { padding: 22px 0px 0px 0px; }",
	".framer-l8wrB.framer-v-1ee1r6l.framer-1w32osl, .framer-l8wrB.framer-v-5zc9gr.framer-1w32osl { height: 80px; padding: 20px 0px 20px 0px; width: 390px; }",
	".framer-l8wrB.framer-v-owpxup.framer-1w32osl { width: min-content; }",
	...css,
	...css3,
	...css2,
];
var FramerQ9b__6jzS = withCSS(Component, css4, "framer-l8wrB");
var stdin_default = FramerQ9b__6jzS;
FramerQ9b__6jzS.displayName = "Site Title";
FramerQ9b__6jzS.defaultProps = {
	height: 91,
	width: 1040,
};
addPropertyControls(FramerQ9b__6jzS, {
	variant: {
		options: [
			"LvoaopbQz",
			"vc49LGISs",
			"qIGGa2PYs",
			"l8PGLW0a_",
			"g3PmTIMgm",
			"LQ69zFeX8",
			"kbXvllZqT",
			"vb1XZW3pk",
		],
		optionTitles: [
			"Desktop",
			"Tablet",
			"Mobile",
			"Tablet Case Study",
			"Mobile Case Study",
			"DM Tablet Case Study",
			"DM Mobile Case Study",
			"DM Desktop",
		],
		title: "Variant",
		type: ControlType.Enum,
	},
	pjQQtpSJ_: {
		defaultValue:
			'var(--token-38e34800-80da-44a7-911f-74b9aae91a0c, rgba(0, 0, 0, 0.9)) /* {"name":"Black Text Primary"} */',
		title: "Color",
		type: ControlType.Color,
	},
});
addFonts(
	FramerQ9b__6jzS,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://app.framerstatic.com/Inter-Regular.cyrillic-ext-CFTLRB35.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://app.framerstatic.com/Inter-Regular.cyrillic-KKLZBALH.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+1F00-1FFF",
					url: "https://app.framerstatic.com/Inter-Regular.greek-ext-ULEBLIFV.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0370-03FF",
					url: "https://app.framerstatic.com/Inter-Regular.greek-IRHSNFQB.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://app.framerstatic.com/Inter-Regular.latin-ext-VZDUGU3Q.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://app.framerstatic.com/Inter-Regular.latin-JLQMKCHE.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://app.framerstatic.com/Inter-Regular.vietnamese-QK7VSWXK.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://app.framerstatic.com/Inter-Bold.cyrillic-ext-XOTVL7ZR.woff2",
					weight: "700",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://app.framerstatic.com/Inter-Bold.cyrillic-6LOMBC2V.woff2",
					weight: "700",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+1F00-1FFF",
					url: "https://app.framerstatic.com/Inter-Bold.greek-ext-WXWSJXLB.woff2",
					weight: "700",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0370-03FF",
					url: "https://app.framerstatic.com/Inter-Bold.greek-YRST7ODZ.woff2",
					weight: "700",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://app.framerstatic.com/Inter-Bold.latin-ext-BASA5UL3.woff2",
					weight: "700",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://app.framerstatic.com/Inter-Bold.latin-UCM45LQF.woff2",
					weight: "700",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://app.framerstatic.com/Inter-Bold.vietnamese-OEVJMXEP.woff2",
					weight: "700",
				},
			],
		},
		...getFontsFromSharedStyle(fonts),
		...getFontsFromSharedStyle(fonts3),
		...getFontsFromSharedStyle(fonts2),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:site-title
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "g3PmTIMgm",
	md: "LQ69zFeX8",
	xl: "LvoaopbQz",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"1763929c89cf4969ad190da187fc25ea516fa82b7cf163cf1161896117bee1d5"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders SiteTitleFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"1763929c89cf4969ad190da187fc25ea516fa82b7cf163cf1161896117bee1d5"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var site_title_default = ComponentWithRoot;
export { site_title_default as default };
