// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 1763929c89cf4969 "Patrick McKowen", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Default' | 'Small' // Variant
 * icon?: 'Strategy' | 'Visual' | 'Prototyping' | 'UX' | '0-1' | 'UXR' | 'Mentoring' | 'Design Systems' // Icon
 * title?: string // Title
}} Props

 */
import { stdin_default } from "./chunks/chunk-6AQAO6ZN.js";
import { routes } from "./chunks/chunk-IRNZKG45.js";

// virtual:skill-card
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/lWWPJR0NfEGzdBuvkDKO/QGo7Brtp6FnFO2CaJKKz/OkiuWLTE2.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ComponentViewportProvider,
	ControlType,
	cx,
	getFonts,
	getPropertyControls,
	RichText,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
var SkillIconFonts = getFonts(stdin_default);
var SkillIconControls = getPropertyControls(stdin_default);
var cycleOrder = ["Bm8XeuXDV", "cjTA08qiu"];
var serializationHash = "framer-4TPQt";
var variantClassNames = {
	Bm8XeuXDV: "framer-v-13086tw",
	cjTA08qiu: "framer-v-1h6i8y2",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants === null || variants === void 0
		? void 0
		: variants.forEach(
				(variant) =>
					variant && Object.assign(nextOverrides, overrides[variant]),
			);
	return nextOverrides;
}
var transition1 = {
	damping: 60,
	delay: 0,
	mass: 1,
	stiffness: 500,
	type: "spring",
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition =
		value !== null && value !== void 0 ? value : config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion(React.Fragment);
var humanReadableEnumMap = {
	"0-1": "AMcmqyGmE",
	"Design Systems": "biV_jrj1k",
	Mentoring: "E8qhs6qEw",
	Prototyping: "LT53qLEz3",
	Strategy: "HvPOAuc5A",
	UX: "pAsM8XMpy",
	UXR: "DphAsIM6D",
	Visual: "R_u3i25O8",
};
var humanReadableVariantMap = {
	Default: "Bm8XeuXDV",
	Small: "cjTA08qiu",
};
var getProps = ({ height, icon, id, title, width, ...props }) => {
	var _humanReadableEnumMap_icon,
		_ref,
		_ref1,
		_humanReadableVariantMap_props_variant,
		_ref2,
		_ref3;
	return {
		...props,
		D7mW3UdHH:
			(_ref1 =
				(_ref =
					(_humanReadableEnumMap_icon = humanReadableEnumMap[icon]) !== null &&
					_humanReadableEnumMap_icon !== void 0
						? _humanReadableEnumMap_icon
						: icon) !== null && _ref !== void 0
					? _ref
					: props.D7mW3UdHH) !== null && _ref1 !== void 0
				? _ref1
				: "HvPOAuc5A",
		variant:
			(_ref2 =
				(_humanReadableVariantMap_props_variant =
					humanReadableVariantMap[props.variant]) !== null &&
				_humanReadableVariantMap_props_variant !== void 0
					? _humanReadableVariantMap_props_variant
					: props.variant) !== null && _ref2 !== void 0
				? _ref2
				: "Bm8XeuXDV",
		W7AV6U43D:
			(_ref3 = title !== null && title !== void 0 ? title : props.W7AV6U43D) !==
				null && _ref3 !== void 0
				? _ref3
				: "Strategy",
	};
};
var createLayoutDependency = (props, variants) =>
	variants.join("-") + props.layoutDependency;
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const { activeLocale, setLocale } = useLocaleInfo();
	const {
		style,
		className,
		layoutId,
		variant,
		D7mW3UdHH,
		W7AV6U43D,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		gestureVariant,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "Bm8XeuXDV",
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const ref1 = React.useRef(null);
	const defaultLayoutId = React.useId();
	const sharedStyleClassNames = [];
	const componentViewport = useComponentViewport();
	return (
		<LayoutGroup
			id={layoutId !== null && layoutId !== void 0 ? layoutId : defaultLayoutId}
		>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.div
						{...restProps}
						className={cx(
							serializationHash,
							...sharedStyleClassNames,
							"framer-13086tw",
							className,
							classNames,
						)}
						data-border={true}
						data-framer-name={"Default"}
						layoutDependency={layoutDependency}
						layoutId={"Bm8XeuXDV"}
						onHoverEnd={() =>
							setGestureState({
								isHovered: false,
							})
						}
						onHoverStart={() =>
							setGestureState({
								isHovered: true,
							})
						}
						onTap={() =>
							setGestureState({
								isPressed: false,
							})
						}
						onTapCancel={() =>
							setGestureState({
								isPressed: false,
							})
						}
						onTapStart={() =>
							setGestureState({
								isPressed: true,
							})
						}
						ref={ref !== null && ref !== void 0 ? ref : ref1}
						style={{
							"--border-bottom-width": "1px",
							"--border-color": "rgba(0, 0, 0, 0.08)",
							"--border-left-width": "1px",
							"--border-right-width": "1px",
							"--border-style": "solid",
							"--border-top-width": "1px",
							backgroundColor: "rgba(241, 241, 243, 0.45)",
							borderBottomLeftRadius: 8,
							borderBottomRightRadius: 8,
							borderTopLeftRadius: 8,
							borderTopRightRadius: 8,
							boxShadow: "0px 1px 2px 0px rgba(0, 0, 0, 0.05000000074505806)",
							...style,
						}}
						{...addPropertyOverrides(
							{
								cjTA08qiu: {
									"data-framer-name": "Small",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<ComponentViewportProvider>
							<motion.div
								className={"framer-gnpp1k-container"}
								layoutDependency={layoutDependency}
								layoutId={"zdG9Fq1Tm-container"}
							>
								{_jsx(stdin_default, {
									height: "100%",
									id: "zdG9Fq1Tm",
									layoutId: "zdG9Fq1Tm",
									variant: D7mW3UdHH,
									width: "100%",
								})}
							</motion.div>
						</ComponentViewportProvider>
						<RichText
							__fromCanvasComponent={true}
							className={"framer-1473ycb"}
							data-framer-name={"Strategy"}
							fonts={["CUSTOM;Geist Regular"]}
							layoutDependency={layoutDependency}
							layoutId={"QTVNOC3sn"}
							style={{
								"--extracted-r6o4lv":
									"var(--token-38e34800-80da-44a7-911f-74b9aae91a0c, rgba(0, 0, 0, 0.9))",
								"--framer-paragraph-spacing": "0px",
							}}
							text={W7AV6U43D}
							verticalAlignment={"top"}
							withExternalLayout={true}
							{...addPropertyOverrides(
								{
									cjTA08qiu: {
										children: (
											<React.Fragment>
												<motion.p
													style={{
														"--font-selector": "Q1VTVE9NO0dlaXN0IFJlZ3VsYXI=",
														"--framer-font-family":
															'"Geist Regular", "Geist Regular Placeholder", sans-serif',
														"--framer-letter-spacing": "-0.01em",
														"--framer-line-height": "100%",
														"--framer-text-color":
															"var(--extracted-r6o4lv, var(--token-38e34800-80da-44a7-911f-74b9aae91a0c, rgba(0, 0, 0, 0.9)))",
													}}
												>
													{"Strategy"}
												</motion.p>
											</React.Fragment>
										),
									},
								},
								baseVariant,
								gestureVariant,
							)}
						>
							<React.Fragment>
								<motion.p
									style={{
										"--font-selector": "Q1VTVE9NO0dlaXN0IFJlZ3VsYXI=",
										"--framer-font-family":
											'"Geist Regular", "Geist Regular Placeholder", sans-serif',
										"--framer-font-size": "20px",
										"--framer-letter-spacing": "-0.01em",
										"--framer-line-height": "100%",
										"--framer-text-color":
											"var(--extracted-r6o4lv, var(--token-38e34800-80da-44a7-911f-74b9aae91a0c, rgba(0, 0, 0, 0.9)))",
									}}
								>
									{"Strategy"}
								</motion.p>
							</React.Fragment>
						</RichText>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-4TPQt.framer-1aiedsg, .framer-4TPQt .framer-1aiedsg { display: block; }",
	".framer-4TPQt.framer-13086tw { align-content: flex-start; align-items: flex-start; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 32px; height: auto; justify-content: flex-start; overflow: visible; padding: 16px; position: relative; width: 245px; }",
	".framer-4TPQt .framer-gnpp1k-container { flex: none; height: auto; position: relative; width: auto; }",
	".framer-4TPQt .framer-1473ycb { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
	"@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-4TPQt.framer-13086tw { gap: 0px; } .framer-4TPQt.framer-13086tw > * { margin: 0px; margin-bottom: calc(32px / 2); margin-top: calc(32px / 2); } .framer-4TPQt.framer-13086tw > :first-child { margin-top: 0px; } .framer-4TPQt.framer-13086tw > :last-child { margin-bottom: 0px; } }",
	".framer-4TPQt.framer-v-1h6i8y2.framer-13086tw { gap: 16px; width: auto; }",
	".framer-4TPQt.framer-v-1h6i8y2 .framer-1473ycb { white-space: pre; width: auto; }",
	"@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-4TPQt.framer-v-1h6i8y2.framer-13086tw { gap: 0px; } .framer-4TPQt.framer-v-1h6i8y2.framer-13086tw > * { margin: 0px; margin-bottom: calc(16px / 2); margin-top: calc(16px / 2); } .framer-4TPQt.framer-v-1h6i8y2.framer-13086tw > :first-child { margin-top: 0px; } .framer-4TPQt.framer-v-1h6i8y2.framer-13086tw > :last-child { margin-bottom: 0px; } }",
	'.framer-4TPQt[data-border="true"]::after, .framer-4TPQt [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; pointer-events: none; }',
];
var FramerOkiuWLTE2 = withCSS(Component, css, "framer-4TPQt");
var stdin_default2 = FramerOkiuWLTE2;
FramerOkiuWLTE2.displayName = "Skill Card";
FramerOkiuWLTE2.defaultProps = {
	height: 108,
	width: 245,
};
addPropertyControls(FramerOkiuWLTE2, {
	variant: {
		options: ["Bm8XeuXDV", "cjTA08qiu"],
		optionTitles: ["Default", "Small"],
		title: "Variant",
		type: ControlType.Enum,
	},
	D7mW3UdHH: (SkillIconControls === null || SkillIconControls === void 0
		? void 0
		: SkillIconControls["variant"]) && {
		...SkillIconControls["variant"],
		defaultValue: "HvPOAuc5A",
		description: void 0,
		hidden: void 0,
		title: "Icon",
	},
	W7AV6U43D: {
		defaultValue: "Strategy",
		displayTextArea: false,
		title: "Title",
		type: ControlType.String,
	},
});
addFonts(
	FramerOkiuWLTE2,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "Geist Regular",
					source: "custom",
					url: "https://framerusercontent.com/assets/fmgcvoo7Pvi75XN7wkBOp5g4i4s.woff2",
				},
			],
		},
		...SkillIconFonts,
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:skill-card
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
	base: "cjTA08qiu",
	xl: "Bm8XeuXDV",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"1763929c89cf4969ad190da187fc25ea516fa82b7cf163cf1161896117bee1d5"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default2, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders SkillCardFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"1763929c89cf4969ad190da187fc25ea516fa82b7cf163cf1161896117bee1d5"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default2}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default2);
var skill_card_default = ComponentWithRoot;
export { skill_card_default as default };
