// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 1763929c89cf4969 "Patrick McKowen", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Default' | 'Open' // Variant
 * title?: string // Title
 * text?: string // Text
 * image?: 'UI' | 'UX' | 'Prototyping' | 'Research' | 'Design System' // Image
}} Props

 */
import {
	className as className2,
	css as css2,
	fonts as fonts2,
} from "./chunks/chunk-VWB5RE47.js";
import { className, css, fonts } from "./chunks/chunk-T6M5HMBG.js";
import { stdin_default } from "./chunks/chunk-URLOE2LX.js";
import "./chunks/chunk-4JZSFPWQ.js";
import "./chunks/chunk-AWZNHXD6.js";
import { routes } from "./chunks/chunk-IRNZKG45.js";

// virtual:skill-accordian
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/Ffvg3je32FSNplAO4Rm9/6VvDi9iiwdpB71AIpbBL/Z3jckc89r.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	getFonts,
	getPropertyControls,
	RichText,
	SVG,
	useActiveVariantCallback,
	useConstant,
	useIsOnFramerCanvas,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
var SkillImageFonts = getFonts(stdin_default);
var SkillImageControls = getPropertyControls(stdin_default);
var cycleOrder = ["OCcNatQjl", "YN6Z5uNPo"];
var serializationHash = "framer-cvmyh";
var variantClassNames = {
	OCcNatQjl: "framer-v-jpxc24",
	YN6Z5uNPo: "framer-v-zjnwfs",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants === null || variants === void 0
		? void 0
		: variants.forEach(
				(variant) =>
					variant && Object.assign(nextOverrides, overrides[variant]),
			);
	return nextOverrides;
}
var transitions = {
	default: {
		damping: 60,
		delay: 0,
		mass: 1,
		stiffness: 500,
		type: "spring",
	},
};
var transition1 = {
	delay: 0,
	duration: 0.3,
	ease: [0.44, 0, 0.56, 1],
	type: "tween",
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition =
		value !== null && value !== void 0 ? value : config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var humanReadableEnumMap = {
	"Design System": "Dcs1c0kjm",
	Prototyping: "oADSfpPAX",
	Research: "jNwetUwa4",
	UI: "q8mMcHabe",
	UX: "Cf96OouZf",
};
var humanReadableVariantMap = {
	Default: "OCcNatQjl",
	Open: "YN6Z5uNPo",
};
var getProps = ({ height, id, image, text, title, width, ...props }) => {
	var _humanReadableEnumMap_image,
		_ref,
		_ref1,
		_humanReadableVariantMap_props_variant,
		_ref2,
		_ref3,
		_ref4;
	return {
		...props,
		QeH1wSy6e:
			(_ref1 =
				(_ref =
					(_humanReadableEnumMap_image = humanReadableEnumMap[image]) !==
						null && _humanReadableEnumMap_image !== void 0
						? _humanReadableEnumMap_image
						: image) !== null && _ref !== void 0
					? _ref
					: props.QeH1wSy6e) !== null && _ref1 !== void 0
				? _ref1
				: "q8mMcHabe",
		variant:
			(_ref2 =
				(_humanReadableVariantMap_props_variant =
					humanReadableVariantMap[props.variant]) !== null &&
				_humanReadableVariantMap_props_variant !== void 0
					? _humanReadableVariantMap_props_variant
					: props.variant) !== null && _ref2 !== void 0
				? _ref2
				: "OCcNatQjl",
		w1Wmfou5x:
			(_ref3 = text !== null && text !== void 0 ? text : props.w1Wmfou5x) !==
				null && _ref3 !== void 0
				? _ref3
				: "I find joy in crafting elegant, intuitive interfaces, and collaborating with engineers to bring them to life.",
		yO7pfAqfT:
			(_ref4 = title !== null && title !== void 0 ? title : props.yO7pfAqfT) !==
				null && _ref4 !== void 0
				? _ref4
				: "Interface Design",
	};
};
var createLayoutDependency = (props, variants) =>
	variants.join("-") + props.layoutDependency;
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const { activeLocale, setLocale } = useLocaleInfo();
	const {
		style,
		className: className3,
		layoutId,
		variant,
		yO7pfAqfT,
		w1Wmfou5x,
		QeH1wSy6e,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		gestureVariant,
		setGestureState,
		setVariant,
		transition,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "OCcNatQjl",
		transitions,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const { activeVariantCallback, delay } =
		useActiveVariantCallback(baseVariant);
	const onTap1lifxp9 = activeVariantCallback(async (...args) => {
		setGestureState({
			isPressed: false,
		});
		setVariant("YN6Z5uNPo");
	});
	const onTap1j28dge = activeVariantCallback(async (...args) => {
		setVariant("OCcNatQjl");
	});
	const isOnCanvas = useIsOnFramerCanvas();
	const initialVariant = useConstant(() => variant);
	const ref1 = React.useRef(null);
	const isDisplayed = () => {
		if (baseVariant === "YN6Z5uNPo") return true;
		return false;
	};
	const defaultLayoutId = React.useId();
	const sharedStyleClassNames = [className2, className];
	return (
		<LayoutGroup
			id={layoutId !== null && layoutId !== void 0 ? layoutId : defaultLayoutId}
		>
			<Transition value={transition}>
				<motion.div
					{...restProps}
					animate={variants}
					className={cx(
						serializationHash,
						...sharedStyleClassNames,
						"framer-jpxc24",
						className3,
						classNames,
					)}
					data-border={true}
					data-framer-name={"Default"}
					data-highlight={true}
					initial={isOnCanvas ? variant : initialVariant}
					layoutDependency={layoutDependency}
					layoutId={"OCcNatQjl"}
					onHoverEnd={() =>
						setGestureState({
							isHovered: false,
						})
					}
					onHoverStart={() =>
						setGestureState({
							isHovered: true,
						})
					}
					onTap={onTap1lifxp9}
					onTapCancel={() =>
						setGestureState({
							isPressed: false,
						})
					}
					onTapStart={() =>
						setGestureState({
							isPressed: true,
						})
					}
					ref={ref !== null && ref !== void 0 ? ref : ref1}
					style={{
						"--border-bottom-width": "1px",
						"--border-color":
							'var(--token-728f2089-2296-4aee-a86c-db2846c58a22, rgba(0, 0, 0, 0.08)) /* {"name":"Black Border Subtle"} */',
						"--border-left-width": "1px",
						"--border-right-width": "1px",
						"--border-style": "solid",
						"--border-top-width": "1px",
						backgroundColor:
							"var(--token-0646263c-1e98-47cd-9020-0c1d771c1075, rgb(255, 255, 255))",
						borderBottomLeftRadius: 8,
						borderBottomRightRadius: 8,
						borderTopLeftRadius: 8,
						borderTopRightRadius: 8,
						boxShadow:
							"0px 1px 1px 0px rgba(0, 0, 0, 0.029999999329447746), 0px 1px 1px 0px rgba(0, 0, 0, 0.019999999552965164), 0px 2px 1px 0px rgba(0, 0, 0, 0.009999999776482582), 0px 4px 1px 0px rgba(0, 0, 0, 0)",
						...style,
					}}
					{...addPropertyOverrides(
						{
							YN6Z5uNPo: {
								"data-framer-name": "Open",
								"data-highlight": void 0,
								onTap: () =>
									setGestureState({
										isPressed: false,
									}),
							},
						},
						baseVariant,
						gestureVariant,
					)}
				>
					<Transition
						{...addPropertyOverrides(
							{
								YN6Z5uNPo: {
									value: transition1,
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion.div
							className={"framer-1c1nyrj"}
							data-framer-name={"Header"}
							layoutDependency={layoutDependency}
							layoutId={"aDmzxmRQK"}
							{...addPropertyOverrides(
								{
									YN6Z5uNPo: {
										"data-highlight": true,
										onTap: onTap1j28dge,
									},
								},
								baseVariant,
								gestureVariant,
							)}
						>
							<RichText
								__fromCanvasComponent={true}
								className={"framer-1nbfw60"}
								layoutDependency={layoutDependency}
								layoutId={"fHK4ynib9"}
								style={{
									"--extracted-r6o4lv":
										"var(--token-38e34800-80da-44a7-911f-74b9aae91a0c, rgba(0, 0, 0, 0.9))",
									"--framer-link-text-color": "rgb(0, 153, 255)",
									"--framer-link-text-decoration": "underline",
								}}
								text={yO7pfAqfT}
								verticalAlignment={"top"}
								withExternalLayout={true}
							>
								<React.Fragment>
									<motion.p
										className={"framer-styles-preset-buwpek"}
										data-styles-preset={"RQuvxa0Qb"}
										style={{
											"--framer-text-color":
												"var(--extracted-r6o4lv, var(--token-38e34800-80da-44a7-911f-74b9aae91a0c, rgba(0, 0, 0, 0.9)))",
										}}
									>
										<motion.strong>{"Interface Design"}</motion.strong>
									</motion.p>
								</React.Fragment>
							</RichText>
							<motion.div
								className={"framer-mxypkd"}
								data-framer-name={"Button"}
								layoutDependency={layoutDependency}
								layoutId={"JHW4SjyJS"}
								style={{
									backgroundColor:
										"var(--token-68366ab7-03aa-46f4-96ae-993f4367e005, rgb(247, 247, 247))",
									borderBottomLeftRadius: 100,
									borderBottomRightRadius: 100,
									borderTopLeftRadius: 100,
									borderTopRightRadius: 100,
								}}
							>
								<SVG
									className={"framer-1hcxu4c"}
									data-framer-name={"graphic"}
									fill={"black"}
									intrinsicHeight={15}
									intrinsicWidth={16}
									layoutDependency={layoutDependency}
									layoutId={"yuCD3XsHd"}
									style={{
										rotate: 0,
									}}
									svg={
										'<svg width="16" height="15" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M.741 7.654c0-.216.076-.401.229-.553a.759.759 0 0 1 .553-.238H7.21V1.186c0-.211.076-.393.228-.545a.74.74 0 0 1 .554-.238.74.74 0 0 1 .554.238.73.73 0 0 1 .237.545v5.677h5.678a.73.73 0 0 1 .545.238.74.74 0 0 1 .237.553.74.74 0 0 1-.237.554.744.744 0 0 1-.545.229H8.783v5.686a.73.73 0 0 1-.237.545.74.74 0 0 1-.554.237.74.74 0 0 1-.554-.237.744.744 0 0 1-.228-.545V8.437H1.523a.773.773 0 0 1-.553-.229.754.754 0 0 1-.229-.554Z" fill="#000" fill-opacity=".9" style="fill:#000;fill-opacity:.9"/></svg>'
									}
									variants={{
										YN6Z5uNPo: {
											rotate: 45,
										},
									}}
									withExternalLayout={true}
								/>
							</motion.div>
						</motion.div>
					</Transition>
					{isDisplayed() && (
						<motion.div
							className={"framer-1g3hk2x"}
							data-framer-name={"Body"}
							layoutDependency={layoutDependency}
							layoutId={"fbqxC6uL_"}
							style={{
								opacity: 0,
							}}
							variants={{
								YN6Z5uNPo: {
									opacity: 1,
								},
							}}
						>
							<motion.div
								className={"framer-1uaap2e"}
								data-framer-name={"Description"}
								layoutDependency={layoutDependency}
								layoutId={"dBRBcLTYY"}
							>
								<RichText
									__fromCanvasComponent={true}
									className={"framer-1bng1e"}
									layoutDependency={layoutDependency}
									layoutId={"aQnebnb6S"}
									style={{
										"--extracted-r6o4lv":
											"var(--token-c3ec4201-05df-4ec8-93fe-fe8f0231d7fb, rgba(0, 0, 0, 0.75))",
										"--framer-link-text-color": "rgb(0, 153, 255)",
										"--framer-link-text-decoration": "underline",
									}}
									text={w1Wmfou5x}
									verticalAlignment={"top"}
									withExternalLayout={true}
								>
									<React.Fragment>
										<motion.p
											className={"framer-styles-preset-1f40k0m"}
											data-styles-preset={"YYoNxvhFL"}
											style={{
												"--framer-text-color":
													"var(--extracted-r6o4lv, var(--token-c3ec4201-05df-4ec8-93fe-fe8f0231d7fb, rgba(0, 0, 0, 0.75)))",
											}}
										>
											{
												"I find joy in crafting elegant, intuitive interfaces, and collaborating with engineers to bring them to life."
											}
										</motion.p>
									</React.Fragment>
								</RichText>
							</motion.div>
							<motion.div
								className={"framer-loeihb-container"}
								layoutDependency={layoutDependency}
								layoutId={"vnyRoQble-container"}
							>
								{_jsx(stdin_default, {
									height: "100%",
									id: "vnyRoQble",
									layoutId: "vnyRoQble",
									style: {
										height: "100%",
										width: "100%",
									},
									variant: QeH1wSy6e,
									width: "100%",
								})}
							</motion.div>
						</motion.div>
					)}
				</motion.div>
			</Transition>
		</LayoutGroup>
	);
});
var css3 = [
	'.framer-cvmyh[data-border="true"]::after, .framer-cvmyh [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; pointer-events: none; }',
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-cvmyh.framer-1xu0w84, .framer-cvmyh .framer-1xu0w84 { display: block; }",
	".framer-cvmyh.framer-jpxc24 { align-content: center; align-items: center; cursor: pointer; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px 0px 0px 0px; position: relative; width: 335px; }",
	".framer-cvmyh .framer-1c1nyrj { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: 64px; justify-content: flex-start; overflow: visible; padding: 16px 16px 16px 16px; position: relative; width: 100%; }",
	".framer-cvmyh .framer-1nbfw60, .framer-cvmyh .framer-1bng1e { flex: 1 0 0px; height: auto; max-width: 640px; position: relative; white-space: pre-wrap; width: 1px; word-break: break-word; word-wrap: break-word; }",
	".framer-cvmyh .framer-mxypkd { align-content: center; align-items: center; aspect-ratio: 1 / 1; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: var(--framer-aspect-ratio-supported, 32px); justify-content: center; overflow: hidden; padding: 0px 0px 0px 0px; position: relative; width: 32px; will-change: var(--framer-will-change-override, transform); }",
	".framer-cvmyh .framer-1hcxu4c { aspect-ratio: 1.0666666666666667 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 15px); position: relative; width: 16px; }",
	".framer-cvmyh .framer-1g3hk2x { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: hidden; padding: 0px 0px 0px 0px; position: relative; width: 335px; z-index: 1; }",
	".framer-cvmyh .framer-1uaap2e { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px 16px 0px 16px; position: relative; width: 100%; }",
	".framer-cvmyh .framer-loeihb-container { aspect-ratio: 1 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 200px); position: relative; width: 100%; }",
	"@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-cvmyh.framer-jpxc24, .framer-cvmyh .framer-1c1nyrj, .framer-cvmyh .framer-mxypkd, .framer-cvmyh .framer-1g3hk2x, .framer-cvmyh .framer-1uaap2e { gap: 0px; } .framer-cvmyh.framer-jpxc24 > * { margin: 0px; margin-bottom: calc(0px / 2); margin-top: calc(0px / 2); } .framer-cvmyh.framer-jpxc24 > :first-child, .framer-cvmyh .framer-mxypkd > :first-child, .framer-cvmyh .framer-1g3hk2x > :first-child { margin-top: 0px; } .framer-cvmyh.framer-jpxc24 > :last-child, .framer-cvmyh .framer-mxypkd > :last-child, .framer-cvmyh .framer-1g3hk2x > :last-child { margin-bottom: 0px; } .framer-cvmyh .framer-1c1nyrj > *, .framer-cvmyh .framer-1uaap2e > * { margin: 0px; margin-left: calc(10px / 2); margin-right: calc(10px / 2); } .framer-cvmyh .framer-1c1nyrj > :first-child, .framer-cvmyh .framer-1uaap2e > :first-child { margin-left: 0px; } .framer-cvmyh .framer-1c1nyrj > :last-child, .framer-cvmyh .framer-1uaap2e > :last-child { margin-right: 0px; } .framer-cvmyh .framer-mxypkd > *, .framer-cvmyh .framer-1g3hk2x > * { margin: 0px; margin-bottom: calc(10px / 2); margin-top: calc(10px / 2); } }",
	".framer-cvmyh.framer-v-zjnwfs.framer-jpxc24 { cursor: unset; overflow: hidden; will-change: var(--framer-will-change-override, transform); }",
	".framer-cvmyh.framer-v-zjnwfs .framer-1c1nyrj { cursor: pointer; }",
	".framer-cvmyh.framer-v-zjnwfs .framer-1g3hk2x { width: 100%; }",
	".framer-cvmyh.framer-v-zjnwfs .framer-loeihb-container { height: var(--framer-aspect-ratio-supported, 335px); }",
	...css2,
	...css,
];
var FramerZ3jckc89r = withCSS(Component, css3, "framer-cvmyh");
var stdin_default2 = FramerZ3jckc89r;
FramerZ3jckc89r.displayName = "Skill Accordian";
FramerZ3jckc89r.defaultProps = {
	height: 64,
	width: 335,
};
addPropertyControls(FramerZ3jckc89r, {
	variant: {
		options: ["OCcNatQjl", "YN6Z5uNPo"],
		optionTitles: ["Default", "Open"],
		title: "Variant",
		type: ControlType.Enum,
	},
	yO7pfAqfT: {
		defaultValue: "Interface Design",
		displayTextArea: false,
		title: "Title",
		type: ControlType.String,
	},
	w1Wmfou5x: {
		defaultValue:
			"I find joy in crafting elegant, intuitive interfaces, and collaborating with engineers to bring them to life.",
		displayTextArea: false,
		title: "Text",
		type: ControlType.String,
	},
	QeH1wSy6e: (SkillImageControls === null || SkillImageControls === void 0
		? void 0
		: SkillImageControls["variant"]) && {
		...SkillImageControls["variant"],
		defaultValue: "q8mMcHabe",
		description: void 0,
		hidden: void 0,
		title: "Image",
	},
});
addFonts(FramerZ3jckc89r, [...SkillImageFonts, ...fonts2, ...fonts]);

// virtual:skill-accordian
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"1763929c89cf4969ad190da187fc25ea516fa82b7cf163cf1161896117bee1d5"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default2, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders SkillAccordianFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"1763929c89cf4969ad190da187fc25ea516fa82b7cf163cf1161896117bee1d5"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default2}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default2);
var skill_accordian_default = ComponentWithRoot;
export { skill_accordian_default as default };
