// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 1763929c89cf4969 "Patrick McKowen", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * title?: string // Title
}} Props

 */
import { routes } from "./chunks/chunk-IRNZKG45.js";

// virtual:tag
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/Hk1PK9V2RY9VonitwUJI/DvTVmBxbfqhjs8g1Wu6B/bhbIVNmaz.js
import { jsx as _jsx } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	RichText,
	useConstant,
	useIsOnFramerCanvas,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
var cycleOrder = ["IfxlykhEo"];
var serializationHash = "framer-u8HCW";
var variantClassNames = {
	IfxlykhEo: "framer-v-e1xs08",
};
var transitions = {
	default: {
		damping: 60,
		delay: 0,
		mass: 1,
		stiffness: 500,
		type: "spring",
	},
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition =
		value !== null && value !== void 0 ? value : config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var getProps = ({ height, id, title, width, ...props }) => {
	var _ref;
	return {
		...props,
		RvLGFZV2f:
			(_ref = title !== null && title !== void 0 ? title : props.RvLGFZV2f) !==
				null && _ref !== void 0
				? _ref
				: "B2B",
	};
};
var createLayoutDependency = (props, variants) =>
	variants.join("-") + props.layoutDependency;
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const { activeLocale, setLocale } = useLocaleInfo();
	const { style, className, layoutId, variant, RvLGFZV2f, ...restProps } =
		getProps(props);
	const {
		baseVariant,
		classNames,
		gestureVariant,
		setGestureState,
		setVariant,
		transition,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "IfxlykhEo",
		transitions,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const isOnCanvas = useIsOnFramerCanvas();
	const initialVariant = useConstant(() => variant);
	const ref1 = React.useRef(null);
	const defaultLayoutId = React.useId();
	const sharedStyleClassNames = [];
	return (
		<LayoutGroup
			id={layoutId !== null && layoutId !== void 0 ? layoutId : defaultLayoutId}
		>
			<Transition value={transition}>
				<motion.div
					{...restProps}
					animate={variants}
					className={cx(
						serializationHash,
						...sharedStyleClassNames,
						"framer-e1xs08",
						className,
						classNames,
					)}
					data-border={true}
					data-framer-name={"Variant 1"}
					initial={isOnCanvas ? variant : initialVariant}
					layoutDependency={layoutDependency}
					layoutId={"IfxlykhEo"}
					onHoverEnd={() =>
						setGestureState({
							isHovered: false,
						})
					}
					onHoverStart={() =>
						setGestureState({
							isHovered: true,
						})
					}
					onTap={() =>
						setGestureState({
							isPressed: false,
						})
					}
					onTapCancel={() =>
						setGestureState({
							isPressed: false,
						})
					}
					onTapStart={() =>
						setGestureState({
							isPressed: true,
						})
					}
					ref={ref !== null && ref !== void 0 ? ref : ref1}
					style={{
						"--border-bottom-width": "1px",
						"--border-color":
							'var(--token-8d9f1bee-3d7d-4a43-8cd2-86f1117f4aa0, rgba(255, 255, 255, 0.1)) /* {"name":"White Border"} */',
						"--border-left-width": "1px",
						"--border-right-width": "1px",
						"--border-style": "solid",
						"--border-top-width": "1px",
						borderBottomLeftRadius: 100,
						borderBottomRightRadius: 100,
						borderTopLeftRadius: 100,
						borderTopRightRadius: 100,
						...style,
					}}
				>
					<RichText
						__fromCanvasComponent={true}
						className={"framer-7kkwgm"}
						fonts={["CUSTOM;Geist Mono Variable Regular"]}
						layoutDependency={layoutDependency}
						layoutId={"z4osTAiRb"}
						style={{
							"--extracted-r6o4lv":
								"var(--token-896a38fe-d0ec-4731-b86b-9b448c2d2dcc, rgba(255, 255, 255, 0.45))",
							"--framer-link-text-color": "rgb(0, 153, 255)",
							"--framer-link-text-decoration": "underline",
						}}
						text={RvLGFZV2f}
						verticalAlignment={"top"}
						withExternalLayout={true}
					>
						<React.Fragment>
							<motion.p
								style={{
									"--font-selector":
										"Q1VTVE9NO0dlaXN0IE1vbm8gVmFyaWFibGUgUmVndWxhcg==",
									"--framer-font-family":
										'"Geist Mono Variable Regular", "Geist Mono Variable Regular Placeholder", monospace',
									"--framer-font-size": "14px",
									"--framer-line-height": "1.4em",
									"--framer-text-color":
										"var(--extracted-r6o4lv, var(--token-896a38fe-d0ec-4731-b86b-9b448c2d2dcc, rgba(255, 255, 255, 0.45)))",
									"--framer-text-transform": "uppercase",
								}}
							>
								{"B2B"}
							</motion.p>
						</React.Fragment>
					</RichText>
				</motion.div>
			</Transition>
		</LayoutGroup>
	);
});
var css = [
	'.framer-u8HCW[data-border="true"]::after, .framer-u8HCW [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; pointer-events: none; }',
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-u8HCW.framer-5p18t1, .framer-u8HCW .framer-5p18t1 { display: block; }",
	".framer-u8HCW.framer-e1xs08 { align-content: center; align-items: center; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: 44px; justify-content: center; overflow: hidden; padding: 10px 20px 10px 20px; position: relative; width: min-content; will-change: var(--framer-will-change-override, transform); }",
	".framer-u8HCW .framer-7kkwgm { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
	"@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-u8HCW.framer-e1xs08 { gap: 0px; } .framer-u8HCW.framer-e1xs08 > * { margin: 0px; margin-left: calc(10px / 2); margin-right: calc(10px / 2); } .framer-u8HCW.framer-e1xs08 > :first-child { margin-left: 0px; } .framer-u8HCW.framer-e1xs08 > :last-child { margin-right: 0px; } }",
];
var FramerbhbIVNmaz = withCSS(Component, css, "framer-u8HCW");
var stdin_default = FramerbhbIVNmaz;
FramerbhbIVNmaz.displayName = "Tag";
FramerbhbIVNmaz.defaultProps = {
	height: 44,
	width: 65,
};
addPropertyControls(FramerbhbIVNmaz, {
	RvLGFZV2f: {
		defaultValue: "B2B",
		displayTextArea: false,
		title: "Title",
		type: ControlType.String,
	},
});
addFonts(FramerbhbIVNmaz, [
	{
		family: "Geist Mono Variable Regular",
		source: "custom",
		url: "https://framerusercontent.com/assets/awrUu69VgkDKQl3yHJCBKi9Zam8.woff2",
	},
]);

// virtual:tag
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"1763929c89cf4969ad190da187fc25ea516fa82b7cf163cf1161896117bee1d5"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders TagFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"1763929c89cf4969ad190da187fc25ea516fa82b7cf163cf1161896117bee1d5"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var tag_default = ComponentWithRoot;
export { tag_default as default };
