// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 1763929c89cf4969 "Patrick McKowen", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * file?: string // File
}} Props

 */
import { Video } from "./chunks/chunk-4JZSFPWQ.js";
import "./chunks/chunk-AWZNHXD6.js";
import { routes } from "./chunks/chunk-IRNZKG45.js";

// virtual:video-i-phone-frame
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/fLvjO66COBzICxFR1Dtc/3wK37YQgpIPKopi5R7Am/DFPRmtl6Y.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ComponentViewportProvider,
	cx,
	getFonts,
	getPropertyControls,
	Image,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
var VideoFonts = getFonts(Video);
var VideoControls = getPropertyControls(Video);
var cycleOrder = ["P1tI9sGwB"];
var serializationHash = "framer-QtKHh";
var variantClassNames = {
	P1tI9sGwB: "framer-v-1q2hdek",
};
var transition1 = {
	damping: 60,
	delay: 0,
	mass: 1,
	stiffness: 500,
	type: "spring",
};
var transformTemplate1 = (_, t) => `translate(-50%, -50%) ${t}`;
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition =
		value !== null && value !== void 0 ? value : config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion(React.Fragment);
var getProps = ({ file, height, id, width, ...props }) => {
	var _ref;
	return {
		...props,
		e7pEJkkTI:
			(_ref = file !== null && file !== void 0 ? file : props.e7pEJkkTI) !==
				null && _ref !== void 0
				? _ref
				: "https://framerusercontent.com/assets/994D9VDDsvZ1OlanOKNU1d8rV6Y.mp4",
	};
};
var createLayoutDependency = (props, variants) =>
	variants.join("-") + props.layoutDependency;
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const { activeLocale, setLocale } = useLocaleInfo();
	const { style, className, layoutId, variant, e7pEJkkTI, ...restProps } =
		getProps(props);
	const {
		baseVariant,
		classNames,
		gestureVariant,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "P1tI9sGwB",
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const ref1 = React.useRef(null);
	const defaultLayoutId = React.useId();
	const sharedStyleClassNames = [];
	const componentViewport = useComponentViewport();
	return (
		<LayoutGroup
			id={layoutId !== null && layoutId !== void 0 ? layoutId : defaultLayoutId}
		>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.div
						{...restProps}
						className={cx(
							serializationHash,
							...sharedStyleClassNames,
							"framer-1q2hdek",
							className,
							classNames,
						)}
						data-framer-name={"Variant 1"}
						layoutDependency={layoutDependency}
						layoutId={"P1tI9sGwB"}
						onHoverEnd={() =>
							setGestureState({
								isHovered: false,
							})
						}
						onHoverStart={() =>
							setGestureState({
								isHovered: true,
							})
						}
						onTap={() =>
							setGestureState({
								isPressed: false,
							})
						}
						onTapCancel={() =>
							setGestureState({
								isPressed: false,
							})
						}
						onTapStart={() =>
							setGestureState({
								isPressed: true,
							})
						}
						ref={ref !== null && ref !== void 0 ? ref : ref1}
						style={{
							...style,
						}}
					>
						<ComponentViewportProvider>
							<motion.div
								className={"framer-1q46cxv-container"}
								layoutDependency={layoutDependency}
								layoutId={"VwiPoJQFA-container"}
								transformTemplate={transformTemplate1}
							>
								<Video
									backgroundColor={"rgba(0, 0, 0, 0)"}
									borderRadius={0}
									bottomLeftRadius={0}
									bottomRightRadius={0}
									controls={false}
									height={"100%"}
									id={"VwiPoJQFA"}
									isMixedBorderRadius={false}
									layoutId={"VwiPoJQFA"}
									loop={true}
									muted={true}
									objectFit={"cover"}
									playing={true}
									posterEnabled={false}
									srcFile={e7pEJkkTI}
									srcType={"Upload"}
									srcUrl={
										"https://assets.mixkit.co/videos/preview/mixkit-shining-sun-in-the-sky-surrounded-by-moving-clouds-31793-small.mp4"
									}
									startTime={0}
									style={{
										height: "100%",
										width: "100%",
									}}
									topLeftRadius={0}
									topRightRadius={0}
									volume={25}
									width={"100%"}
								/>
							</motion.div>
						</ComponentViewportProvider>
						<Image
							background={{
								alt: "",
								fit: "fill",
								pixelHeight: 1615,
								pixelWidth: 800,
								sizes: "1px",
								src: "https://framerusercontent.com/images/8URMd96Rf5vcc7td8c8VnkB9e1I.png",
								srcSet:
									"https://framerusercontent.com/images/8URMd96Rf5vcc7td8c8VnkB9e1I.png 800w",
							}}
							className={"framer-rf6g0u"}
							layoutDependency={layoutDependency}
							layoutId={"DJ4aqa7ku"}
						/>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-QtKHh.framer-gdi5ff, .framer-QtKHh .framer-gdi5ff { display: block; }",
	".framer-QtKHh.framer-1q2hdek { align-content: center; align-items: center; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 10px; height: 424px; justify-content: center; overflow: hidden; padding: 0px; position: relative; width: 210px; }",
	".framer-QtKHh .framer-1q46cxv-container { aspect-ratio: 0.46120689655172414 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 406px); left: 50%; position: absolute; top: 50%; width: 89%; z-index: 1; }",
	".framer-QtKHh .framer-rf6g0u { aspect-ratio: 0.4953764861294584 / 1; flex: 1 0 0px; height: 1px; overflow: hidden; position: relative; width: var(--framer-aspect-ratio-supported, 210px); z-index: 1; }",
	"@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-QtKHh.framer-1q2hdek { gap: 0px; } .framer-QtKHh.framer-1q2hdek > * { margin: 0px; margin-bottom: calc(10px / 2); margin-top: calc(10px / 2); } .framer-QtKHh.framer-1q2hdek > :first-child { margin-top: 0px; } .framer-QtKHh.framer-1q2hdek > :last-child { margin-bottom: 0px; } }",
];
var FramerDFPRmtl6Y = withCSS(Component, css, "framer-QtKHh");
var stdin_default = FramerDFPRmtl6Y;
FramerDFPRmtl6Y.displayName = "Video iPhone Frame";
FramerDFPRmtl6Y.defaultProps = {
	height: 424.5,
	width: 210,
};
addPropertyControls(FramerDFPRmtl6Y, {
	e7pEJkkTI: (VideoControls === null || VideoControls === void 0
		? void 0
		: VideoControls["srcFile"]) && {
		...VideoControls["srcFile"],
		__defaultAssetReference:
			"data:framer/asset-reference,994D9VDDsvZ1OlanOKNU1d8rV6Y.mp4?originalFilename=Edit+Photo.mp4",
		description: void 0,
		hidden: void 0,
		title: "File",
	},
});
addFonts(
	FramerDFPRmtl6Y,
	[
		{
			explicitInter: true,
			fonts: [],
		},
		...VideoFonts,
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:video-i-phone-frame
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"1763929c89cf4969ad190da187fc25ea516fa82b7cf163cf1161896117bee1d5"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders VideoIPhoneFrameFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"1763929c89cf4969ad190da187fc25ea516fa82b7cf163cf1161896117bee1d5"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var video_i_phone_frame_default = ComponentWithRoot;
export { video_i_phone_frame_default as default };
