// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 1763929c89cf4969 "Patrick McKowen", do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Default' | 'Playing' // Variant
}} Props

 */
import { Video } from "./chunks/chunk-4JZSFPWQ.js";
import "./chunks/chunk-AWZNHXD6.js";
import { routes } from "./chunks/chunk-IRNZKG45.js";

// virtual:video-reel
import { Fragment } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/81JHr6FpCftW6VXtmsLK/Gmot9dOuNe4zU9zstQdr/MsetqcaeL.js
import { jsx as _jsx } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	getFonts,
	useConstant,
	useIsOnFramerCanvas,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
var VideoFonts = getFonts(Video);
var cycleOrder = ["LfiZt_rWJ", "fmofYVSEy"];
var serializationHash = "framer-sxiR4";
var variantClassNames = {
	fmofYVSEy: "framer-v-16bblob",
	LfiZt_rWJ: "framer-v-kjvwim",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants === null || variants === void 0
		? void 0
		: variants.forEach(
				(variant) =>
					variant && Object.assign(nextOverrides, overrides[variant]),
			);
	return nextOverrides;
}
var transitions = {
	default: {
		damping: 60,
		delay: 0,
		mass: 1,
		stiffness: 500,
		type: "spring",
	},
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition =
		value !== null && value !== void 0 ? value : config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var humanReadableVariantMap = {
	Default: "LfiZt_rWJ",
	Playing: "fmofYVSEy",
};
var getProps = ({ height, id, width, ...props }) => {
	var _humanReadableVariantMap_props_variant, _ref;
	return {
		...props,
		variant:
			(_ref =
				(_humanReadableVariantMap_props_variant =
					humanReadableVariantMap[props.variant]) !== null &&
				_humanReadableVariantMap_props_variant !== void 0
					? _humanReadableVariantMap_props_variant
					: props.variant) !== null && _ref !== void 0
				? _ref
				: "LfiZt_rWJ",
	};
};
var createLayoutDependency = (props, variants) =>
	variants.join("-") + props.layoutDependency;
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const { activeLocale, setLocale } = useLocaleInfo();
	const { style, className, layoutId, variant, ...restProps } = getProps(props);
	const {
		baseVariant,
		classNames,
		gestureVariant,
		setGestureState,
		setVariant,
		transition,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "LfiZt_rWJ",
		transitions,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const isOnCanvas = useIsOnFramerCanvas();
	const initialVariant = useConstant(() => variant);
	const ref1 = React.useRef(null);
	const defaultLayoutId = React.useId();
	const sharedStyleClassNames = [];
	return (
		<LayoutGroup
			id={layoutId !== null && layoutId !== void 0 ? layoutId : defaultLayoutId}
		>
			<Transition value={transition}>
				<motion.div
					{...restProps}
					animate={variants}
					className={cx(
						serializationHash,
						...sharedStyleClassNames,
						"framer-kjvwim",
						className,
						classNames,
					)}
					data-framer-name={"Default"}
					initial={isOnCanvas ? variant : initialVariant}
					layoutDependency={layoutDependency}
					layoutId={"LfiZt_rWJ"}
					onHoverEnd={() =>
						setGestureState({
							isHovered: false,
						})
					}
					onHoverStart={() =>
						setGestureState({
							isHovered: true,
						})
					}
					onTap={() =>
						setGestureState({
							isPressed: false,
						})
					}
					onTapCancel={() =>
						setGestureState({
							isPressed: false,
						})
					}
					onTapStart={() =>
						setGestureState({
							isPressed: true,
						})
					}
					ref={ref !== null && ref !== void 0 ? ref : ref1}
					style={{
						...style,
					}}
					{...addPropertyOverrides(
						{
							fmofYVSEy: {
								"data-framer-name": "Playing",
							},
						},
						baseVariant,
						gestureVariant,
					)}
				>
					<motion.div
						className={"framer-1qat81o-container"}
						layoutDependency={layoutDependency}
						layoutId={"YsFzDuofy-container"}
					>
						<Video
							backgroundColor={"rgba(0, 0, 0, 0)"}
							borderRadius={0}
							bottomLeftRadius={0}
							bottomRightRadius={0}
							controls={false}
							height={"100%"}
							id={"YsFzDuofy"}
							isMixedBorderRadius={false}
							layoutId={"YsFzDuofy"}
							loop={true}
							muted={true}
							objectFit={"cover"}
							playing={false}
							posterEnabled={false}
							srcFile={
								"https://framerusercontent.com/assets/sj8cBV1Rgoc7LVafQ20WoKfIaaY.mp4"
							}
							srcType={"Upload"}
							srcUrl={
								"https://assets.mixkit.co/videos/preview/mixkit-shining-sun-in-the-sky-surrounded-by-moving-clouds-31793-small.mp4"
							}
							startTime={0}
							style={{
								height: "100%",
								width: "100%",
							}}
							topLeftRadius={0}
							topRightRadius={0}
							volume={25}
							width={"100%"}
							{...addPropertyOverrides(
								{
									fmofYVSEy: {
										playing: true,
									},
								},
								baseVariant,
								gestureVariant,
							)}
						/>
					</motion.div>
				</motion.div>
			</Transition>
		</LayoutGroup>
	);
});
var css = [
	'.framer-sxiR4[data-border="true"]::after, .framer-sxiR4 [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; pointer-events: none; }',
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-sxiR4.framer-iq6989, .framer-sxiR4 .framer-iq6989 { display: block; }",
	".framer-sxiR4.framer-kjvwim { align-content: center; align-items: center; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: hidden; padding: 0px 0px 0px 0px; position: relative; width: 1360px; }",
	".framer-sxiR4 .framer-1qat81o-container { aspect-ratio: 1.7777777777777777 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 765px); pointer-events: none; position: relative; width: 100%; }",
	"@supports (background: -webkit-named-image(i)) and (not (font-palette:dark)) { .framer-sxiR4.framer-kjvwim { gap: 0px; } .framer-sxiR4.framer-kjvwim > * { margin: 0px; margin-left: calc(10px / 2); margin-right: calc(10px / 2); } .framer-sxiR4.framer-kjvwim > :first-child { margin-left: 0px; } .framer-sxiR4.framer-kjvwim > :last-child { margin-right: 0px; } }",
];
var FramerMsetqcaeL = withCSS(Component, css, "framer-sxiR4");
var stdin_default = FramerMsetqcaeL;
FramerMsetqcaeL.displayName = "Video Reel";
FramerMsetqcaeL.defaultProps = {
	height: 765,
	width: 1360,
};
addPropertyControls(FramerMsetqcaeL, {
	variant: {
		options: ["LfiZt_rWJ", "fmofYVSEy"],
		optionTitles: ["Default", "Playing"],
		title: "Variant",
		type: ControlType.Enum,
	},
});
addFonts(FramerMsetqcaeL, [...VideoFonts]);

// virtual:video-reel
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"1763929c89cf4969ad190da187fc25ea516fa82b7cf163cf1161896117bee1d5"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders VideoReelFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"1763929c89cf4969ad190da187fc25ea516fa82b7cf163cf1161896117bee1d5"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var video_reel_default = ComponentWithRoot;
export { video_reel_default as default };
